### ISSUE TITLE
Переименовать образ Докера

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#1038]
Хотелось бы убрать Y из названия в [start.sh](https://github.com/doka-guide/content/blob/main/start.sh)

```
docker pull ydoka/platform
```

И сделать либо `doka/platform`, либо `doka-guide/platform`. Сможем? :)

**Comment by igsekor** [comment]
@pepelsbey вот [нет](https://hub.docker.com/support/doc/how-do-i-rename-a-docker-hub-repository). Можно только создать ещё одну организацию... Будем делать?

**Comment by pepelsbey** [comment]
Давай тогда сделаем doka-guide по примеру организации на Гитхабе.

**Comment by igsekor** [comment]
Название организации должно быть такое: «Use 4 to 30 letters & digits only».

**Comment by pepelsbey** [comment]
dokaguide 🙄
