### ISSUE TITLE
Добавить линтер для меты в материалах

### ISSUE THREAD

**Issue by igsekor** [doka-guide/content#1053]
Готового решения не нашёл. Есть три варианта:
1. Линтинг с помощью [markdownlint](https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md), но придётся писать свои правила. В стандартной есть проверка просто на тему правильности синтаксиса YAML, но не наличия тех или иных тегов и уж тем более последовательности.
2. Сначала парсить `*.md`, а потом пробегать литером по объекту. Это проверит наличие полей, но не строгую последовательность.
3. Всё писать самим.

@pepelsbey @nlopin @furtivite @solarrust что думаете?

**Comment by solarrust** [comment]
Я всё ещё за то, чтобы просто договориться про порядок =)

**Comment by pepelsbey** [comment]
А склеить из грязи и веточек не получится? Откусывать шапку файла, считать её YAML и уже это отдавать в валидатор. Я точно видел готовые решения для валидации чистого YAML.

**Comment by igsekor** [comment]
> А склеить из грязи и веточек не получится?

Запросто. Это тот самый третий вариант 🙃
