### ISSUE TITLE
Yaspeller на прекоммите

### ISSUE THREAD

**Issue by Windrushfarer** [doka-guide/content#1054]
У нас есть проверка `yaspeller` в CI, так может быть имеет смысл поставить его на прекоммите?

Я не вижу особых проблем в плане ухудшения опыта во время написания статей, проверка для пары файлов происходит быстро. Это явно быстрее, чем потом возвращаться в PR посмотреть, что ничего не упало.

**Comment by solarrust** [comment]
Мы уже не раз обсуждали, что для прекоммита надо иметь установленное окружение. А для написания статьи — нет! Да, @pepelsbey?

**Comment by igsekor** [comment]
> У нас есть проверка `yaspeller` в CI, так может быть имеет смысл поставить его на прекоммите?

Мы действительно говорили об этом. Сошлись на том, что написание статей должно быть максимально доступным для всех.

> Я не вижу особых проблем в плане ухудшения опыта во время написания статей, проверка для пары файлов происходит быстро. Это явно быстрее, чем потом возвращаться в PR посмотреть, что ничего не упало.

**Comment by pepelsbey** [comment]
Мы очень не хотим тащить в контент сложные зависимости и прекоммиты. Особенно прекоммиты, когда ты первый раз открыл, написал, коммитишь, а консоль или приложение зависло, что-то крутит, а потом вываливает на тебя ошибку. А если у тебя нет Node.js или он не той версии, а если нет сети, но ты хочешь закоммитить? Начинаются сложности.

Мы хотим, чтобы ошибкой это стало на Гитхабе. Когда мы сможем помочь её исправить, например.

Любой, кто не хочет сюрпризов в пиаре, может локально запустить такое и всё увидеть :)

```
npx yaspeller --only-errors **/*.{md,html}
```

**Comment by Windrushfarer** [comment]
Принял, просто хотя бы узнал мнения :)
Спасибо, закрываю тогда
