### ISSUE TITLE
Привести всю мету к одному формату

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#1056]
Надо привести мету во всех статьях и в документации к одному формату, чтобы в ней было удобно ориентироваться и копировать в новую статью из любой другой.

**Comment by furtivite** [comment]
Кажется, мета сейчас выглядит так:

```markdown
---
title: Название статьи
authors:
  - Никнейм основного автора
contributors:
  - Никнеймы всех соавторов и контрибьюторов
designers: Никнейм дизайнера
summary:
  - Альтернативные теги для работы поиска
cover:
  desktop: 'images/desktop.png'
  mobile: 'images/mobile.png'
  alt: 'Альтернативное описание для обложки'
tags:
  - doka
---
```

Предложение вынести все списки в конец, опциональные должны быть ниже:

```markdown
---
title: Название статьи
authors:
  - Никнейм основного автора
contributors:
  - Никнеймы всех соавторов и контрибьюторов
cover:
  desktop: 'images/desktop.png'
  mobile: 'images/mobile.png'
  alt: 'Альтернативное описание для обложки'
tags:
  - doka
summary:
  - Альтернативные теги для работы поиска

---
```

Дизайнеров убрал, потому что у нас есть постоянная команда, которая будет указана отдельно. 

Обложки подвинул выше, потому что их нет по-умолчанию в статье, а я их вставляю сам по шаблону. 

Теги выше summary потому что их меньше.

**Comment by nlopin** [comment]
я не очень понимаю, как мы будем следить за соблюдением порядка. Насколько это нужно? Из встречи в пятницу я понял, что для вас это значимая штука. Можете рассказать подробнее, преимущества такого подхода за которые мы готовы платить поддержкой?
