### ISSUE TITLE
Element: scroll/scrollBy

### ISSUE THREAD

**Issue by skorobaeus** [doka-guide/content#1071]
Статья есть [в ноушн](https://www.notion.so/praktikum/Element-scroll-scrollBy-c09391d8116741efb138097675363811), но её нет в репо.

**Comment by nlopin** [comment]
Спасибо, её надо пересмотреть. Оставил себе

**Comment by nlopin** [comment]
[scrollBy.md](https://github.com/doka-guide/content/files/7578775/scrollBy.md)
Выгрузил статью, чтобы её мог кто угодно перенести

**Comment by StarHamster** [comment]
Можно взять задачку? 😅
