### ISSUE TITLE
Картинка для статьи про единицы измерения в CSS

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#1074]
В этой статье буквально одна картиночка. Надо глянуть ок она или не ок.

**Comment by ValyaBro** [comment]
@solarrust дай, пожалуйста, какую-то ссылку на превью статьи, чтобы я могла посмотреть картинку, о которой ты говоришь

**Comment by solarrust** [comment]
@ValyaBro держи =)

https://new.y-doka.site/css/numeric-types/

**Comment by ValyaBro** [comment]
@solarrust спасибо!! <3 Давай сейчас оставим такие картинки, они хорошие. Потом сделаем им редизайн.

**Comment by furtivite** [comment]
@solarrust, я тут убрал заказ для Вали, надо посмотреть актуальность. Возможно, сможет сделать Кира? Или ещё кто?

**Comment by solarrust** [comment]
> Надо глянуть ок она или не ок.

> Давай сейчас оставим такие картинки, они хорошие.

Нет уже задачи. Можно закрывать
