### ISSUE TITLE
Сделать валидатор для HTML

### ISSUE THREAD

**Issue by igsekor** [doka-guide/content#1077]
Есть две стратегии:
1. Собрать полный сайт и провести валидацию
2. Собрать только то, что в PR и провести валидацию (попробую сотворить)

Реализация будет зависеть от решения [ишью из платформы](https://github.com/doka-guide/platform/issues/217).

@pepelsbey @nlopin @furtivite что скажите?

**Comment by furtivite** [comment]
@igsekor, кажется, что надо проверять дважды, вначале на уровне PR, а потом уже на уровне всей сборки. Помнишь, проблемы со словарём, когда в main попадали ошибки как-то?

**Comment by igsekor** [comment]
> @igsekor, кажется, что надо проверять дважды, вначале на уровне PR, а потом уже на уровне всей сборки. Помнишь, проблемы со словарём, когда в main попадали ошибки как-то?

Мы пользовались не тем экшеном. Ошибки появлялись из-за того, что ничего не проверялось. Теперь всё работает правильно. Надо будет решить насчёт тестирования на платформе. Попробуем несколько вариантов и выберем наиболее верный.
