### ISSUE TITLE
В main просочились ошибки

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#1113]
@tachisis поможешь добавить их в словарь исключений (или спряшешь)?
@igsekor посмотришь, как так вышло?

```
npx yaspeller --only-errors **/*.{md,html}
npx: installed 61 in 3.518s
Spelling check:
✗ /Users/pepelsbey/Documents/Дока/content/css/media/index.md 96 ms
-----
Typos: 1
1. медиатипа (64:156, suggest: медиа типа)
-----

✗ /Users/pepelsbey/Documents/Дока/content/css/not/index.md 101 ms
-----
Typos: 1
1. Суперполезный (15:1, suggest: Супер полезный)
-----

✗ /Users/pepelsbey/Documents/Дока/content/css/overflow/index.md 45 ms
-----
Typos: 1
1. скроллить (58:42, suggest: скролить)
-----

✗ /Users/pepelsbey/Documents/Дока/content/css/sticky/index.md 103 ms
-----
Typos: 1
1. спозиционирован (37:40, suggest: позиционирован)
-----

✗ /Users/pepelsbey/Documents/Дока/content/js/design-patterns-behaviorial/index.md 102 ms
-----
Typos: 1
1. Мидлвар (289:1)
-----

✗ /Users/pepelsbey/Documents/Дока/content/js/infinite-scroll/index.md 217 ms
-----
Typos: 1
1. рефакторинг (44:143)
-----

✗ /Users/pepelsbey/Documents/Дока/content/js/modules/practice/bespoyasov.md 50 ms
-----
Typos: 1
1. рефакторинг (3:84)
-----

✗ /Users/pepelsbey/Documents/Дока/content/js/tdd/index.md 147 ms
-----
Typos: 1
1. рефакторинг (20:79, count: 3)
-----

✗ /Users/pepelsbey/Documents/Дока/content/js/technical-debt/index.md 167 ms
-----
Typos: 1
1. рефакторинг (8:5, count: 7)
-----

✗ /Users/pepelsbey/Documents/Дока/content/js/web-security/index.md 194 ms
-----
Typos: 1
1. едленно (301:128, suggest: медленно)
-----
```

**Comment by igsekor** [comment]
@pepelsbey проблема в том, что словарь не правильно работает для некоторых терминов. После приведения словаря к соответствию правилам, некоторые исключения были упущены. Например, чтобы проверить `рефакторинг`, исключение `рефакторинг(е|а)` не сработает. Нужно использовать правило `рефакторинг(е|а|)`.

**Comment by pepelsbey** [comment]
@igsekor у нас с первой версии словаря были пустые пайпы для версии без окончания. Даже [документация](https://github.com/doka-guide/content/blob/main/docs/speller.md) об этом есть. Я удивлён, что у нас тесты зелёные, хотя ошибки есть.

**Comment by igsekor** [comment]
@pepelsbey в текущей версии это не так. А перед правками было так: `рефактори(нг|м|ть|нге)`, поэтому и тесты проходили. Надо посмотреть как чекаут проходит. Кажется в нём проблемы. Надо тестить, заведу PR.

**Comment by pepelsbey** [comment]
@igsekor ну, я сам писал такие окончания, так что в словаре они есть :) Другое дело, что не все авторы и лиды это знают — повод об этом рассказать.

**Comment by igsekor** [comment]
> @igsekor ну, я сам писал такие окончания, так что в словаре они есть :) Другое дело, что не все авторы и лиды это знают — повод об этом рассказать.

Вот [коммит](https://github.com/doka-guide/content/commit/bdc6eb83e6ef1d42468787fa94b9381ee9471ac9#diff-eb99f346ccb007a5876553c3a0a06a0cdb69b69746ded3c98d2fb9a9d19382df), я ничего не придумываю.

Рассказать точно надо! 🙃

**Comment by tachisis** [comment]
@pepelsbey @igsekor мне нужно в документации для авторов поменять команду, которая запускает проверку, на `npx yaspeller --only-errors --file-extensions ".md,.htm" *`?

**Comment by igsekor** [comment]
> @pepelsbey @igsekor мне нужно в документации для авторов поменять команду, которая запускает проверку, на `npx yaspeller --only-errors --file-extensions ".md,.htm" *`?

Ну кажется, такая штука должна точно запуститься везде.

**Comment by pepelsbey** [comment]
Я бы только расширение HTML-файлов указал целиком:

```
npx yaspeller --only-errors --file-extensions ".md,.html" *
```
