### ISSUE TITLE
Не отрабатывает action по созданию поля `updatedAt`

### ISSUE THREAD

**Issue by monochromer** [doka-guide/content#1122]
В github actions почему-то не отрабатывает команда по получению файлов последнего коммита:

```javascript
// получение id последнего коммита
const lastCommitId = 'git log --diff-filter=AMCR --format="%H" -n 1'

// получение изменённых и добавленных файлов последнего коммита
const gitCommand = `git diff-tree --no-commit-id --name-only -r $(echo $(${lastCommitId}))`

const { stdout } = await promisify(exec)(gitCommand)
```

В stdout пустота, хотя "локально все работает".

Нашел решение с помощью стороннего action jitterbit/get-changed-files, но хотелось бы понять, почему не срабатывает текущее решение.

**Comment by pepelsbey** [comment]
@igsekor ты кажется собаку на этом съел :)

**Comment by igsekor** [comment]
@monochromer в этом экшена тоже не правильно работает. Он не отрабатывает для коммитов, дата которых позади. Есть его форк, который работает корректно ([коммит для исправления](https://github.com/Ana06/get-changed-files/commit/f51efe59fcc624cc2a79d1bf87344432da0ad6ca)). Воспользоваться им было бы правильно. Он у нас к тому же уже используется.

Не работает кажется потому, что настроен Node.js в экшена от GitHub особым образом. Есть [issue похожий](https://github.com/actions/setup-node/issues/224#issuecomment-765247398) даже. Можно воспользоваться git и в скрипте, но для этого нужно проникнуться [скриптом](https://github.com/Ana06/get-changed-files/blob/main/src/main.ts) для указанного выше экшена. Иначе работать не будет, они не починили ещё...

**Comment by monochromer** [comment]
> Он не отрабатывает для коммитов, дата которых позади.

нужен только тот коммит, для которого запускается action, то есть самый последний

**Comment by igsekor** [comment]
> > Он не отрабатывает для коммитов, дата которых позади.
> 
> нужен только тот коммит, для которого запускается action, то есть самый последний

Это не так просто, но это есть.
