### ISSUE TITLE
Ссылка на основной файл раздела

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#1180]
У нас есть основной файл раздела. Например: [/tools/index.md](https://github.com/doka-guide/content/blob/main/tools/index.md) — там происходит организация контента. 

Сейчас этот файл попадает в коллекции и отображается на странице [doka.guide/all](https://doka.guide/all) в виде ссылки без текста, потому что у него нет поля `title`, к тому же ссылка битая [doka.guide/tools/tools](https://doka.guide/tools/tools/)

<img width="1396" alt="Снимок экрана 2021-07-21 в 14 01 50" src="https://user-images.githubusercontent.com/50330458/126479223-43100fc1-ff27-4528-8112-d96e07c4990f.png">

Необходимо:

- [x] Убрать страницу из коллекций
- [x] Сделать страницы c подборками для разделов
- [ ] Сделать ссылку на страницу с такими подборками в заголовках на [doka.guide/all](https://doka.guide/all)

**Comment by pepelsbey** [comment]
Упс, извините, зря связал

**Comment by monochromer** [comment]
Почему это issue находится в этом репозитории?

**Comment by furtivite** [comment]
> Почему это issue находится в этом репозитории?

Потому что надо было страницу убрать из коллекций и, видимо, я перепутал. Давай создадим новый issue и сделаем ссылку сюда?

**Comment by monochromer** [comment]
Мне кажется, создавать уже не нужно, так как все задачи решены, кроме последней, но которая уже находится в PR.

**Comment by monochromer** [comment]
Как полагаю, можно закрыть
