### ISSUE TITLE
Разбить статьи с несколькими событиями на единичные статьи

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#1321]
Нужно соблюсти принцип — одна дока на одно событие

Отревьюить статьи:

- [x] keydown/keyup
- [x] scroll/wheel
- [x] scroll/scrollTo
- [x] scroll/scrollIntoView
- [x] load и DOMContentLoaded

**Comment by nlopin** [comment]
Привет! конечно бери

**Comment by Inventoris** [comment]
Привет! Готов сделать :)

**Comment by nlopin** [comment]
Забирай

**Comment by Inventoris** [comment]
😎

**Comment by nlopin** [comment]
@Inventoris офигенно! Большое спасибо 👍
