### ISSUE TITLE
Проверить, что в статье «логические операторы» есть ссылка на объяснение value type и reference type

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#1324]

**Comment by Abusess** [comment]
В статье **«логические операторы»** нету даже упоминания о **value type** и **reference type** и соответственно ссылок тоже, увы

**Comment by nlopin** [comment]
@RoNUII поможешь добавить aside?

**Comment by RoNUII** [comment]
@nlopin не совсем понимаю о каком "aside" идет речь?

**Comment by nlopin** [comment]
у нас есть врезки для статей, они делаются тегом `aside` ([пример в коде](https://github.com/doka-guide/content/blob/f7937a6699c3499f142ee82f3d149fdf0d76b19d/css/animation-duration/index.md)). Предлагаю напистаь его

**Comment by RoNUII** [comment]
@nlopin `aside` лишь тег добавить в разметку или еще сослаться на **value type** и **reference type** (эти понятия значительно запутали меня, но это оказывается просто **примитивные типы** и **не примитивные/ссылочные типы**(?), а меня, будучи новичка в js, разные наименования насторожили). В теме [Преобразование типов](https://doka.guide/js/typecasting/) нашел объяснение **[примитивных](https://doka.guide/js/typecasting/#primitivnye-tipy)** и упоминание  **[не примитивных/ссылочных типов](https://doka.guide/js/typecasting/#obekty)**, если ссылаться на эти понятия в врезке, то ссылаться на вышеупомянутые источники или же внешние, ибо в теме **[примитивные типы](https://doka.guide/js/typecasting/#primitivnye-tipy)** имеется ссылка на MDN

p.s. _что-то я передумал изучать js с таким раскладом в плане типизации..._

**Comment by nlopin** [comment]
Это достаточно стандартный расклад к почти любом языке программирования, когда что-то хранится по значению, а что-то по ссылке. Обычно это связано с тем, что мы не знаем, сколько памяти нужно выделить под динамические структуры данных (такие как объекты), а под числа знаем, ведь они фиксированной длины (32 или 64 бита).

Вот примерно прикинул, куда вставить `<aside>` и текст:
![Uploading image.png…]()
