### ISSUE TITLE
Событие `submit`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#1334]

**Comment by Inventoris** [comment]
Привет! Готов сделать доку.

**Comment by nlopin** [comment]
Привет! Жду!

Пожалуйста, используй ту же структуру, что и в [шаблоне доки](https://github.com/doka-guide/content/blob/main/docs/examples/doka.md). 

Если возникнут вопросы с оформлением, то тебе может пригодится [руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
