### ISSUE TITLE
Проверка документации

### ISSUE THREAD

**Issue by tachisis** [doka-guide/content#1346]
Перед запуском нужно перепроверить документацию: все ли адекватно, все ли актуально.

- Общий ридми: https://github.com/doka-guide/content/blob/main/README.md
- Остальные доки: https://github.com/doka-guide/content/tree/main/docs

Предлагаю при необходимости правок заводить отдельные пиары, а если вопросов нет — поставить тут эмодзи или комментарий, что вы посмотрели, и на ваш вкус все ок :)

**Comment by tachisis** [comment]
@solarrust @igsekor @pepelsbey kindly reminder :)

**Comment by solarrust** [comment]
Закинула несколько правок:

* #1546 
* #1547
* #1549
