### ISSUE TITLE
Поменять шрифт в шаблонах демок

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#1349]
Когда появится новый шрифт, надо не забыть заменить Roboto в документации

**Comment by StarHamster** [comment]
@furtivite, привет, кажется, эта ишью уже неактуальна 👀

**Comment by furtivite** [comment]
@skorobaeus мы решили в демках же использовать стандартные шрифты? Закрываем?

**Comment by skorobaeus** [comment]
> @skorobaeus мы решили в демках же использовать стандартные шрифты? Закрываем?

Да, шрифт решили не менять :)
