### ISSUE TITLE
Обзорная статья `Map`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#1384]
Рассказать про работу `Map` в формате, аналогичном [обзорной статье множества `Set`](https://doka.guide/js/set/).

**Comment by NedelevPhilip** [comment]
Я тоже не увидел этого типа данных, про него забыли или не внесли сознательно?

**Comment by nlopin** [comment]
Привет! До него пока не дошли руки. Если у тебя есть интерес написать этот, то мы с удовольствием поможем. Думаю, что должен получиться набор статей, как в [разделе Set](https://doka.guide/js/#mnozhestvo-set)

**Comment by vitalybaev** [comment]
@nlopin я бы хотел заняться этой статьёй
