### ISSUE TITLE
Удалить репозиторий surge-preview

### ISSUE THREAD

**Issue by igsekor** [doka-guide/content#1391]
Необходимо удалить репозиторий [surge-preview](https://github.com/doka-guide/surge-preview) из организации за ненадобностью, когда следующие PR будут закрыты:

1. Правит инструкцию для создания новой статьи скриптом
2. Добавляет инструкцию для папки people
3. Обновляет демо и рисунки в статье Линейный градиент
4. setTimeout и clearTimeout
5. Редактирует статью про box-shadow

**Comment by nlopin** [comment]
Убрал, чтобы слияние пул реквестов не закрывало таск. 

Ждём:

- [ ] #1284 
- [ ] #1274
