### ISSUE TITLE
Баг в рендере кода на странице статьи

### ISSUE THREAD

**Issue by bespoyasov** [doka-guide/content#1459]
На странице [статьи о стиле кода](https://doka.guide/js/code-style/) есть блоки с намеренно неправильным форматированием. 

В некоторых блоках на этой странице рендер ломается:

![image](https://user-images.githubusercontent.com/9102374/132057148-29b52180-6c8a-4afe-aeee-6bad0efb0baa.png)

![image](https://user-images.githubusercontent.com/9102374/132057157-82a84c9c-f9c0-4e33-ae30-ed29d458213f.png)

**Comment by pepelsbey** [comment]
@monochromer у меня в принципе перестали рендериться блоки кода в этой статье:

![Screen Shot 2021-09-07 at 00 13 13](https://user-images.githubusercontent.com/105274/132260851-9fc8d797-9646-4631-bd2d-0c5c0bdf35b7.png)

**Comment by monochromer** [comment]
Сейчас должно рендериться корректно

**Comment by bespoyasov** [comment]
Подтверждаю, всё ок.

**Comment by pepelsbey** [comment]
Спасибо!
