### ISSUE TITLE
`for...of`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#1464]
Ссылки для старта:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of
- https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-for-in-and-for-of-statements

**Comment by vitya-ne** [comment]
Привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять эту доку ?

А бери!
