### ISSUE TITLE
Обновить схемы в новом дизайне

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#1574]
@ValyaBro с командой подготовила новые схемы, их необходимо залить

- [x] HTML #1575
    - [x] `<aside>` #1613 
- [x] CSS #1576
- [x] JS #1577
- [x] TOOLS #1614
    - [x] Статическая типизация #1615

**Comment by ValyaBro** [comment]
ура редизайну схем

**Comment by ValyaBro** [comment]
@furtivite я не знаю как тут посмотреть каждую статью и как выглядят в них схемы и честно говоря думаю, что тут мой аппрув не обязателен. С нашей стороны все схемы готовы и выданы в отличном качестве. Думаю вы тут можете сами чекнуть не поломалось ли что-то при загрузке.

**Comment by furtivite** [comment]
@ValyaBro, сорри, я тебя отметил только для того, чтобы обозначить, что схемы взял не с потолка, а от тебя и команды. Так что тут всё заапрувлено в плане дизайна.

**Comment by ValyaBro** [comment]
супер ))
