### ISSUE TITLE
Завести странички для всех авторов

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#1624]
Для всех авторов, которые участвовали в проекте необходимо завести страничку в папке `/people`, если такой ещё нет.

**Comment by pepelsbey** [comment]
Добавил пустой список таких людей, чтобы проще было трекать: их бы найти и сделать :)

**Comment by furtivite** [comment]
> Добавил пустой список таких людей, чтобы проще было трекать: их бы найти и сделать :)

А я уже нашёл и сделал)
