### ISSUE TITLE
Что-то пошло не так с превью

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#1769]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/105274/135279959-d6763445-1a95-4543-acfd-b2ba37220074.png">

[Вот здесь](https://github.com/doka-guide/content/pull/1768#issuecomment-930183370)

**Comment by pepelsbey** [comment]
@igsekor а есть причина или ссылка? )

**Comment by igsekor** [comment]
> @igsekor а есть причина или ссылка? )

Вот [фикс](https://github.com/doka-guide/content/commit/a55f0f73f727767a306ff0a3a3273b0430fe5858). PR делать вроде бы нет смысла. Проверить работу новой редакции этого экшена можно только в ветке `main`.
