### ISSUE TITLE
В iframe с атрибутом sandbox не работает JavaScript

### ISSUE THREAD

**Issue by monochromer** [doka-guide/content#1779]
Например, https://doka.guide/js/set/

**Comment by pepelsbey** [comment]
Решение — добавить [значения](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) в атрибут `sandbox`. Как минимум `sandbox="allow-scripts"`.

Но раз мы добавляем значения, то кажется лучше будет убрать это из контента и сделать трансформацию на уровне Eleventy, чтобы по маске «демка» добавлять атрибут.

**Comment by furtivite** [comment]
> Но раз мы добавляем значения, то кажется лучше будет убрать это из контента и сделать трансформацию на уровне Eleventy, чтобы по маске «демка» добавлять атрибут.

Да, кажется, это отличное решение.

**Comment by edbond88** [comment]
@furtivite тут можно тоже закрыть?

**Comment by furtivite** [comment]
@monochromer, тут, кажется, пофиксили. Не помнишь точнее?
