### ISSUE TITLE
Ошибка в `.toString()`

### ISSUE THREAD

**Issue by ghost** [doka-guide/content#1837]
Некорректное описание работы функции Object.prototype.toString (https://doka.guide/js/object-tostring/)

> Если метод не переопределён, то он возвращает строку формата [object тип], где тип — это строка, которая уточняет тип объекта. В подавляющем большинстве вы будете видеть вывод [object Object].

Во-первых метод не подставляет никакого типа. Он подставляет **тэг**, который либо заранее определен в объекте или в цепочке его прототипов, либо динамически подставляется, в зависимости от того, является ли объект экземпляром одного из встроенных классов, из строго определенного списка.

Во-вторых совершенно необязательно переопределять сам метод. Согласно алгоритму, строго определенному в спецификации, но проигнорированному в данной статье, функция смотрит на определенное в объекте (если переданное ей значение не принадлежит типу null или undefined) свойство с ключом [Symbol.toStringTag],  и если оно определено и является **строкой**, возвращает именно его значение в [object whatever], в противном случае подставляет **тэг**, в зависимости от того, экземпляром какого базового класса, из строго определенного списка, является объект. 

```javascript
({ [Symbol.toStringTag] : 'ololo' }).toString() // [object ololo]
({ [Symbol.toStringTag] : 123 }).toString() // [object Object]

Object.prototype.toString.call(
    Object.assign( new Date(), { [Symbol.toStringTag] : 'ololo' })
) // [object ololo]
Object.prototype.toString.call(
    Object.assign( new Date(), { [Symbol.toStringTag] : 123 })
) // [object Date]

Object.prototype.toString.call(123) // [object Number]
Number.prototype[Symbol.toStringTag] = 'ololo'
Object.prototype.toString.call(123) // [object ololo]
```

В общем и целом, статья несет неверную и даже вредную информацию.
Во-первых совершенно не обязательно переопределять метод - достаточно в объекте определить тэг. 
Во-вторых, никакого типа функция не подставляет. 
В-третьих эта функция вообще перекрывается методом [Symbol.toPrimitive], у которой есть целых три состояния, в зависимости от контекста, которого она вызвана.

Пулл-реквест мне оформлять предельно лень, там по-хорошему следует переписывать целиком и полностью всё. 

Ваши начинания хороши - пытаться объяснить сложные вещи простым языком это замечательно. 
Вот только если вместо простых объяснений подавать некорректную информацию, это принесет больше вреда, чем пользы. 

Ну и в целом не ясно, чем исчерпывающая документация на MDN не проста (или сложна), или неактуальна? 

На всякий случай, оставляю вам описание алгоритма из спецификации

```
When the toString method is called, the following steps are taken:

If the this value is undefined, return "[object Undefined]".
If the this value is null, return "[object Null]".
Let O be ! ToObject(this value).
Let isArray be ? IsArray(O).
If isArray is true, let builtinTag be "Array".
Else if O has a [[ParameterMap]] internal slot, let builtinTag be "Arguments".
Else if O has a [[Call]] internal method, let builtinTag be "Function".
Else if O has an [[ErrorData]] internal slot, let builtinTag be "Error".
Else if O has a [[BooleanData]] internal slot, let builtinTag be "Boolean".
Else if O has a [[NumberData]] internal slot, let builtinTag be "Number".
Else if O has a [[StringData]] internal slot, let builtinTag be "String".
Else if O has a [[DateValue]] internal slot, let builtinTag be "Date".
Else if O has a [[RegExpMatcher]] internal slot, let builtinTag be "RegExp".
Else, let builtinTag be "Object".
Let tag be ? Get(O, @@toStringTag).
If Type(tag) is not String, set tag to builtinTag.
Return the string-concatenation of "[object ", tag, and "]".
```

Успехов.

**Comment by vitya-ne** [comment]
@TatianaFokina, @furtivite , хочу исправить неточности описания `toString()`.
Нет возражений ?

**Comment by TatianaFokina** [comment]
> @TatianaFokina, @furtivite , хочу исправить неточности описания `toString()`. Нет возражений ?

Нет, исправляй конечно.
