### ISSUE TITLE
Ошибка в `for...in`

### ISSUE THREAD

**Issue by ghost** [doka-guide/content#1838]
https://doka.guide/js/for-in/

>В стандарте языка нет описания того, как свойства должны перечисляться, потому порядок будет зависеть от реализации в конкретном движке браузера. Но есть базовые правила, которое можно встретить во всех браузерах

Это неправда. 

Согласно актуальной спецификации, порядок перечисления ключей в объекте строго определено. 
Сначала перечисляются все собственные ключи приводимые к типу uint32 (ключи, являющиеся целыми беззнаковыми числами от 0 до 0xFFFFFFFF) в порядке возрастания, потом остальные **строковые** ключи, **в хронологическом порядке их добавления** в объект,  затем ключи-символы, так же в хронологическом порядке их добавления, затем все то же самое по цепочке прототипов, если это необходимо контекстом перебора. 

По факту, и без спецификации подобное поведение было реализовано во всех актуальных браузерах и мейнстрим js-движках, просто исходя из того, в каких именно структурах под капотом хранятся объекты. JS-движки используют скрытых классы, которые опираются именно на порядок определения свойств. Тем самым объекты `{a: 1, b: 2}` и `{b:2, a: 1} `под капотом имеют две разных формы. А так же используют отдельное хранение слотов с числовыми индексами, чтобы ускорять работу массивоподобных объектов. И именно на данные нюансы в реализациях, уже более 10 лет как, и опиралось большинство движков. И именно исходя из подобных реализаций в движках, в спецификацию внесли изменения, которые строго гарантируют порядок, в котором будут перечисляться свойства. 

Алгоритм перечисления описан в спецификации в реализации функции **OrdinaryOwnPropertyKeys**, которая применяется во множестве ситуаций обхода объекта, собирания их ключей, их сериализации (например в JSON-представление), и в том числе в цикле for..in

При всем при этом, данный порядок обхода строго определили еще с принятием ES6, а лишь спустя всего пару версии спецификации позднее, его еще более строго уточнили, убрав из разных частей спецификации всяческие неоднозначные формулировки, дающие основания полагать, что порядок перечисления может как-либо оставаться на усмотрение имплементаций. 

Поэтому очень странно, что позиционируя себя как наиболее актуальный справочник, и наполняя его контентом в 2021 году,  описываете совершенно неактуальную, и даже чрезвычайно устаревшую информацию. 

>Числовые свойства будут перечисляться в отсортированном порядке по возрастанию:

Из всего сказанного выше, опять же нет. Числовые ключи больше чем максимальный размер массива, будут сортироваться в хронологическом порядке и рассматриваться как и все остальные строковые ключи.

>Несмотря на договорённости о порядке вывода числовых ключей, не нужно использовать for...in для перебора массива. В будущем правила могут измениться. 

Правила давно изменились, и они уже много лет как строго определены и поддерживаются всеми актуальными имплементациями. Никаких договоренностей нет - есть спецификация.

**Comment by vitya-ne** [comment]
Привет, я могу взять этот тикет ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять этот тикет ?

Совершенно точно можешь.
