### ISSUE TITLE
HTMLCollection и NodeList

### ISSUE THREAD

**Issue by dynamicult** [doka-guide/content#1841]
https://doka.guide/js/htmlcollection-and-nodelist/

>HTMLCollection возвращают методы getElementsByTagName и getElementsByClassName.
>NodeList возвращает метод querySelectorAll.

Есть куда больше методов, возвращающих нод-листы и html-коллекции. 

>NodeList работает так же, как и HTMLCollection. Разница только в том, что NodeList не живая коллекция — она не обновляется при появлении на странице новых элементов.

NodeList тоже может быть "живой коллекцией". Яркий пример такого живого нод-листа - это список элементов возвращаемый геттером Node.childNodes - данная коллекция будет динамически обновляться при изменении узлов-потомков, без необходимости ее повторно запрашивать через тот же геттер. 

**И это, блин, важно. Огромная масса разработчиков начитавшихся подобных материалов, пишут код будучи отчаянно уверены, что раз NodeList, то он никогда не изменится. Это не так. И учить такому нельзя.** 

Действительная разница между этими коллекциями в членах, которых они хранят. **NodeList**, как ясно из названия **хранит узлы** (узлами могут быть не только элементы, но и, например комментарии, текстовые ноды и так далее), а **HTMLCollection** - **только** подтип этих узлов, являющихся **html-элементами**. 

NodeList может быть **как динамической (живой), так и статической** коллекцией, а HTMLCollection **только** динамической. 

Индексация элементов в NodeList производится **только** по числовому индексу, в то время, как в HTMLCollection _дополнительно_ по id элемента, при этом возможны коллизии.  

Ну и разумеется имеется разница в предоставляемом интерфейсе коллекций. У NodeList более расширенный интерфейс по работе с коллекцией.

**Comment by Northrain-cmd** [comment]
Взял в работу
