### ISSUE TITLE
Не работает ссылка в гит документации на файле "Предпросмотр статьи"

### ISSUE THREAD

**Issue by MegaVasiliy007** [doka-guide/content#1863]
В документации не работает ссылка на видеоинструкцию по запуску. Ссылка ведет на 404 ошибку.

Где ошибка:
https://github.com/doka-guide/content/blob/main/docs/preview.md?plain=1#L5

![image](https://user-images.githubusercontent.com/32243070/137110419-f57bf6f9-4424-43c7-b052-5d5ee49da107.png)

**Comment by pepelsbey** [comment]
В любом случае, думаю эта инструкция устарела и её лучше выпилить. Мы её делали скорее для внутренних нужд.

**Comment by tachisis** [comment]
@furtivite точно не мой
