### ISSUE TITLE
Русифицировать примеры кода

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#1924]
Сейчас в примерах кода есть большая несогласованность -- они то на русском, то на английском. Особенно это актуально для JS-раздела, как пример https://doka.guide/js/alert/

![image](https://user-images.githubusercontent.com/4408379/137390031-9e1e582f-b965-452d-8c5f-777c976e5f93.png)

Это большая задача, поэтому, наверное, сначала нужно явно зафиксировать это правило в руководстве по стилю.

**Comment by Vladyan-dev** [comment]
Мне кажется, большинству будет удобнее читать примеры на русском 😅

**Comment by nlopin** [comment]
@tachisis все новые примеры мы пишем на русском, но есть примеры кода, которые писали до этой договорённости. Зафиксируем это в руководстве по стилю?
