### ISSUE TITLE
Выражения и инструкции: блок-схемы не видны в тёмном режиме

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#1925]
При включённом тёмном режиме не видны блок-схемы, пока только заметил это на https://doka.guide/js/expressions-vs-statements/ 

![image](https://user-images.githubusercontent.com/4408379/137392098-34c1e39a-1772-4090-91f7-cc99d97c1a19.png)

**Comment by mvrlin** [comment]
Как вариант можно использовать CSS свойство при включенной темной теме `filter: invert(1)`

**Comment by pepelsbey** [comment]
Это временные схемы, пока до них не добрались, чтобы сделать красиво. Самое быстрое решение — экспортировать картинки со сплошным белым фоном.
