### ISSUE TITLE
Gulp: краткий обзор

### ISSUE THREAD

**Issue by igsekor** [doka-guide/content#1936]
Сделать статью подобную [Webpack: краткий обзор](https://doka.guide/tools/webpack/).

Рассказать, чем отличаются подходы к сборке (artifact-based vs task-based)

**Comment by webdb81** [comment]
Добрый вечер.
Могу взяться написать статью.

**Comment by nlopin** [comment]
Привет! Конечно, присылай пул реквест! 

Если ты еще не писал ничего для нас, то тебе пригодится [руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md) и [файл со структурой статьи](https://github.com/doka-guide/content/blob/main/docs/examples/article.md).
