### ISSUE TITLE
Унифицировать обращения

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#1969]
Периодически во всех разделах встречаются дружеские обращения, хотя в руководстве по стилю зафиксировано уважительное обращение.

![image](https://user-images.githubusercontent.com/4408379/137590754-431e0447-6a53-4c41-a950-0a40cd3dffa6.png)

https://doka.guide/css/transition/

![image](https://user-images.githubusercontent.com/4408379/137590771-3bc2858b-7057-4769-8234-dd37dfb51f1f.png)

https://doka.guide/html/title/

![image](https://user-images.githubusercontent.com/4408379/137590898-eeabc5db-bb06-4da9-a10e-f02979a3d48e.png)

https://doka.guide/js/events/

**Comment by lex111** [comment]
Уточню, это правило не должно распространяться на мнения разработчиков (секция "В работе")? Тут они вольны сами определять обращение, даже если состоят в редакции, или нет?

![image](https://user-images.githubusercontent.com/4408379/137601422-dbe3a7b9-4554-442f-885a-c85d53e13b28.png)

**Comment by sashasushko** [comment]
@furtivite круто! Вот этой инфы не хватает, возможно это действительно решится правкой заголовка и визуальной привязкой имени автора к сказанному.
