### ISSUE TITLE
Тема про !important не развернута до конца.

### ISSUE THREAD

**Issue by ivanstrilets** [doka-guide/content#1994]
Статья может ввести в заблуждение из-за отсутствия информации о том, что !important перебивает стили из атрибута style

**Comment by pepelsbey** [comment]
Это хороший повод для пул-реквеста :) Там сразу можно объяснить, как и что именно стоит объяснить лучше.

Дерзайте :)

**Comment by ivanstrilets** [comment]
@pepelsbey обращаюсь к инструкции
![image](https://user-images.githubusercontent.com/45265680/137804316-f0e6939f-69b0-4966-8354-1b4f44124c8a.png)
получаю негативный результат
![image](https://user-images.githubusercontent.com/45265680/137804231-cd0f3588-2d27-4d80-8e93-9f55081c7865.png)

**Comment by pepelsbey** [comment]
@ivanstrilets по скриншоту сложно сказать. Вероятнее всего, вы пытаетесь запушить не в свой форк, а в наш репозиторий, на что у вас нет прав. Запушьте себе и у вас на Гитхабе появится зелёная кнопка с предложением сделать пул-реквест.
