### ISSUE TITLE
Раскрыть пользователя "Дока Дог"

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#1996]
Довольно странно и вызывает недоумение, когда в авторе статьи указан некий "Дока Дог", который позиционируется вроде как бот, особенно когда встречаешь его мнение в разделе "В работе". Или это искусственный интеллект и так должно быть?

![image](https://user-images.githubusercontent.com/4408379/137619098-66c37127-8cec-49eb-b306-9ca4a67e8ef0.png)

Кажется, это противоречит основной концепции, когда авторы статей должны быть известны, а тут непонятный аноним, либо если под ним имеется в виду в целом вся редакция, то так и указать, или вообще скрыть. В общем, сделать это более понятным способом, чтобы не возникало вопросов, кто или что это.

**Comment by pepelsbey** [comment]
Это анонимные авторы, которые работали над статьями в самом начале, мы пока решили так сделать. Дальше будем думать, что делать.
