### ISSUE TITLE
Некорректная иллюстрация в статье "Гайд по grid"

### ISSUE THREAD

**Issue by vasilii-kovalev** [doka-guide/content#1998]
Здравствуйте.
Обнаружил некорректную иллюстрацию в статье "Гайд по grid", раздел [grid-auto-flow](https://doka.guide/css/grid-guide/#grid-auto-flow).
![image](https://user-images.githubusercontent.com/10310491/137630758-5dce4b7a-4358-4094-9d49-5df1ee506a5b.png)

**Comment by solarrust** [comment]
Спасибо за внимательность! И правда, немного напутали с картинками. Поправим =)
