### ISSUE TITLE
Вопрос: как должен выглядеть заголовок статьи про метод прототипа?

### ISSUE THREAD

**Issue by Semigradsky** [doka-guide/content#2076]
Сейчас есть разные варианты:
1. `[].forEach`
2. `.includes()`
3. `set.add()` - как 1, но со скобками
4. `Element.focus()` - выглядит как вызов метода у функции-конструктора
5. `Promise. Метод then`

Хотелось бы какого-то единообразия.

**Comment by notiv-nt** [comment]
Я за `Array.forEach` и подобное, т.к. гуглят примерно `js array foreach` и под запрос подходит лучше

**Comment by pepelsbey** [comment]
Обсудили с редакцией, сделаем подход на неделе и сдвинем задачу.

**Comment by nlopin** [comment]
Сделал подход, записал [демо](https://www.loom.com/share/11c859c5236f40d49d26a7c94041908e)

Идея — разделить названия статьи для представления по темам и по алфавиту, чтобы перестать искать компромис между краткостью и полнотой названия. В группировке по темам писать кратко, а по алфавиту — полно

**Comment by solarrust** [comment]
Имхо, в таком случае теряется смысл алфавитной сортировки. Я буду ожидать искать `slice()` на букву S, а не на букву М — «Массивы. Метод slice»

**Comment by tachisis** [comment]
Мне нравятся полные названия, чтобы было видно, к какому разделу относится статья. Но Алена права, в этом случае теряется сама суть сортировки по алфавиту. Когда-то я предлагала раздел указывать после названия статьи (в скобках или просто менее заметным начертанием типа светлого курсива). Кажется, что такое решение одновременно может и помочь в том плане, что раздел можно подставлять автоматически и не заводить новое поле.

**Comment by nlopin** [comment]
Договорились сделать ещё эксперимент — добавить «тему» в конец названия статьи. Например, «Метод `forEach`, _Массивы_» (если включён в несколько подкатегорий, то разделы через запятую)

**Comment by tachisis** [comment]
@nlopin сделали ли мы это в итоге?

**Comment by nlopin** [comment]
Постараюсь на этой неделе показать, чтобы мы приняли решение
