### ISSUE TITLE
Новая дока «Тернарный оператор»

### ISSUE THREAD

**Issue by spokik** [doka-guide/content#2136]
В разделе  js/if-else/#variacii не хватает тернарного оператора.

Не считаю себя достаточно опытным, что бы кого-то учить. Скорее хочется узнать когда его стоит использовать, когда нет и как работает.

Оно вроде как хуже читается, с одной стороны, а где-то if...else слишком громоздкий

**Comment by Ginger-Raccoon** [comment]
Готов взяться :eyes:

**Comment by nlopin** [comment]
@Ginger-Raccoon ждём! Кажется там будет горячий раздел «в работе»

Думаю обойдёмся простой структурой: Кратко → Как пишется → Как понять

**Comment by spokik** [comment]
@nlopin @Ginger-Raccoon мне, как не опытному, важно и где применяется, а где не стоит и в чем отличия от обычного if else, если они есть

**Comment by darinapairel** [comment]
Еще можно добавить описание такой возможности, как isTrue && statement, когда в зависимости от значения левой части выражения будет выполняться второе. Лаконичная конструкция, думаю, начинающим было бы интересно с ней познакомиться.
