### ISSUE TITLE
Валидно ли определение свойства line-height?

### ISSUE THREAD

**Issue by doctorrsm** [doka-guide/content#2221]
Почему везде бездумно, или может быть очень умно, но выше моего уровня понимания, все копируют такое определение свойства line-height?

"line-height задаёт интервал между строчками текста, который называют интерлиньяж."

Это в документации так написано? В любом случае, если судить здраво, то это свойство определяет не интервал между строчками, а высоту инлайн бокса, или строки. А непосредственно интерлиньяж - это скорее побочный эффект. 

Например, на сайте "w3schools" объясняется так "The line-height property specifies the height of a line". Что более логично и более понятно отражает суть этого свойства? 

Cайт "css-tricks" говорит так. "The line-height property defines the amount of space above and below inline elements." Вроде и не придерешься. Но опять же не отражает самой сути. 

Когда я пишу браузеру, что Line-height - 19px, что я говорю браузеру? Что у меня интервал между строками 19px? Или что при расчете боксовой модели высота строки 19px?

**Comment by solarrust** [comment]
@doctorrsm получилось ли ответить на ваш вопрос? Можно закрыть задачку?

**Comment by doctorrsm** [comment]
> @doctorrsm получилось ли ответить на ваш вопрос? Можно закрыть задачку?

Да, закрывайте. Хотя неплохо бы и вставить про рендеринг небольшую ремарку.  Новичкам будет полезно. Если это не бездумное копирование, а часть тактики, которой придерживается автор, то я спокоен.

**Comment by solarrust** [comment]
Я создала задачу #2282 на основании текущего обсуждения. Возьмёшься дополнить статью? 

Эту задачку закрываю.
