### ISSUE TITLE
Необходимо поставить два пробела в конце строки, но они затираются trim_trailing_whitespace

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2225]
В статье про Markdown необходимо привести пример кода, где в конце строки стоит два пробела для явного переноса, но при сохранении они удаляются из-за того, что в .editorconfig стоит trim_trailing_whitespace = true. Полагаю, что это условие проверяется не только редактором кода, поэтому есть идея воспользоваться спецсимволом &#32;, но это кажется несколько сомнительным решением. Возможно, есть способ, которым можно сделать лучше или причины, по которым так не стоит делать?

**Comment by pepelsbey** [comment]
Предлагаю обсудить это уже в пул-реквесте со статьёй, это очень специфический вопрос :)

Сходу: я бы поставил там символы, обозначающие пробелы, чтобы было видно. Иначе как читателю ещё понять, что там пробелы? :)

```
Примерно так∙∙∙
```
