### ISSUE TITLE
Дока про итератор

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#2228]
- [ ] Рассказать о том, как устроен итератор и зачем он нужен
- [ ] проставить ссылку на эту статью в статье `for...of`

**Comment by kanishev** [comment]
Готов взяться.

**Comment by nlopin** [comment]
Класс, жду PR! 

Если нужна помощь в структуре, то пиши тут и обсудим. Мне видится, что она будет нестандартной. Точно нужны блоки «Кратко» и «Как понять», а всё остальное кастомное.

В качестве примера можно взять [статью о модулях](https://doka.guide/js/modules/) в JS или [про области видимости](https://doka.guide/js/closures/). 

Тебе точно поднадобится [руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)

**Comment by nlopin** [comment]
@kanishev нужна ли помощь?

**Comment by kanishev** [comment]
> @kanishev нужна ли помощь?

Извиняюсь за задержку. Был занят статьей про CSS, только сделали merge. У меня есть представления по структуре, с учетом того, что есть смежные темы (Fix #1464 , #2370) сформулирую основные идеи и дальше уже определимся, что конкретно стоит написать. Буквально на днях отпишусь.

**Comment by kanishev** [comment]
1. Кратко.
  Цикл for…of. Переход к итераторам.
  Поскольку про for…of уже пишут (), акцентировать на нем внимание не буду, однако считаю необходимым его упомянуть именно в начале и сделать плавный переход к самим итераторам. Так, мне кажется, не будет выглядеть слишком топорно.
2. Как это понять? 
Зачем нужен итератор? Что позволяет делать? 
3. Итерируемые объекты
4. Пример объекта-итератора. Синтаксис, особенности
5. Встроенные итераторы 

Изначально была идея показать как посредством итератора делать простой объект итерируемым. Будет ли уместно приводить такой пример в разделе «На практике»?

**Comment by nlopin** [comment]
Да, план хороший. 

Только раздел «Кратко» стоит отделить и там дать выжимку статьи. Сейчас в плане он выглядит как введение, но он не должен быть введением. Должно получиться так, что в разделе «Кратко» в одном-двух абзацах рассказывается что это и зачем, а остальная статья уже разворачивает понятие.

Из материалов в спорных случаях ещё стоит смотреть в [спеку](https://262.ecma-international.org/#sec-iteration)
