### ISSUE TITLE
Статья про OpenAPI, Swagger

### ISSUE THREAD

**Issue by jag-k** [doka-guide/content#2233]
Могу взяться за статью про [OpenAPI](https://openapis.org)

Так же про связку со Swagger и помощь в создании mock-серверов (на базе Postman, [axios mock server](https://www.npmjs.com/package/openapi-axios-mock-adapter))

**Comment by pepelsbey** [comment]
Думаю, можно начать с питча: что это такое, почему важно и насколько распространено.

Чтобы мы смогли оценить, стоит ли писать об этом вводную стратью. Я про все эти вещи слышу первый раз, думаю многие тоже.

**Comment by pepelsbey** [comment]
@nlopin @igsekor @bespoyasov что скажете?

**Comment by jag-k** [comment]
[OpenAPI] – это стандарт для разработки "документации" для доступа к бекэнду, совместимый с [JSON Schema](https://json-schema.org/) (Об этом я тоже хотел бы рассказать: #2232)

Его поддерживают многие бекенд библиотеки, автоматически генерируя на основе роутингов и моделей правильные запросы и ответы. Есть библиотеки, которые пошли ещё дальше и интегрируют в себя поддержку отображения в интерактивной оболочке, такие как [Swagger](https://swagger.io/) ([пример](https://petstore.swagger.io/)) или [ReDoc](https://redoc.ly/) ([пример](https://redocly.github.io/redoc/))

Обычному бекэнд разработчику тоже было бы неплохо знать о самом стандарте и (возможно) самому написать документацию по API. На работе даже был случай, когда не было ещё бекенда, но уже нужно было завязаться на тестовые данные. Тут и пригодились знания [OpenAPI]

Но так же обычный фронтенд разработчик может добавить своё отображение [OpenAPI], поговорить в бекендерами о данном стандарте, ведь гораздо проще узнать к какому роутингу нужно стучаться, что бы получить те или иные данные через приятный автоматически-генерируемый интерфейс, нежели чем каждый раз спрашивать разработчика или вообще разбираться в коде бека

Надеюсь ответил на вопрос о том, что это такое))

[OpenAPI]: https://www.openapis.org/

**Comment by pepelsbey** [comment]
Мы тут пишем про бэкенд в таком виде, чтобы это могло пригодиться фронтендеру. То есть если OpenAPI это чисто бэкендерская история, а фронтендеру всего лишь «хорошо бы это понимать», я бы не стал добавлять статью. Если это действительно нужно, важно и часть ежедневной работы или каких-то процессов — другое дело. Но кажется, что нет.

**Comment by igsekor** [comment]
> @nlopin @igsekor @bespoyasov что скажете?

Ну мне нравится. Главное не уходить слишком в бэкенд и фокусироваться на необходимых знаниях, которые понадобятся, чтобы с бэкендером говорить на одном языке (или хотя бы наречии 🙃)

**Comment by jag-k** [comment]
Если не разбирать OpenAPI полностью, то можно тогда и добавить в статью про JSON Schema (#2232)

**Comment by nlopin** [comment]
Давай пока так и сделаем. Я закрою эту задачу и если поймём, что в JSON Schema это смотрится чужеродно, переоткроем
