### ISSUE TITLE
Объединение статей о var, let и const в одну статью

### ISSUE THREAD

**Issue by ruslauz** [doka-guide/content#2238]
Что скажете на счет идеи об объединением 2х статей ([var/let](https://doka.guide/js/var-let/), [const](https://doka.guide/js/const/) ) в одну. Под названием, например:  "Типы переменных"

**Comment by nlopin** [comment]
Мне кажется хорошей идеей. Нужно или разбивать дальше, или сливать.

По ощущениям, мы выиграем от слияния больше. Разделение на отдельные материалы будет усложнять понимание различий между ними. Хотя если в какой-то момент поймём, что статья получается слишком большой, то распилим на отдельные.

Я бы не стал сильно копаться в `var`, потому

**Comment by pepelsbey** [comment]
Есть другая стратегия: написать общую вводную статью var-let-const, где расписать разницу и практики.

А потом, при желании, можно написать var, let, const — и там уже расписать нюансы, историю, сложности.

**Comment by ruslauz** [comment]
https://github.com/doka-guide/content/pull/2237 попробовал создать вводную статью.
