### ISSUE TITLE
Статья CSS-счётчики

### ISSUE THREAD

**Issue by BlueInGreen68** [doka-guide/content#2242]
Объединение #1411, #1410

**Comment by BlueInGreen68** [comment]
Готов взяться.

**Comment by solarrust** [comment]
Супер! Закрепила задачку за тобой 🙌
Пожалуйста, пиши, если потребуется любая помощь. 
И да, лучше бы сначала написать про свойства отдельно, а потом ссылаться на эти статьи внутри собирательной.

**Comment by BlueInGreen68** [comment]
@solarrust, хорошо. Можно тогда меня ещё закрепить, пожалуйста, за вот этим #1410

**Comment by solarrust** [comment]
Гитхаб злой, не даёт закрепить ту задачку за тобой. Ты мог бы там написать что-нибудь?

**Comment by solarrust** [comment]
@BlueInGreen68 привет! Как дела? Планируешь написать эту статью?

**Comment by BlueInGreen68** [comment]
@solarrust привет! Дела нормально! Затянул я конечно с написанием, но я хочу всё таки написать её, постараюсь за ближайшую неделю +-. Ещё хочу попросить отписать меня, пожалуйста, от вот этой темы #1412. И ещё, не подскажешь, как лучше всего удалять ветки? Вот например, я когда делал исправления по свойствам `counter-set/reset/increment` я их писал в отдельной ветке, когда я изменения отправил эта ветка осталась, но допустим мне нужно внести ещё одно изменения и я не хочу делать новую ветку, а использовать эту же, так у неё название подходящее, мне что сделать нужно?

**Comment by solarrust** [comment]
Привет!
Рада, что дела нормально =)
Отписала тебя от задачи #1412 по твоей просьбе. 
Ветку можно назвать любым другим именем, например, добавить в конце `-2`. 
Если пул-реквест, для которого создавалась ветка, уже слит, то на гитхабе она удалилась автоматически. Чтобы удалить её локально, нужно выполнить команду `git branch -D branch_name`.

**Comment by BlueInGreen68** [comment]
@solarrust Спасибо!
