### ISSUE TITLE
Превью контента для сторонних пул-реквестов

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#2258]
Видимо причина та же, что и у лабелера: превью не создается сейчас для сторонних пул-реквестов (пример - https://github.com/doka-guide/content/runs/4066494371?check_suite_focus=true), на стабильно почту падает соответствующее уведомление:

![image](https://user-images.githubusercontent.com/4408379/139656554-4ed3b03b-41bd-4736-93aa-0424f472a691.png)

Либо нужно починить это, либо вовсе отключить попытку создания превью для пул-реквестов не от редакции, чтобы хотя бы уведомления не приходили авторам пул-реквестов.

**Comment by igsekor** [comment]
Согласен! Работаю над этим :)

**Comment by lex111** [comment]
Забавно, вроде теперь всё работает корректно: лейблы проставляются, превью создаётся, но все обе соответствующие задачи падают (пример - https://github.com/doka-guide/content/pull/2366#issuecomment-964568796) 

![image](https://user-images.githubusercontent.com/4408379/141009114-0d5ef9da-e8a4-48d0-9b4e-a2fa58f183f0.png)

Странно, в общем...

**Comment by igsekor** [comment]
> Забавно, вроде теперь всё работает корректно: лейблы проставляются, превью создаётся, но все обе соответствующие задачи падают (пример - [#2366 (comment)](https://github.com/doka-guide/content/pull/2366#issuecomment-964568796))

Это я не досмотрел. Надо триггер убрать один из двух. Сделаю.

> UPD: интересно, почему лейбл "css" в данном PR автоматически не добавился?

Потому что правила такого нет. Надо добавить. Сделаю тоже.
