### ISSUE TITLE
Проблемы работы оглавления статьи, когда заголовки находятся внутри `details`

### ISSUE THREAD

**Issue by monochromer** [doka-guide/content#2262]
Пример статьи - https://doka.guide/js/modules/.

Когда заголовки находятся внутри `details`, они по умолчанию будут скрыты, из-за чего их начальная позиция и позиция при клике на ссылку в оглавлении вычисляется некорректно.

Теоретически можно проверять, скрыт ли заголовок и если да, то искать заголовок выше. Но хочется как-то надёжнее.

Поэтому вижу несколько вариантов решения на стороне контента:
- Достать контент из `details`
- Убрать заголовки внутри `details`, сделать заголовок внутри `summary`

На стороне движка:
- Игнорировать заголовки, которые находятся внутри `details`, при генерации оглавления

Какие ещё предложения?

**Comment by pepelsbey** [comment]
Я бы расписал в гайде, что внутри `<details>` не используются заголовки. Что это секция сама по себе, а то вижу привычку скрывать большие блоки текста. В итоге их не видно по умолчанию, большие части теряются.

**Comment by nlopin** [comment]
В этой статье заголовки очень хорошо ложаться в этот раздел. Я понимаю, что хочется проще, но если мы достанем их оттуда, то они переусложнят статью.

Предлагаю их просто не включать в оглавление

**Comment by bespoyasov** [comment]
> Предлагаю их просто не включать в оглавление

На правах автора статьи соглашусь с @nlopin. 

Я изначально так и рассчитывал, что заголовков из-под `details` видно не будет в оглавлении, это же `details`. Они там нужны исключительно для того, чтобы простыню, которая открывается при клике на `summary`, было тоже удобно читать.

**Comment by nlopin** [comment]
Поговорил с @tachisis и у неё есть мнение, что заголовки в `details` плохо.

**Comment by bespoyasov** [comment]
Что делать, если внутри `details` много контента, как в этой статье?

**Comment by tachisis** [comment]
Я предлагаю пересмотреть структуру статьи и сделать так, чтобы раздел под details прятать было не нужно -- например, если это дополнительная информация, переместить ее в конец статьи и как-то дать понять, что она дополнительная.

**Comment by pepelsbey** [comment]
Проблему решили на уровне платформы, теперь заголовки в оглавление не входят.

Спасибо всем ❤️
