### ISSUE TITLE
Проанализировать структуру статей и выработать общий подход

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#2266]
- что сейчас есть в разделе «в работе» и что там должно быть
- насколько разошлись структуры разных разделов и как их сделать похожими

**Comment by tachisis** [comment]
Проанализировала статьи в каждом разделе и пришла к выводу, что в большинстве случаев содержимое раздела «На практике» попадает в 4 группы:

**Личное мнение + совет**

https://doka.guide/html/iframe/#v-rabote
https://doka.guide/tools/static-types/#igor-kamyshev

**Подсказки**

https://doka.guide/html/input/#v-rabote
https://doka.guide/html/video/#v-rabote
https://doka.guide/css/flexbox-guide/#v-rabote
https://doka.guide/js/how-the-browser-creates-pages/#sasha-bespoyasov
https://doka.guide/js/string-wrapper/#doka-dog

**Рецепт с демкой/примером кода**

https://doka.guide/css/box-shadow/#v-rabote
https://doka.guide/js/async-in-js/#sasha-bespoyasov
https://doka.guide/html/video/#v-rabote
https://doka.guide/css/flexbox-guide/#v-rabote
https://doka.guide/js/if-else/#nikolay-lopin

**Дополнительная углубленная информация**

https://doka.guide/tools/cli/#prodvinutyy-uroven-ispolzovaniya-cli
https://doka.guide/tools/package-managers/#zavisimosti-dlya-razrabotki
https://doka.guide/tools/file/#na-praktike

Предлагаю оставлять в разделе «На практике» только содержимое групп «Личное мнение» и «Рецепт с демкой/примером кода», а дополнительную углубленную информацию и подсказки переносить в тело статьи, делая автора этих изменений контрибьютором.

Если остановимся на этом, тогда можно будет подзаголовок раздела «На практике», который сейчас представляет собой имя добавившего, поменять на «Имя Автора советует» или что-то вроде того.

**Comment by tachisis** [comment]
Теперь про структуру материала типа «дока». Во всех разделах структура примерно одинаковая, в JS и Инструментах некоторые подразделы отсутствуют.

**HTML**

Кратко
Пример
Как это понять
Как пишется
Атрибуты
Подсказки
(Ещё пример)
На практике 

**CSS**

Кратко
Пример
Как пишется
Как это понять
Подсказки
На практике

**Инструменты**

Кратко
Как понять
На практике

Кратко
Как происходит
На практике

Кратко
Как пишется
На практике

**JS**

Кратко
Как пишется
Как понять
На практике

Предлагаю:

а) подумать, действительно ли в разделах JS и Инструменты не нужны подразделы, которые опущены (типа Пример, Как пишется) — сейчас такое чувство, что все это уходит в одну кучу в раздел Как понять.

б) внимательнее следить за структурой при создании/редактировании статей — чтобы подразделы шли в одинаковом порядке и одинаково назывались.

**Comment by nlopin** [comment]
Договорились:
* я синкнусь с Алёной и принесу лучшие практики в JS и инструменты
* Оля исправит шаблон и мы будем использовать его

**Comment by tachisis** [comment]
Поняла, что мы недообсудили вопрос про подразделы внутри блоков практики. Я правильно понимаю, что у нас нет технической возможности правильно встраивать подзаголовки в оглавление? Можно ли написать какое-то исключение, чтобы подзаголовки в этом разделе все же были, но не попадали в оглавление, или нужно при редактировании перестраивать структуру практики так, чтобы там не были нужны подзаголовки? Кажется, что это увеличит работу, потому что разработчики любят все структурировать :)

**Comment by solarrust** [comment]
Кажется, это хороший вопрос для разработки: можем ли мы исключить этот раздел из построения оглавления.

**Comment by tachisis** [comment]
Приняли решение по аналогии с принятым по поводу тега details: если текст такой сложный, что ему нужны заголовки — переносим его в тело статьи и делаем автора практики контрибьютором. Если же текст практики подпадает под жанр практики (личное мнение, рецепт), но все равно структурирован автором — переструктурируем его так, чтобы убрать заголовки (например, отбиваем смысловые блоки эмодзи).
