### ISSUE TITLE
Способы подключения стилей на страницу

### ISSUE THREAD

**Issue by kanishev** [doka-guide/content#2279]
Статья о том, какие бывают способы подключения стилей на страницу, каковы их плюсы и минусы. Отдельное внимание отмечу на _inline_ стилях. Объясню почему инлайнить стили не рекомендуется.

**Comment by solarrust** [comment]
Звучит как идея отличной статьи!
Возьмёшься?

**Comment by kanishev** [comment]
Обязательно!
