### ISSUE TITLE
Добавить статьи про CSS свойства repeating-XXX-gradient()

### ISSUE THREAD

**Issue by Mitorun** [doka-guide/content#2310]
Нужно добавить в доку свойства `repeating-linear-gradient()`, `repeating-radial-gradient()`, `repeating-conic-gradient()`.

Готов взяться за написание этих трех статей.

**Comment by solarrust** [comment]
Создала отдельные задачки #2313 #2312 #2311 
Эту закрываю.

Отпишись, пожалуйста, в новых задачках. Тогда я смогу их назначить на тебя =)
