### ISSUE TITLE
Функция `repeating-conic-gradient()`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2313]

**Comment by solarrust** [comment]
@Mitorun привет! Планируешь написать эту доку? Если нет — ничего страшного. Скажи и я откреплю задачу =)

**Comment by Mitorun** [comment]
> @Mitorun привет! Планируешь написать этот документ? Если нет ничего — страшного. Скажи и я откреплю крышки =)

Вообще планировал написать после того как свой сайт закончу, но это затянулось. Пожалуй лучше открепить от всех задач, о них помню и если что вернусь к написанию.

**Comment by solarrust** [comment]
Буду очень ждать твоего возвращения! Успехов с сайтом =)
