### ISSUE TITLE
Не отправляется оценка статьи

### ISSUE THREAD

**Issue by Affid** [doka-guide/content#2317]
При попытке отправить позитивную оценку статьи 
https://doka.guide/html/flow/

Вылетает сообщение об ошибке и предложение попробовать еще раз. В консоли видна запись о коде ошибки 405 при использовании fetch метода в запросе.
![image](https://user-images.githubusercontent.com/47119594/140417589-3bba2451-e1b5-4098-88b6-ce5b30ae3799.png)

После нескольких перезагрузок страницы кнопка исчезла со страницы(по крайней мере стала не видна)

**Comment by igsekor** [comment]
Это не баг. Мы переезжаем на новый сервер. В течение нескольких дней форма должна вернуться. Здорово, что подметили! 🙃

**Comment by Affid** [comment]
Понял:)
