### ISSUE TITLE
Статья по работе языка с памятью

### ISSUE THREAD

**Issue by olegKusov** [doka-guide/content#2318]
Новичкам важно понимать не просто конструкции JS, но и то, как работают языки программирования.
1. Что происходит при объявлении переменной
2. Что такое стек и куча, как они работают, показать примеры с картинками. 
3. Какие данные хранятся в стеке, а какие в куче. Что такое инструкции, где они хранятся, как выполняются. Всё это следует объяснить простым языком с картинками и мб анимациями. Подать контент Like for keeds - чтобы всем было понятно.
4. Чем JS отличается от низкоуровненых языков и привести примеры таких языков, показать как представлены данные на самом низком уровне (010010101), далее на уровне выше (ассемблер) и далее еще выше (высокоуровневые языки типа C++). И далее можно подняться на уровень JS.
5. Рассказать о том в чем разница между компиляцией и интерпретацией
6. Показать как работает браузер изнутри, как происходит выполнение кода, как работает JIT-компиляция
7. В разделе (https://doka.guide/js/ref-type-vs-value-type/) показать, что не во всех языках примитивы хранятся в стеке. В условном Python все примитивы это объекты и хранятся они по ссылке.

**Без понимания вышеизложенных пунктов у новичка будет непонимание сути хранения по ссылке и значению. Да и, в целом, будет непонимание того, что такое JS**

Ну и хочу заострить внимание на том, что для меня главная особенность Доки - ламповость, простота и понятность. Хочется видеть объяснение всего выжеизложенного таким, чтобы это понял каждый.

Для начинающих фронтендеров, которые умеют только верстать, такой материал будет очень полезным и Must have я бы сказал, перед тем как начать изучать JS.

**Comment by olegKusov** [comment]
Эти вопросы меня заинтересовали, потому что я сам сейчас занимаюсь статьей для своего блога и думаю было бы неплохо видеть подобную информацию и в Доке!

**Comment by nlopin** [comment]
Олег, привет! В планах дойти до основ Computer Science в следующем году. Потенциально это целый раздел. 

Текущая цель — покрыть синтаксис JavaScript. Дока в первую очередь справочник и мы хотим сначала закрыть эту потребность.

**Comment by olegKusov** [comment]
> Олег, привет! В планах дойти до основ Computer Science в следующем году. Потенциально это целый раздел.
> 
> Текущая цель — покрыть синтаксис JavaScript. Дока в первую очередь справочник и мы хотим сначала закрыть эту потребность.

О, очень круто! Спасибо!

**Comment by HellSquirrel** [comment]
Закрою, так как написали статью про тривиальную модель памяти
