### ISSUE TITLE
Дока по GitLab CI

### ISSUE THREAD

**Issue by vitalybaev** [doka-guide/content#2326]
В Доке уже есть статья про GitHub Actions. 

Однако многие компании используют GitLab и его CI. Могу рассказать о работе с ним аналогично статье по GitHub Actions.

**Comment by furtivite** [comment]
Привет, мы в редакции придерживаемся мнения, что сложно писать документацию по сервисам, потому что у них есть своя документация и они могут сделать редизайн, так что статья может быстро устареть. 

Мы написали статью про  GitHub Actions прежде всего потому, что сами пользуемся инструментом, чтобы создавать Доку. Поэтому мы отслеживаем изменения и всегда готовы обновить статью при необходимости. 

Написать вводную статью про сервис чтобы она не устарела через год или два — это сложная задача, но если вы хотите попробовать, мы не ограничиваемся в Доке одним Гитхабом.

**Comment by igsekor** [comment]
Можно сфокусироваться на конфигурационных файлах. Проблема состоит в том, что графические интерфейсы быстро устаревают.

**Comment by vitalybaev** [comment]
Да, безусловно упор на то, как с помощью конфига настроить основные типовые процессы во фронтенде

**Comment by nlopin** [comment]
Будет классно показать альтернативну GH Actions. Можно показать настройку на таком же примере, чтобы можно было сравнить. Добавлю в бэклог. @vitalybaev тебе интересно заняться такой статьёй?

**Comment by vitalybaev** [comment]
Да, я хочу взяться за такую статью

**Comment by nlopin** [comment]
Класс! 

Тебе потребуется [стайлгайд](https://github.com/doka-guide/content/blob/main/docs/styleguide.md) и [шаблон статьи](https://github.com/doka-guide/content/blob/main/docs/examples/article.md). 

Думаю стоит немного рассказать о самом гитлабе. Если тебе удобнее сначала обсудить структуру, то можно или открыть с ней пул реквест, или обсудить здесь. Думаю она не будет сильно отличаться от [статьи про гитхаб экшены](https://doka.guide/tools/github-actions/)

**Comment by vitalybaev** [comment]
Думаю, лучше структуру обсудить здесь. У меня пока что не очень много опыта в написании статей, но давно хочется это попробовать :)

Итак,  по структуре вижу так:

* Сначала нам нужен такой же коллаут _В этой статье мы говорим про инструменты CI/CD..._ - мне кажется, нет ничего плохого, чтобы использовать его как есть.
* Далее введение, в котором коротко рассказать, что такое гитлаб
* Пример из жизни (как пример с EditorConfig в статье про GitHub Actions). Вопрос - пример оставляем точно такой же или в этой статье расскажем на примере тестов или ESLInt, например?
## Как пользоваться
* Самые первые шаги - создание файла `.gitlab-ci.yml`
* Немного о том, из чего в гитлабе состоит конфигурация CI/CD - джобы, стейджи, их порядок выполнения (а также подсветить отличие от GitHub Actions, в котором конфигурация мультифайловая). Здесь я бы хотел все-таки воспользоваться скриншотом какого-нибудь воркфлоу, чтобы проилюстрировать порядок выполнения джобов. Аргумент про интерфейс понимаю, с другой стороны общая суть вряд ли поменяется. Или можно нарисавать что-то схематичное, как в туториалах по гиту.
* Рассказать про образ (ключевое слово `image`. + Добавить ссылку на Docker, чтобы почитать подробнее)
* Далее в статье про GitHub Actions идет описание того, как ограничить выполнение джоба по названию веток, источнику правок (пуш или пул реквест). Можно аналогично упомянуть, как это делается в GitLab CI, но, мне кажется, что в гитлабе это штука более второстепенная и бы упомянул это где-нибудь дальше. То есть я бы сначала дал именно тот самый минимум, что нужен для создания обычных джобов, а уже потом давал бы всякие нюансы настройки выполнения.
* Аналогично, я бы не стал в этом месте описывать управление порядком выполнения, как в статье про GitHub Actions
* Как задать скрипт, который будет выполняться
* Как запустить что-то в разных версиях ноды
<---- Вот здесь мы фактически рассказали про минимум, который нужен, чтобы писать свои джобы. И теперь логично рассказать немного про нюансы.
* Ограничение выполнения в определенных ветках, тегах, источниках правок и т.д.
* Возможность джобы не останавливать пайплайн, если она провалена (`allow_failure`)
* Управление порядком выполнения
* Возможность джобы запускаться только вручную
## На практике
* Можно весь пример повторить как в статье про GitHub Actions

Отдельно хочется рассказать про кеширование для ускорения работы. Однако здесь все очень непросто, кешировать `node_modules` втупую часто бывает очень медленно, поскольку гитлаб под капотом по факту создает ZIP архив директории, что на больших проектах может быть поразительно медленно (был опыт когда только кеширование выполнялось 4 минуты). Был даже [ишью](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1797) с этой проблемой, однако единственный фикс по нему был использование более быстрой импелементации zip. В этом плане хорошо работает кеширование с Yarn Berry, поскольку он стал кеш хранить по одному файлу на пакет, что молниеносно архивируется. Насчет более новых версий NPM мне нужно изучить вопрос, так как с NPM 7+ у меня опыта очень мало.

Дополнительно добавить перекрестную ссылку на новую статью в статью про GitHub Actions.

**Comment by nlopin** [comment]
Офигенный план! Я предлагаю использовать тот же самый или очень похожий пример, чтобы читателю было легко сравнить две статьи. 

Если получится в раздел «Как пользоваться» добавить подзаголовки, то будет отлично. В Github Actions их нет, и получилась простыня, хочется этого избежать. Можно прямо по твоим пунктам делать заголовки в виде глаголов «Создать `.gitlab-ci.yml`», «Написать конфигурацию», «Задать скрипт» и так далее

Про кеширование в разделе «на практике» — офигенно, именно для таких штук существует раздел.

**Comment by vitalybaev** [comment]
Отлично! Про заголовки я как раз сам думал - их очень не хватает в статье про GitHub Actions, но самому такие вещи править не решался.

Начинаю активно заниматься статьей ✍️
