### ISSUE TITLE
Переделать картинки в гайде про флексбоксы

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#2367]
Сейчас на рисунках в гайде по флексбоксу (https://doka.guide/css/flexbox-guide/) поперечная ось обозначается как "дополнительная", что сбивает с толку, поскольку в тексте нет ни одного такого упоминания.

![image](https://user-images.githubusercontent.com/4408379/141009691-c3737d1e-3059-4073-b034-6db8a0195ea8.png)

То же самое относится и к размерам:

![image](https://user-images.githubusercontent.com/4408379/141009941-21af78f4-1fca-467d-a220-d9020e01da0d.png)

Возможно это всё так и было задумано, но кажется текст и рисунки должны использовать одну и ту же терминологию, чтобы не было лишних вопросов.

**Comment by solarrust** [comment]
Спасибо! Унесу дизайнерам
