### ISSUE TITLE
Дока про generator / yield

### ISSUE THREAD

**Issue by robotikz** [doka-guide/content#2370]
не хватает доки по generator / yield
готов помочь

**Comment by nlopin** [comment]
Привет! Будем рады помощи. У нас уже есть автор на доку по итераторам #2228 , генераторы как раз следом хорошо встанут.

Давай структуру тут набросаем (или можно в драфте PR) и обсудим.

Тебе поднадобится [руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).

**Comment by nlopin** [comment]
@robotikz ты ещё планируешь делать?

**Comment by robotikz** [comment]
@nlopin как раз хотел заняться на "праздниках" если еще актуально!

**Comment by nlopin** [comment]
Да, ждём

**Comment by robotikz** [comment]
привет, я глянул смежную тему  итераторы #2228, ее почти скопипастили javascript.info, это так к слову, просто думаю как еще лучше можно эту тему написать

**Comment by Windrushfarer** [comment]
Извините, на меня просто внезапно снизошла идея статьи и как ее сделать. С декабря надеюсь ничего не изменилось

**Comment by HellSquirrel** [comment]
Статья ищет нового автора :)
