### ISSUE TITLE
Ошибка в картинке статьи про цвета

### ISSUE THREAD

**Issue by hoblex** [doka-guide/content#2373]
https://doka.guide/css/web-colors/#hex

![image](https://user-images.githubusercontent.com/47644252/141120552-1090ca29-56a4-4bee-8fc1-4c66640422a0.png)
Код цвета в формате HEX не соответствует формату RGB. И еще - правильное название схемы CYMK или CMYK?

**Comment by solarrust** [comment]
Привет!
Цвет #F5DF4D в HEX-е соответствует цвету 245 233 77 в RGB
![CleanShot 2021-11-11 at 13 18 16](https://user-images.githubusercontent.com/13676514/141281120-edf6d259-fce4-4089-b540-7d31ad140930.png)

Уточни, пожалуйста, что именно ты считаешь ошибочным в данном случае?

**Comment by hoblex** [comment]
На исходной картинке в подписи для цвета G указан 233, а не 223

**Comment by solarrust** [comment]
Всё, теперь увидела, поняла, осознала. Всё поправим! Спасибо большое 🖤

**Comment by hoblex** [comment]
:)
Похоже, еще и в формате CMYK не тот цвет указан

**Comment by solarrust** [comment]
Закинула ПР с исправленной картонкой. Теперь цвета написаны верно, а CYMK, он же CMYK, вообще выпилила. Речь не о нём =)

**Comment by hoblex** [comment]
Отлично!:)
