### ISSUE TITLE
Ошибка в доке про text-align

### ISSUE THREAD

**Issue by mitorun** [doka-guide/content#2379]
На странице https://doka.guide/css/text-align/ в первом примере повторяются два значения свойства:

p {
  text-align: left;
  text-align: start;
  text-align: right;
  text-align: end;
  text-align: center;
  text-align: justify;
  text-align: justify-all;
  **text-align: start;
  text-align: end;**
  text-align: match-parent;
}

***

На MDN вроде больше значений, может что-то добавить следует.

***

Также есть идея в подобных примерах кода подписывать комментарием значение по умолчанию. Ну и это значение, по умолчанию, должно всегда идти первым:

```css
p {
  text-align: left;/* По умолчанию */
  text-align: start;
  ...
}
```

***

П.С. Немного оффтоп-вопрос: есть ли простой способ в гитхабе самому поправить мелкие опечатки в статьях?

**Comment by furtivite** [comment]
Привет! Можно [открыть статью на гитхабе](https://github.com/doka-guide/content/blob/main/css/text-align/index.md), и дальше либо нажимаешь на карандашик в правом верхнем углу:

![Screenshot 2021-11-10 at 19 29 42](https://user-images.githubusercontent.com/50330458/141153387-6727392d-8293-44d1-b8a8-78b54637539f.png)

Тогда откроется простой редактор. 

Либо нажимаешь там же на клавиатуре на точку на включённой английской раскладке (там где Ю), и получаешь целый VS Code в браузере. 

![Screenshot 2021-11-10 at 19 31 11](https://user-images.githubusercontent.com/50330458/141153645-97b36e96-0582-479c-92cb-b1534c4b2add.png)

**Comment by solarrust** [comment]
Привет!
Спасибо что обратил на это внимание. 
Такой способ записи не очень валиден и удобен для чтения. Со временем мы от него ушли и теперь не перечисляем значения в таком виде. Но в каких-то старых статьях просто ещё не успели порефакторить этот момент. 
Обязательно запланирую в ближайшее время добраться с редактурой до этой статьи! 🙌

**Comment by SelenIT** [comment]
Кстати, по умолчанию не `left` 😳

По актуальной спеке CSS Text 3 по умолчанию `start` (как минимум [с 2013 года](https://www.w3.org/TR/2013/WD-css-text-3-20131010/#text-align-property)). Раньше, в CSS2.1, было _«безымянное значение, которое ведет себя как `left` при `dir=ltr` и как `right` при `dir=rtl`»,_ но на знаю, надо ли сейчас упоминать этот исторический курьез.

**Comment by solarrust** [comment]
@SelenIT спасибо, что подметил это. Может быть, принесёшь правку, чтобы было всё по красоте?

**Comment by solarrust** [comment]
Пофиксили в пиаре https://github.com/doka-guide/content/pull/4637
