### ISSUE TITLE
Ошибка в статье о блочной модели

### ISSUE THREAD

**Issue by Ortiz1221** [doka-guide/content#2398]
В [статье](https://doka.guide/css/box-model/) есть абзац о том, что: 

> Элементы со строчным (`display: inline`) или строчно-блочным (`display: inline-block`) отображениями подстраивают и ширину и высоту под вложенный контент, если при помощи `width` и `height` не задано иное.

Из формулировки складывается впечатление, что для `display: inline` можно задать `width` и `height`, но на самом деле значение `inline` проигнорирует эти свойства. 

[Ссылка на MDN](https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/The_box_model#блочные_и_строчные_элементы)

**Comment by solarrust** [comment]
Спасибо большое! И правда, формулировка может быть трактована неоднозначно. Принесёшь правку в пул-реквесты?

**Comment by edbond88** [comment]
@furtivite можно закрыть баг

**Comment by furtivite** [comment]
@edbond88, да, так и есть. Спасибо за внимательность.
