### ISSUE TITLE
В статье про CSS-анимации сделать цвета фигур более приглушенными

### ISSUE THREAD

**Issue by Ortiz1221** [doka-guide/content#2401]
В [статье ](https://doka.guide/css/animation/) анимированы ярко красный круг и ярко синий квадрат и на определённом шаге они начинают менять цвета с синего на зелёный, а потом на красный. 

Обратите, пожалуйста, внимание, что для людей с эпилепсией это может быть триггером. Также это может быть проблемой для тех, у кого очень слабый вестибулярный аппарат. Например, у меня мерцание ярких цветов вызвало головокружение и тошноту. 

Вариант решения: выбрать более спокойные пастельные оттенки и сделать их смену более медленной + менять цвета обеих фигур синхронно.

Особенно тяжело было на этой анимации:

![image](https://user-images.githubusercontent.com/41075682/141537695-448823dc-8abf-4af8-89bc-ae1aae775539.png)

**Comment by solarrust** [comment]
Спасибо большое, что подсветила эту проблему! 🖤
Задачка на перерисовку демок в этой статье уже есть, повысила её приоритет и @skorobaeus скоро сделает красивые демки с учётом возможных особенностей восприятия 🙌
