### ISSUE TITLE
Почему статья про <table>, называется "Таблицы"?

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2402]
В разделе HTML названия статей про все теги имеют формат "\<tag\>", кроме единственной статьи про тег `<table>`, которая называется "Таблицы". Может стоит её переименовать?

**Comment by solarrust** [comment]
Потому что внутри этой статьи рассматриваются все теги, используемые для создания таблицы 
![CleanShot 2021-11-13 at 12 22 55](https://user-images.githubusercontent.com/13676514/141613570-58be4a33-ed58-4f58-8bda-71f17ccf1ba4.png)

По структуре эта статья похожа на гайды по гридам или по флексам, в которых тоже перечисляются все относящиеся к этой технологии свойства.

**Comment by cergmin** [comment]
Понятно, спасибо
