### ISSUE TITLE
Неверное утверждение в статье «Контекст наложения»

### ISSUE THREAD

**Issue by davayd** [doka-guide/content#2408]
Можете привести пример правоты этого суждения "Чем ниже в списке слой, тем он выше над основным холстом."? 

У меня получается по-другому - "Чем ВЫШЕ в списке слой, тем он выше над основным холстом."

![image](https://user-images.githubusercontent.com/17270614/141696874-27c7ec4e-e8be-4860-bc5a-54c56036f0e8.png)

**Comment by solarrust** [comment]
Привет! Ты прав, я сейчас тоже перепроверила и верхний в списке слой будет поверх остальных слоёв холста. Сейчас уберу эту фразу в статье =)
