### ISSUE TITLE
Проблемы с демкой в html/input

### ISSUE THREAD

**Issue by jag-k** [doka-guide/content#2410]
При нажатии на кнопку отправки происходит `POST` запрос на [html/input/demos/inputs/input1.php](https://doka.guide/html/input/demos/inputs/input1.php) с данными `browser=ie&comment=<данные из textarea>` и выдаёт ошибку 404.

При фокусе на радио-кнопки не видно самого фокуса.

**Comment by solarrust** [comment]
Метко подмечено, спасибо большое! Возьмём в работу и поправим 🙌

**Comment by jag-k** [comment]
@solarrust если что, могу и я поправить))

**Comment by solarrust** [comment]
Давай! Так точно будет быстрее =)

**Comment by jag-k** [comment]
Тогда небольшой вопрос по отправке. Можно будет просто сделать отдельную страницу с выводом результатов запроса или pop-up?

**Comment by solarrust** [comment]
Попап — не очень хороший паттерн. Всех раздражают всплывающие окна =) А тут ещё и в айфрейме. Суть демки в самой форме, данные, отправляемые на сервер, не так важны. Можно скрыть форму и показать текст. Что-то вроде «форма отправлена 👍».

**Comment by jag-k** [comment]
> Попап — не очень хороший паттерн. Всех раздражают всплывающие окна =) А тут ещё и в айфрейме. Суть демки в самой форме, данные, отправляемые на сервер, не так важны. Можно скрыть форму и показать текст. Что-то вроде «форма отправлена 👍».

Как вариант можно под формой добавить что отправилось

**Comment by jag-k** [comment]
Сделал предварительную версию. Так же накинул немного адаптива, но думаю, стоит ещё поработать

| ![html/input demo with form result on desktop](https://user-images.githubusercontent.com/30597878/141841414-7ceae986-f732-4f7d-8594-a91a5041b3c1.png) | ![html/input demo with form result on mobile](https://user-images.githubusercontent.com/30597878/141841430-29577ba4-0c33-44eb-80b1-7eaf3a374e5d.png) | ![html/input demo on mobile](https://user-images.githubusercontent.com/30597878/141841434-d5f099c0-58ac-4a04-a29d-5ae638f6ab71.png) |
| --- | --- | --- |
| Демо после отправки формы | Демо после отправки формы на мобильном устройстве | Демо на мобильном устройстве |

Что скажете, @solarrust ?)

**Comment by jag-k** [comment]
Добавил вариант в виде отдельной страницы. Выглядит примерно так

| ![Result of demo with filled form](https://user-images.githubusercontent.com/30597878/141851723-a3fdadb4-d7f8-4911-a729-748239d87719.png) | ![Result of demo with empty form](https://user-images.githubusercontent.com/30597878/141851730-ed5a0548-fa26-42f3-b80e-15a88df671e3.png) |
| --- | --- |
| Отправлена заполненная форма | Отправлена пустая форма |

Работает при помощи `GET` запроса с формы на соседнюю "демку". Думаю оставить этот вариант

**Comment by solarrust** [comment]
На твой вопрос из [твитв](
