### ISSUE TITLE
Не загрузились новые обложки для статьи про таблицы

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2415]
В этом пул реквесте #2378 залили новые обложки для [статьи про таблицы](https://doka.guide/html/tables/), но если сейчас её открыть, то там будут висеть старые.
![image](https://user-images.githubusercontent.com/21996065/141879766-53d65a68-8bf5-41a6-aae1-80be018259a6.png)

**Comment by solarrust** [comment]
Можешь, пожалуйста, подробнее рассказать, что именно, на твой взгляд, не загрузилось? 
Я пока не улавливаю разницы с обложкой от дизайнера

![CleanShot 2021-11-16 at 09 22 11](https://user-images.githubusercontent.com/13676514/141932327-c6a1de22-49ee-4f2e-a7f0-1c4e25aad9e0.png)

**Comment by solarrust** [comment]
Открыла только что, вижу нормальную обложку 
![CleanShot 2021-11-16 at 09 24 18](https://user-images.githubusercontent.com/13676514/141932580-29143735-734f-4eb2-a821-e0aea24be662.png)


Очень похоже на кэш =) Попробуй, пожалуйста, сбросить его и проверить ещё разок.

**Comment by cergmin** [comment]
Очистил весь кеш браузера вручную и обложки обновились. Видимо проблема была действительно в нём, хотя это немного странно, потому что я обновлял страницу через Force Reload <kbd>Ctrl + Shift + R</kbd>.
