### ISSUE TITLE
Дока по Intl.DateTimeFormat

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#2417]
Сделать доку по DateTimeFormat: рассказать про методы и очень подробно остановиться на объекте `option`

Отдельно отметить, что в `DateTimeFormat` нельзя установить разделитель в датах, он берётся из локали пользователя, и рассказать, как можно собрать ISO дату: руками или через вызов метода `toISOString` объекта Date (сослаться на доку).

Проставить ссылки из статьи #2416

**Comment by AntonGorelov** [comment]
@nlopin могу начать писать эту тему

**Comment by furtivite** [comment]
@HellSquirrel
