### ISSUE TITLE
Дока по классу `Date`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#2418]
Рассказать про методы класса `Date`, его плюсах и минусах, показать альтернативы (Intl.DateTimeFormat).

**Comment by RuslanAsadov** [comment]
Еще в процессе?

**Comment by nlopin** [comment]
> Еще в процессе?

Привет. Нет, она ждёт своего автора

**Comment by kseniaSs** [comment]
Добрый день, можно забрать тему? За неделю справлюсь

**Comment by nlopin** [comment]
Конечно! 

Тебе пригодится [руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md). Думаю по структуре можно сделать что-то типа обзора класса и методов. В качестве примера посмотри на доку по классу [`Map`](https://doka.guide/js/map/) и [`localStorage`](https://doka.guide/js/local-storage/)
