### ISSUE TITLE
Статья " Комбинированные селекторы". Улучшение описание к демо

### ISSUE THREAD

**Issue by RomanBarannickov** [doka-guide/content#2425]
Описание к демке со звездочками какое - то расплывчатое.  
`Но сейчас при наведении курсора будут выделяться все элементы после (т. е. справа). Чтобы это исправить, мы изменим порядок следования элементов с помощью CSS-свойства direction: rtl:`
* При первом прочтении не совсем ясно, что за баг вообще появляется и куда собственно говоря добавляет свойство. Может стоит сделать вторую демку. Чтоб было наглядно, если сделать вот так сломается, если сделать вот так заработает.
* Возможно стоит дополнить статью с приведенным полностью css кодом демки, чтоб было наглядно, куда добавилось свойство 

P.S. Могу взять на себя, если дадите добро на мои предложения)

**Comment by solarrust** [comment]
Привет! Даю добро =)
