### ISSUE TITLE
Пример кода не соответствует демо. Статья :invalid, :valid

### ISSUE THREAD

**Issue by hoblex** [doka-guide/content#2440]
Статья https://doka.guide/css/invalid-valid/
В примере кода другой placeholder, по сравнению с демкой.  
![image](https://user-images.githubusercontent.com/47644252/142278731-6a8af589-8137-4a55-a344-ab5b6a67fac4.png)

Демка "не ругается" на не русские буквы

![image](https://user-images.githubusercontent.com/47644252/142278989-7cf25449-6a6a-46bc-a3aa-163421cc6c97.png)

**Comment by rusakovdenis** [comment]
Привет. Готов взяться.

1. _placeholder_ в демке поменять;
2. заметил, что не работает валидация в демке для поля **Имя**, т.к. там проставлен _type='text'_  без регулярки, которая бы проверяла на наличие кириллицы (нативно так нельзя);
Предлагаю для 2 пункта:
- либо добавить немного _js_, на проверку кириллицы;
- либо использовать в демке для поля **Имя** -> _minlength_, чтобы проверять ввел ли пользователь, как минимум 4 символа

**Comment by solarrust** [comment]
Привет! 
@hoblex спасибо большое что заметил неточность 👍
@rusakovdenis спасибо большое, что готов помочь! Не хотелось бы добавлять JS в такую простую демку. Может быть добавим паттерн для проверки ввода цифр? Они крайне редко встречаются в имени. И это не будет антипаттерном валидации как минимальное количество символов в имени. Ведь живут же люди с именами Ю или Ин =)

**Comment by rusakovdenis** [comment]
@solarrust Добро)
