### ISSUE TITLE
Ошибка в коде списка DL

### ISSUE THREAD

**Issue by DmitrijPerejro** [doka-guide/content#2446]
https://doka.guide/html/dl-dd-dt/

В примере списка `<dl>` ошибка при закрытии тега `<dt>`

![Screenshot 2021-11-18 at 17 08 58](https://user-images.githubusercontent.com/25080661/142442294-96d0a7ed-d76b-431c-9f63-87ef26e9f3b2.png)

**Comment by rusakovdenis** [comment]
Привет
Готов поправить)

**Comment by solarrust** [comment]
@rusakovdenis спасибо большое за твою готовность помочь 🤗
Правку уже принесли в #2447
