### ISSUE TITLE
Статья "Реактивность". Часть картинки сливается с темным фоном при темной теме

### ISSUE THREAD

**Issue by hoblex** [doka-guide/content#2460]
https://doka.guide/js/reactivity/

Темная тема
![image](https://user-images.githubusercontent.com/47644252/142732307-28514796-9be6-43e7-b5ab-748f0ab840bf.png)

Светлая тема
![image](https://user-images.githubusercontent.com/47644252/142732339-3973f2bd-b57b-4463-87b2-62a977733e08.png)

**Comment by nlopin** [comment]
Спасибо, поправим 👍

**Comment by cergmin** [comment]
Могу этим заняться, если ещё никто не взялся

**Comment by StarHamster** [comment]
Кажется, тёмная тема изменилась с тех пор. Сейчас всё более-менее нормально, можно, я думаю, закрывать ишью, @nlopin, @solarrust 

![изображение](https://user-images.githubusercontent.com/91747573/192136868-8019def3-1267-444a-9e7e-a91ff635bf4a.png)

**Comment by furtivite** [comment]
Кажется, тут всё-таки, нужна небольшая доработка, чтобы доделать изображение в стиле Доки. Может оставим пока?

**Comment by skorobaeus** [comment]
Кажется, сделать схему быстрее, чем обсудить её :)
