### ISSUE TITLE
Дополнение к статье про `font-weight`

### ISSUE THREAD

**Issue by KazakovAS** [doka-guide/content#2466]
Привет! Может быть добавить в статью то, как числовые значения соотносятся с названиями начертаний? Ведь обычно файлы шрифтов именуются именно через названия. Думаю было бы полезно для новичков.

по типу:
// 100 Thin;
// 200 Extra Light or Ultra Light; 
// 300 Light;
// 400 Regular or Normal or Book;
// 500 Medium;
// 600 Semibold or Demibold;
// 700 Bold;
// 800 Extra Bold or Ultra Bold;
// 900 Black or Heavy
// 950 Extra Black or Ultra Black

**Comment by rusakovdenis** [comment]
Привет!
Готов взять в работу)

**Comment by KazakovAS** [comment]
Не совсем про weight, скорее в другую статью улетит.. Но наверное, стоит так же где-то упомянуть, что в названиях шрифтов могут попадаться: 
roman, narrow, wide, mono, condensed, expanded, display, text
обозначающие в каком именно стиле нарисованы буквы и как по задумке авторов использовать конкретный шрифт

**Comment by solarrust** [comment]
@rusakovdenis класс! Назначила задачку на тебя! Думаю, что эту инфу можно дать в сворачивающемся списке. Она, всё же, не нужна постоянно.

**Comment by solarrust** [comment]
@KazakovAS лучше это примечание добавить в отдельную задачку иначе оно потеряется сразу, как закроем эту ишью. Но, кажется, это не сильно относится к вебу, скоре к штифтовому дизайну. Да и не у всех шрифтом есть дополнения в имени, правило получается не универсальное. Но можно добавить эту подсказку в блок «На практике», например =)

**Comment by rusakovdenis** [comment]
@solarrust уточнение небольшое)

https://doka.guide/css/font-weight/

1. может блок _ключевые слова_ убрать и разместить справа от цифр? (чтобы легко было найти соответствие)
![image](https://user-images.githubusercontent.com/65253434/143413514-af9819c9-0637-44a2-9bc5-0ab7b4329ce9.png)

2. здесь подкорректирую
![image](https://user-images.githubusercontent.com/65253434/143413484-342c26f6-230e-4629-a8e3-3d3b88fc32af.png)
