### ISSUE TITLE
ошибка в примере кода innerHTML

### ISSUE THREAD

**Issue by maxxondagon** [doka-guide/content#2473]
Привет, в статье об [innerHTML](https://doka.guide/js/element-innerhtml/) лишняя точка в примере, возвращаем не класс.

![123](https://user-images.githubusercontent.com/67747059/142945201-7fe0aafb-ee9a-464a-8ca1-61ec15c80634.jpg)

**Comment by furtivite** [comment]
@maxxondagon, привет! Да, действительно. Сделаете пул-реквест? 

Если это ваш первый пул-реквест, можно посмотреть [видео с Вадимом](https://www.youtube.com/watch?v=y-_nXfKkI3w&t=277s), он подробно рассказывает, как это сделать.

**Comment by edbond88** [comment]
@furtivite может стоит закрыть тогда баг?

**Comment by furtivite** [comment]
> @furtivite может стоит закрыть тогда баг?

Да, спасибо, что подсветили. Задача решена.
