### ISSUE TITLE
Добавить стили демо в статье про `position`

### ISSUE THREAD

**Issue by Ortiz1221** [doka-guide/content#2478]
В уроке[ про позиционирование](https://doka.guide/css/position/) ([ссылка на гитхаб](https://github.com/doka-guide/content/blob/main/css/position)) обратите, пожалуйста, внимание на то, как в примере выглядит меню. Было бы круто хоть как-то его стилизовать.

![image](https://user-images.githubusercontent.com/41075682/143106643-7560e399-32b0-4da4-877d-eddeba9c20da.png)

**Comment by solarrust** [comment]
Демки в этой статье пока не попали в лапки @skorobaeus. Скоро она дойдёт до этой статьи и будет красиво 🔥
