### ISSUE TITLE
Битая ссылка

### ISSUE THREAD

**Issue by Ortiz1221** [doka-guide/content#2479]
[Урок в Доке](https://doka.guide/css/background/)
[Урок на гитхабе](https://github.com/doka-guide/content/tree/main/css/background)
![image](https://user-images.githubusercontent.com/41075682/143109804-791b5cdd-9189-4fe3-8b52-06a6a4199509.png)
![image](https://user-images.githubusercontent.com/41075682/143110032-ce89fe09-b244-42f2-99a1-e29308365da3.png)

**Comment by solarrust** [comment]
Привет!
Спасибо большое, и правда просочилась битая ссылка 🤔
Принесёшь ПР с правочкой? Там, кажется, все проблемы создаёт лишняя буква =)

**Comment by Ortiz1221** [comment]
Да, конечно, сделала
