### ISSUE TITLE
Совместимость с браузерами в статье про `text-decoration-skip-ink`

### ISSUE THREAD

**Issue by zizi-shoot** [doka-guide/content#2480]
В статьях не указана совместимость с браузерами.

На примере [text-decoration-skip-ink](https://doka.guide/css/text-decoration-skip-ink/) долго пытался разглядеть разницу в демке при разных значениях, но не увидел. Потом только понял, что возможно это свойство не работает в Safari (iOS в моём случае). Пришлось лезть на _caniuse_.

Может имеет смысл как-то ссылаться на этот ресурс, если есть проблемы с совместимостью?

Скрин демки из Safari

![image](https://user-images.githubusercontent.com/59991930/143134508-fd6c51b9-f61c-42a8-ac3d-5dd13d6df4b7.jpeg)

**Comment by solarrust** [comment]
Привет!
И правда, это важная информация. Было бы хорошо упомянуть о поддержке в статье. 
Принесёшь ПР с дополнением? 🙌

**Comment by zizi-shoot** [comment]
> Привет!
> И правда, это важная информация. Было бы хорошо упомянуть о поддержке в статье.
> Принесёшь ПР с дополнением? 🙌

Привет!
Конкретно к этой статье принесу, ок)
Но тут вопрос, пожалуй, более глобальный. Думаю своместимость надо указывать во всех статьях со свойствами, имеющими не полную совместимость

**Comment by solarrust** [comment]
Поддерживаю. Будем стараться указывать эту инфу везде, где поддержка не полная 👍
