### ISSUE TITLE
VIM

### ISSUE THREAD

**Issue by anatoly-kor** [doka-guide/content#2482]
Очень хочется написать **серию** статей про VIM(конкретно neovim, но это позже) и немного tmux. Гайдов всяких много, документация вроде бы есть на русском, но все это больно и сложно. Хочется сильно проще. Идея серии в том чтобы дать возможность заменить свой любимый IDE(Pycharm, Vscode, etc) на консольный VIM. Я с удовольствием напишу эту серию. 
Предполагаемая структура серии:

1. Как НЕ выйти из VIM? (ирония названия в том что обычно все ищут как из него выйти. `:q!` если что)

- Рассказать историю vim: сначала был vi, потом vim, сейчас neovim.
- Показать что получится в итоге серии статей(небольшой ролик или gif или наоборот видео минут на 5 с объяснением что происходит в процессе). Можно писать код взаимодействуя только с клавиатурой(никакой мышки или тачпада).
- Рассказать почему пользование vim положительно скажется на flow, скорость вырастет, но есть минус того что теперь не получится залезть в бд без отдельной программы или плагина vim(не знаю есть ли такой) как ранее это делали в IDE. 

2. Безболезненных переход к vim в своем любимом IDE

- Рассказать как в своем любимом IDE поставить vim shortcuts и начать пользоваться.
- Существующие моды в VIM:
— normal - перемещение по файлу
— v - visual mode для выделения строки, слова и тд
— i - insert mode для печати
— comand mode - : для ввода команд bash и редактирования директории(удалить, создать, редактировать файл)
- Простое перемещение: 
—  hjkl(это буквы перемещения влево, вверх, вниз, вправо)
—  web и WEB (перемещение к след началу следующего слова - word, концу слова - end, началу слова - backword)
— начало строки(0), начало строки кода(^),  конец строки ($)
— поиск слова в файле и замена слова
— переход к определению функции(gd - go defenition).
— Все действия в vim это английские слова(глаголы, существительные). Как удалить 2 слова: `d2w`(delete 2 word), как заменить все в (): `ci(`(change inside ( )

3. Установка neovim, tmux, плагинов. 
- Ставим neovim, tmux
- Ставим менеджер плагинов, показываем как пользоваться,  создаем шорткаты для быстрой установки плагинов, ставим парочку плагинов
- Делаем их красивыми: ставим тему которая нравится для обоих инструментов
- tmux - настраиваем и показываем как пользоваться. 
Тут довольно просто: показываем как поменять ключевое сочетания кнопок на удобное и как разделить терминал на 2 окна по вертикали или горизонтали. Как закрыть окно. Как выйти из tmux сессии. Как закрыть tmux сессию чтобы она более не существовала.
- Добиваем плагины, ставим популярные, настраиваем, показываем как пользоваться. 

> P.S: Описал приблизительную структуру серии, вероятно какой то из пунктов может разрастись до нескольких статей.

**Comment by nlopin** [comment]
Привет! Давай сделаем вводную статью про VIM и азы работы с ним, а дальше посмотрим. С вимом совершенно точно все сталкиваются и будет классно про это рассказать.
