### ISSUE TITLE
Подзаголовки в разделе "На практике"

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2484]
Если сделать заголовок второго уровня в разделе "На практике", то будет казаться, что человек ничего и не написал, а дальше просто идёт следующий раздел. Возможно, стоит оговорить это в [styleguide](https://github.com/doka-guide/content/blob/main/docs/styleguide.md) или регулировать такие вещи на уровне платформы.

![image](https://user-images.githubusercontent.com/21996065/143225947-19dae4e4-d300-4931-b8d9-3c025d2b5cf3.png)

**Comment by nlopin** [comment]
Привет! Да, у нас сейчас редактор исследует такие случаи и скоро будем перерабатывать такие материалы
