### ISSUE TITLE
Почему иногда в качестве автора стоит Дока Дог?

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2493]
В некоторых статьях или блоках разделов "На практике" в качестве автора стоит Дока Дог. Почему так получилось, если это, на сколько я понимаю, не живой человек?

**Comment by furtivite** [comment]
Issue дублирует #1996. Если коротко: это живые люди, которые работали над Докой до публичного запуска и до планов о публичности. Мы пока решили так сделать. Дальше будем думать, что делать.
