### ISSUE TITLE
Добавить функции CSS min, max, clamp

### ISSUE THREAD

**Issue by dobernike** [doka-guide/content#2495]
На сайте есть calc, но нет min, max, clamp
см. https://web.dev/min-max-clamp/

возможно пересекается с https://github.com/doka-guide/content/issues/476

**Comment by solarrust** [comment]
Привет! Да, спасибо, надо будет обязательно написать доки по этим функциям. 
Создала отдельные ишью: #2496 #2497 #2498 чтобы продолжить обсуждение каждой отдельной доки в них.
Эту задачку закрою 🙂
