### ISSUE TITLE
Функция `min()`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2496]

**Comment by Ginger-Raccoon** [comment]
Привет! Видел еще и остальные ишью подскажи, на каждую функцию своя статья или все в одну должны войти?

**Comment by solarrust** [comment]
Привет! Лучше если на каждую функцию будет своя статья. А потом можно будет собрать их вместе в общую статью, рассказав в ней про интересные кейсы совместного использования.

**Comment by Ginger-Raccoon** [comment]
Я готов взяться и потихоньку закрыть все 3 :)

**Comment by solarrust** [comment]
Фантастически! Назначу эту задачку на тебя и буду очень ждать твоей статьи =)
