### ISSUE TITLE
Функция `max()`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2497]

**Comment by denisputnov** [comment]
Привет, готов взяться за эту статью.
Также планирую написать статью про функцию clamp #601.
Могу взять ее как сразу в параллельную работу, так и после этой.
@solarrust, закрепишь за мной?

**Comment by denisputnov** [comment]
@TatianaFokina, привет!
Пока писал статью, заметил некоторые недочёты в статье `css/min`
Подскажи пожалуйста, я могу поправить их в рамках этой issue или нужно создать новую?

**Comment by TatianaFokina** [comment]
> @TatianaFokina, привет! Пока писал статью, заметил некоторые недочёты в статье `css/min` Подскажи пожалуйста, я могу поправить их в рамках этой issue или нужно создать новую?

Привет! Лучше создать отдельную ишью под исправления `min()`.
