### ISSUE TITLE
У нас есть небольшое комьюнити бекенда

### ISSUE THREAD

**Issue by proggga** [doka-guide/content#2503]
вопрос, насколько логично писать комменты к вам, добавить разделы по бекенду и все такое?

**Comment by nlopin** [comment]
Привет! Спасибо, что обратил внимание на наш проект. 

Мы фокусируемся в первую очередь на веб разработке и пока не планируем отдельных разделов про бэкенд. Но мы считаем, что фронтендеры должны представлять, как работает бэкенд. У нас есть [отдельный майлстоун](https://github.com/doka-guide/content/milestone/17) по темам, которые хочется покрыть. Вы очень поможете, если сможете написать материалы по ним. 

Можем обсудить и другие материалы. Понимания каких тем бэкендеры ожидают от фронтендеров? Можем оттолкнуться от этого списка

**Comment by proggga** [comment]
тогда еще вопрос, насколько позволяет ваша лицензия нам сделать форк вашего проекта, и сделать версию для бекендеров? я не хочу вас ни обидеть ни чем либо заафектить

**Comment by pepelsbey** [comment]
Дока стартовала ещё на уровне идеи и запустилать позже именно как ресурс для фронтендеров. У этого есть разные причины, но думаю основные две:

1. Новички чаще всего входят в айти именно через веб
2. Изначальная редакция была именно из веб-разработчиков

Сделать из Доки проект, в котором полноценно представлен бэкенд, думаю, можно. Другое дело, что это потребует кардинальных изменений в структуре проекта, редакции и прочего. Вряд ли мы пойдём на такое в ближайшее время. Точно не раньше, чем докажем состоятельность проекта — себе и сообществу.

Если говорить про форк, то если вы возьмёте нашу платформу (шаблоны, сборку, скипты), то никаких проблем — лицензия MIT ([см. подробнее про наши лицензии](https://doka.guide/licenses/)) тут не мешает. Другое дело, что мы бы не хотели, чтобы наш дизайн и стиль использовались где-то ещё.

В общем, пусть цветут тысячи цветов :)

**Comment by proggga** [comment]
> Другое дело, что мы бы не хотели, чтобы наш дизайн и стиль использовались где-то ещё.
Понял, принял, это и хотел уточнить, спасибо!

p.s. Вы молодцы!
