### ISSUE TITLE
Обновить список falsy values в статье о циклах

### ISSUE THREAD

**Issue by nasthe2** [doka-guide/content#2509]
Привет! 
В [статье о циклах](https://doka.guide/js/loop/) среди перечисланных falsy values отсутствет упоминание `-0`, хотя в [статье if ... else ](https://doka.guide/js/if-else/)упоминается.
_loop:_
<img width="654" alt="Снимок экрана 2021-11-28 в 21 01 38" src="https://user-images.githubusercontent.com/32321658/143780341-715b06b6-b6cf-4c57-86dc-e01ea3b05180.png">
_if ... else:_
<img width="661" alt="Снимок экрана 2021-11-28 в 21 02 09" src="https://user-images.githubusercontent.com/32321658/143780353-00295070-696c-4ec4-8c96-e9d01f9eb340.png">

**Comment by nlopin** [comment]
@nasthe2 спасибо за репорт! Сможешь прислать PR с исправлением?

**Comment by nasthe2** [comment]
@nlopin ага :)

**Comment by nasthe2** [comment]
Исправлено в https://github.com/doka-guide/content/pull/2529
