### ISSUE TITLE
Объединить статьи clearInterval() и clearTimeout()

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2519]
Функции clearInterval() и clearTimeout() работают предельно одинаково, они даже являются взаимозаменяемыми, поэтому мне кажется, что есть смысл объединить их в одну статью.

**Comment by nlopin** [comment]
Привет! Спасибо за идею 👍. У меня возникала мысль объеденить их, но разные статьи — это осознанное решение:

* это справочные статьи. В справочнике мы стремимся к быть максимально атомарными, короткими статьями покрывающими только один метод/свойство
* мы не хотим, чтобы эти функции использовали взаимозаменяемо, потому что семантически они отличаются. Я бы не хотел видеть код, где таймаут удаляется через `clearInterval`
* в обеих доках мы говорим о взаимозаменяемости
