### ISSUE TITLE
Битая ссылка в статье про шифрование

### ISSUE THREAD

**Issue by vitalybaev** [doka-guide/content#2526]
В [статье про шифрование](https://doka.guide/tools/encoding/) есть такой отрывок:

> Протоколы TLS, HTTP, HTTPS описаны в статьях «[Протоколы передачи гипертекста](https://doka.guide/tools/hypertext-protocols)».

Такой ссылки сейчас нет. Поискал и нашел статью про [протокол HTTP](https://doka.guide/tools/http-protocol/), но не решился заменить ссылку на него, так как все же про TLS и HTTPS там не написано и лучше тут с точки зрения редактора подумать, как лучше сделать.

**Comment by furtivite** [comment]
Привет, спасибо, что отметил. Призову @igsekor: «Подскажешь, куда должна была вести ссылка»?

**Comment by igsekor** [comment]
> Привет, спасибо, что отметил. Призову @igsekor: «Подскажешь, куда должна была вести ссылка»?

Должна была быть статья, которую мы в итоге разделили на несколько и ещё будем писать, думаю. Предлагаю заменить на строку:

Протоколы TLS, HTTP, HTTPS описаны в статьях «[Протокол HTTP](https://doka.guide/tools/http-protocol/)» и «[Работа с сетью](https://doka.guide/tools/network/)».

**Comment by vitalybaev** [comment]
Ишью закрыто в #2536
