### ISSUE TITLE
Intersection Observer

### ISSUE THREAD

**Issue by RomanovRoma** [doka-guide/content#2539]
Не нашел информации про Intersection Observer

**Comment by nlopin** [comment]
Привет! Да, такого материала у нас пока нет. Итересно ли тебе его написать?

**Comment by kvrvgixzis** [comment]
А насколько материал должен быть уникальным? Можно его принести из mdn?

**Comment by kvrvgixzis** [comment]
А есть гайд? Лень искать сейчас. Займусь на досуге

**Comment by zizi-shoot** [comment]
@nlopin @solarrust могу взять в работу

**Comment by nlopin** [comment]
@zizi-shoot забирай 👍
