### ISSUE TITLE
Дока JavaScript / switch - бага нет, все брейки на местах

### ISSUE THREAD

**Issue by saharok** [doka-guide/content#2563]
"В коде появился баг — значение для бриллиантового уровня будет установлено в 0.1 вместо 0.2."

https://doka.guide/js/switch/images/swich-1200w.webp

И в коде и на картинке все в порядке, бага нет, (все брейки на местах и diamond discount = 0.2)
Т.е. надо поправить и код и картинку, убрать в нужном месте break

```javascript

const memberStatus = "diamond"
 
let discount

switch (memberStatus) {
  case "vip":
    discount = 0.25
    break
  case "diamond":
    discount = 0.2
    break // чтобы получить баг этот брейк надо удалить 
  case "gold":
  case "silver":
    // можно написать несколько кейсов и связать с одним блоком
    discount = 0.1
    break
  default:
    discount = 0
    break
}

```

**Comment by nlopin** [comment]
Привет! Принял, поправим 👍
