### ISSUE TITLE
Дока / JavaScript / if...else - На практике / Частый паттерн — значение по умолчанию через ||, но лучше через ??

### ISSUE THREAD

**Issue by saharok** [doka-guide/content#2568]
Здравствуйте, на практике, если использовать современные возможности, *значение по умолчанию* **правильнее** устанавливать через **[оператор нулевого слияния (??)](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)** вместо ||

В отличие от логического ИЛИ (||), левая часть оператора ?? вычисляется и возвращается даже если его результат после приведения к логическому типу оказывается ложным, но не является null или undefined. Другими словами, если вы используете || чтобы установить значение по умолчанию, вы можете столкнуться с неожиданным поведением если считаете некоторые ложные значения пригодными для использования (например, "" или 0). Ниже приведены примеры.

```javascript
const str = null ?? 'строка по умолчанию';
console.log(str);
// ожидаемый вывод: "строка по умолчанию"

const blockWidth = 0 ?? 42;
console.log(blockWidth);
// ожидаемый вывод: 0
```
Т. е. **[оператор объединения с null (??)](https://learn.javascript.ru/nullish-coalescing-operator)** возвращает первый аргумент, если он не null/undefined, иначе второй.

```javascript
let result = a ?? b
// let result = (a !== null && a !== undefined) ? a : b
```

**Comment by nlopin** [comment]
Привет! Спачибо за уточнение. Согласен, что нужно добавить про nullish coalescing. Пришлешь пул реквест? 

Можно удалить этот совет из моего файла и создать свой под своим именем.

**Comment by saharok** [comment]
Привет, попробую разобраться как у вас тут все устроено. Полагаю, потребуется некоторое время. Первое что приходит в голову, дополнить [content/js/if-else/practice/nlopin.md](https://github.com/doka-guide/content/blob/main/js/if-else/practice/nlopin.md)

**Comment by saharok** [comment]
Сделал микроскопическое дополнение к практике с внешними и внутренней ссылками, возможно позже подготовлю полноценную статью про Nullish coalescing operator (??) и Logical nullish assignment (x ??= y) уже под своим авторством
