### ISSUE TITLE
Сделать описания для нового фичеринга

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#2594]
Вот так будет выглядеть новый фичеринг и мы не учли одну штуку: нам нужна либо обложка, либо описание, чтобы карточка смотрелась «взвешенной». Порядок тоже можно расставить. То есть нужно сделать описания для 7 статей:

- [x] css/box-model
- [x] html/doctype
- [x] css/display
- [x] tools/webpack
- [x] html/head
- [x] js/closures
- [x] js/execution-order

![image](https://user-images.githubusercontent.com/105274/146368864-6d735e6d-757c-4ab8-b8cb-dec180f90d0f.png)

**Comment by solarrust** [comment]
Дописала дескрипшены к своим → #2601

**Comment by nlopin** [comment]
Тоже добавил ☝️

**Comment by solarrust** [comment]
Всё сделано и слито. Новый фичеринг на сайте
