### ISSUE TITLE
Некорректное отображение эмоджи в статье `/js/reactivity/`

### ISSUE THREAD

**Issue by monochromer** [doka-guide/content#2644]
По мотивам [issue](https://github.com/doka-guide/platform/issues/842).

Во втором блоке callout эмоджи не отображается корректно.

**Comment by nlopin** [comment]
Кажется уже неактуально

<img width="880" alt="image" src="https://user-images.githubusercontent.com/1469636/151798818-20379c74-815f-438d-98e9-18c4100b9b5f.png">

**Comment by monochromer** [comment]
Вроде без изменений.

Chrome:
![image](https://user-images.githubusercontent.com/6412192/152927506-076c14a2-d0f3-4acf-a458-f964da22146a.png)

Firefox:
![image](https://user-images.githubusercontent.com/6412192/152927520-2e721519-ce0e-47ec-a05c-44bf16b2ae57.png)

**Comment by nlopin** [comment]
На Маке (сафари — хром — firefox):
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/1469636/152936882-2ed98e5e-9c55-4d0e-9634-0ea6d0bb885f.png">

У тебя со скриншоты с винды или линукса?

**Comment by monochromer** [comment]
MacOS Catalina
