### ISSUE TITLE
Добавить атрибут inputmode

### ISSUE THREAD

**Issue by Spearance** [doka-guide/content#2665]

**Comment by solarrust** [comment]
Привет! Спасибо большое, что принёс эту задачку. Нет желания написать доку по этот атрибут?

**Comment by webdb81** [comment]
Добрый день.
Могу написать доку про атрибут inputmode.
Содержание:
1. Краткое описание атрибута.
2. Для чего он нужен.
3. Какие значения используются.
4. Демо с примерами использования.
5. Примечание о поддержке браузерами со ссылкой на caniuse.

**Comment by solarrust** [comment]
@webdb81 супер! Буду очень ждать доку твоего авторства.
Тебе может пригодиться [руководство для авторов](https://github.com/doka-guide/content/blob/main/docs/styleguide.md). Пожалуйста, пиши, если потребуется любая помощь! 🙌
