### ISSUE TITLE
У обложки статьи про область видимости не отображается нужный шрифт

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2688]
На обложке статьи про область видимости для десктопа у надписи на бинокле стоит не тот шрифт (точнее тот, но он не отображается, т. к. не установлен в системе).
https://github.com/doka-guide/content/tree/main/js/closures/images/covers

## Обложка для десктопа<br>(с неправильным шрифтом, т. к. используется `<text>`)
![desktop](https://user-images.githubusercontent.com/21996065/150631853-e6ce2dc5-22e1-4d62-be63-3156ef7b2892.png)

## Обложка для мобильных устройств <br>(с правильным шрифтом, т. к. используется `<path>`)
![mobile](https://user-images.githubusercontent.com/21996065/150631623-b2f56b37-00de-498e-809b-b3c1bf5a0e0d.png)

**Comment by nlopin** [comment]
@furtivite ты пофиксишь?

**Comment by furtivite** [comment]
@nlopin, да, там надо шрифт перегнать в кривые, сорри, что задача повисла.

**Comment by solarrust** [comment]
Актуальная задачка?

**Comment by furtivite** [comment]
@solarrust эта обложка будет переделываться, Кира сказала

**Comment by solarrust** [comment]
Если будут правки в текущей обложке, то задачка актуальна. Если будет полностью новая обложка, то можно задачку закрыть, кмк
