### ISSUE TITLE
Попап

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2733]
Правильный доступный попап с закрытием по клику по оверлею

**Comment by xpleesid** [comment]
Привет! готов сделать

**Comment by solarrust** [comment]
Привет! Круто 🔥
Было бы классно описать реализацию на [`<dialog>`](https://doka.guide/html/dialog/), чтобы по последнему слову техники =)

**Comment by xpleesid** [comment]
@solarrust привет, я почитал доку про <dialog>, в целом этот рецепт пока что выходит как пересказ доки про диалог с достаточно минимальными изменениями. подскажи плиз, что на твой взгляд тут стоит добавить из уникального? я предлагаю сделать статью без <dialog> (но с отсылкой к доке про него), чтобы можно было показать и рассказать в чем сложность создания правильного диалога и какие трудности возникают. ну и добавить что большая часть из этого в диалоге уже поставляется из коробки. но акцент все равно делать на реализацию без него, например, если нам нужно поддерживать IE или вносить изменения в легаси систему, что-то типа того. что думаешь?

**Comment by solarrust** [comment]
Привет!

1. Реализация на `<dialog>`
2. Расположение по центру экрана
3. Стилизация задника
4. Стили для `body` чтобы не прокручивался под попапоп
5. Избежание скачков при открытии/закрытии из-за скроллбара
6. «Ловушка фокуса» в открывшемся попапе
7. Закрытие при клике по оверлею
8. Обмазать это всё доступностью (тут может помочь @TatianaFokina на этапе редактуры)

Смотри как много разных аспектов, выходящих за пределы простого диалога. Можно ещё покрутить это всё, чтобы было классно и на мобильных тоже, там свои особенности.

**Comment by xpleesid** [comment]
@solarrust хорошо, спасибо за наводку!

**Comment by solarrust** [comment]
@xpleesid привет. Ты снял эту задачку с себя. Решил не писать этот рецепт?

**Comment by xpleesid** [comment]
@solarrust привет, что-то в последнее время совсем свободного времени нет, и в ближайшем будущем его появление не предвидится( решил на всякий случай снять, вдруг кто-то решит написать, чтобы не прошли мимо, думая что я над задачей активно работаю. думаю, в случае чего обратно взять никогда не поздно будет)

**Comment by AnnaBaraulina** [comment]
@solarrust привет-привет! Хочу взять! Только быстро не сделаю ск всего ( переезд ), но постараюсь!:)

**Comment by solarrust** [comment]
@AnnaBaraulina супер! Строгого дедлайна нет, пиши в комфортном для тебя темпе.
Если понадобиться любая помощь — дай знать 🙌

**Comment by AnnaBaraulina** [comment]
@solarrust привет! Я наконец смогла отправить пул реквест с драфтом рецепта (готова править и дописывать)! Прошу прощения, что так долго - последний переезд отнял много сил и времени ;(
