### ISSUE TITLE
Прогрессбар загрузки

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2734]
Как сделать прогрессбар загрузки файла

**Comment by webdb81** [comment]
Добрый день.
Могу предложить несложный вариант реализации прогрессбара, если такой вариант подойдёт. 
Подскажите пожалуйста, в каком виде это оформлять - статья или рецепт для какой-то статьи?

**Comment by solarrust** [comment]
Привет!
Это задача для нового раздела «Рецепты». Там мы будем писать туториалы с самым оптимальным решением наиболее частных рабочих задачек. 
Если решишь писать рецепт, то используй ветку _cookbook_, там есть папка _recipes_.
Лучше всего будет сделать полноценную рабочую часть интерфейса от и до: разметка, стили, а самое главное JS который будет вычислять размер файла и заполнять прогрессбар по мере загрузки этого самого файла.

Возьмёшься за эту задачку?

**Comment by solarrust** [comment]
Призову @nlopin чтобы обсудить задачку со всех сторон.

**Comment by nlopin** [comment]
Привет! Интересный кейс, без сервера сложно будет показать. Думаю пока можно сосредоточиться на рассказе, а живое демо обсудим параллельно. 

У мозиллы есть[ описание, как делать прогресс бар](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#handling_the_upload_process_for_a_file), но оно выглядит старовато. Можно взять его за основу, тем более что нового мы там мало что придумаем — `fetch` не поддерживает инфу о загрузке (см. [первый абзац спеки](https://fetch.spec.whatwg.org/#fetch-api)), так что нам в любом случае придется работать с `XMLHttpRequest`. 

Давай не будем использовать `axios` — это внешняя библиотека, а мы пишем максимально ванильный JS.

**Comment by webdb81** [comment]
Добрый день.
Хорошо, спасибо. Пример подготовлю, наверное, в общем виде для обсуждения.

Мои действия, получается, следующие:
- создать папку рецепта (cookbook → recipes → progressbar);
- подпапка _demos_ с демо-файлом;
- файл статьи по принципу ветки контента: с текстом, демонстрацией кода и т.д.

**Comment by solarrust** [comment]
Да, всё так! Можешь поглядывать на лежащий в этой ветке первый рецепт «Снег» чтобы ориентироваться по структуре самой статьи.

**Comment by webdb81** [comment]
Добрый вечер.

Завершаю оформление статьи и демо-файла. В ходе работы получается, что больше подходит название что-то вроде "Загрузка файла с прогресс-баром ?или индикацией?".

Результат работы кода буду показывать с использованием gif-файла. В JS-коде передачу файла делаю с помощью `FileReader()`.

@nlopin, хотел бы узнать ваше мнение по следующим вопросам:
- надо ли делать вариант с `FormData()`;
- нужно ли решение для загрузки нескольких файлов;
- надо ли на стороне клиента делать проверку файлов (тип, размер и т.п.).

**Comment by nlopin** [comment]
Привет!

* вариант с `FormData` самый стандартный, я бы делал его, но готов обсуждать альтернативы, если они качественно лучше
* Думаю не стоит усложнять совет загрузкой нескольких файлов — это усложнит логику
* проверка на тип кажется базовой, если ты про атрибут `accept`. Если ты про парсинг первых байтов, то это кажется перебором. А вот на размер норм, можно впилить

**Comment by webdb81** [comment]
Хорошо, спасибо.
Тогда использую `FormData` вместо `FileReader` и добавлю проверку на размер файла.
