### ISSUE TITLE
Отправка формы без перезагрузки страницы

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2735]
Отправка данных формы при помощи AJAX

**Comment by pa7lux** [comment]
я бы взялся

**Comment by nlopin** [comment]
У нас же есть «[Обработка форм](https://doka.guide/js/deal-with-forms/)» в разделе JS

**Comment by pa7lux** [comment]
Так может эта статья га самом деле — рецепт?

**Comment by nlopin** [comment]
Не совсем, это про подход к работе с формами. Рецепт это же что-то готовое

**Comment by consoleaf** [comment]
Я бы взялся, там какие темы надо затронуть, AJAX, iframe target или и то и то?

**Comment by HellSquirrel** [comment]
@consoleaf 
Давай выберем какой-нибудь самый простой и распространенный способ - при помощи fetch -https://doka.guide/js/fetch/

**Comment by solarrust** [comment]
@consoleaf привет! Как дела с этим материалом? Нужная какая-то помощь?
