### ISSUE TITLE
Драг-н-дроп для загрузки файлов

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2736]
Загрузка файлов при перетаскивании в определённую область

**Comment by webdb81** [comment]
Добрый день.

Готов взяться за этот рецепт.

План действий:

1. Структура статьи (примерно), часть текста и кода — из предыдущего рецепта для загрузки файлов.
2. Использовать `input=file`.
3. Выбор и загрузка одного файла-изображения.
4. Реализация с использованием [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)

Вопросы:

1. Использовать прогресс-бар?
2. Надо ли делать кроссплатформенный вариант? Например, для десктопа — drag'n'drop, для носимых устройств - нажатие в области загрузки. Для этого надо будет проверять поддержку браузером событий перетаскивания.

**Comment by nlopin** [comment]
Привет! 

>  Надо ли делать кроссплатформенный вариант? Например, для десктопа — drag'n'drop, для носимых устройств - нажатие в области загрузки. Для этого надо будет проверять поддержку браузером событий перетаскивания.

Точно стоит рассказать про кроссплатформу. Многим это будет неочевидно.

>   Использовать прогресс-бар?

Давай обойдёмся простым лоадером, чтобы не усложнять реализацию. Но сошлёмся на твою статью о прогресс-баре для тех, кто захочет объединить

**Comment by webdb81** [comment]
В процессе работы над рецептом пришёл к выводу, что нужна статья по событиям перетаскивания и попутно подбирал материал.

Думаю, что можно будет рассказать о каждом событии перетаскивания с небольшим примером для него. Пример, наверное, в виде планировщика задач/канбан доски. Статью разместить в разделе Javascript, название что-то вроде «События перетаскивания». По формату это будет между статьёй и докой. Что скажете?
