### ISSUE TITLE
Дескрипторы у объектов 

### ISSUE THREAD

**Issue by vitaliyirtlach** [doka-guide/content#2748]

**Comment by vitaliyirtlach** [comment]
В дополнению к этой теме не помешало бы добавить такие методы как 
Object.freeze()
Object.isFrozen()

Object.seal()
Object.isSealed()

**Comment by AntonGorelov** [comment]
Добрый вечер!
Если нужно, могу помочь с этой темой.

**Comment by nlopin** [comment]
@AntonGorelov Конечно, буду рад
