### ISSUE TITLE
Дополнить статью SVG ссылками на документацию MDM Web Docs

### ISSUE THREAD

**Issue by parus7** [doka-guide/content#2756]
В issue #2314 "Добавить раздел про svg: теги, свойства, применение"  требуется большая работа. Но эта работа очень объемная и пока она будет сделана пройдет много времени.  В статье содержатся ссылки на статьи Йоксель,  но этого не достаточно. Поэтому предлагаю дополнить статью SVG   ссылками на документацию MDM Web Docs.  Я хотел приложить pool request, но это перебьет ссылки на статьи Йоксель в пометке "На практике" от  solarrust и может получиться конфликт интересов.  Может быть solarrust добавит ссылки в конце самостоятельно. 

Перечень ссылок:

- [SVG.  Документация MDM Web Docs ]( https://developer.mozilla.org/ru/docs/Web/SVG)
- [Справочник SVG элементов ](https://developer.mozilla.org/ru/docs/Web/SVG/Element)
- [Справочник SVG атрибутов ](https://developer.mozilla.org/ru/docs/Web/SVG/Attribute)
- [SVG — учебное руководство ](https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial)

**Comment by solarrust** [comment]
Привет! Отличная идея со ссылками 👍
Мы планируем отдельный раздел под SVG. Но пока его нет надо дать людям возможность добрать недостающую инфу. 
Смело присылай PR с правками. Будет круто, если получится вписать ссылки в текст, а не просто дать списком в конце статьи.
