### ISSUE TITLE
Свойство keyCode у события keydown/keyup устарело

### ISSUE THREAD

**Issue by cergmin** [doka-guide/content#2761]
В [статье про события keydown/keyup](https://doka.guide/js/element-keydown-keyup/) приводятся примеры c свойством keyCode, однако оно является устаревшим: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode. Предлагаю добавить об этом предупреждение.

**Comment by nlopin** [comment]
давай тогда заменим на современное, а про keyCode скажем в калауте
