### ISSUE TITLE
Статья "Области Видимости": опечатка на картинке

### ISSUE THREAD

**Issue by hosaruzu** [doka-guide/content#2805]
В статье [Области видимости](https://doka.guide/js/closures/) опечатка на картинке [2.png](https://github.com/doka-guide/content/blob/main/js/closures/images/2.png):

<img width="1035" alt="Screenshot 2022-02-23 at 07 42 48" src="https://user-images.githubusercontent.com/25340589/155258429-6126b711-11cc-4df0-855a-51f0a93926e3.png">

**Comment by furtivite** [comment]
@hosaruzu спасибо большое, поправим и зальём.
