### ISSUE TITLE
Как применить svg маску в css

### ISSUE THREAD

**Issue by parus7** [doka-guide/content#2841]
Я просмотрел довольно много документации по применению svg для изображений и масок, но там нет описания одного  практического приема, когда svg используется в виде маски. Но эта маска внедряется не в HTML ,   а  в CSS, что для новичков довольно непривычно и неожиданно. Несмотря на то, что это ещё draft & experiment, поддержка браузерами мне понравилась, https://caniuse.com/?search=mask-image  94% .  
Сам прием довольно прост,  используется передача данных в URL через указание mime type данных следующим образом 
```
-webkit-mask-image: url("data:image/svg+xml,<svg ... /svg>);
```
Теперь вопросы:
- Несмотря на неплохую поддержку это все таки ещё не стандарт. Насколько это существенно?
- В doka.guide  статья svg располагается в разделе HTML,  canIuse говорит что это `CSS property: mask-image: SVG masks`, то есть в html разделе этому описанию не место.  По большому счету ему место в подразделе статьи  о `CSS property: mask-image`. В [html/svg](https://doka.guide/html/svg/) достаточно было бы упомянуть о таком приеме и сделать  ссылку на "Свойство mask-image" , но такой статьи пока нет, есть только  Issue #624.  Получаем неопределенность.

Таким образом не понятно как поступить:
1. пока не писать, поскольку преждевременно.
2. Приложить описание к этому issue и пусть здесь лежит до закрытия Issue #624
3. Приложить описание к Issue #624 и пусть ждет своего часа, а это Issue закрыть.
4.  Другие идеи.

**Comment by solarrust** [comment]
Привет!
Мы стараемся описывать только те технологии, которые можно взять и внедрить прямо сейчас с минимальной головной болью о поддержке. 
Твой вопрос про уместный для такой статьи раздел очень актуальный. В следующем квартале мы собираемся запустить отдельный раздел по SVG. Подобная статья вписалась бы туда идеально. 
Давай добавим комментарий к упомянутому тобой ишью про `mask-image` чтобы точно не забыть об этом написать и дождёмся запуска раздела SVG. Как тебе такой план? =)

**Comment by parus7** [comment]
Отличный план. Тогда это issue закрываем, Упоминание там уже  есть, а ещё я добавлю туда комментарий с приложением.

**Comment by solarrust** [comment]
Спасибо большое за твоё желание участвовать в развитии Доки 🤍
