### ISSUE TITLE
Основы работы с ElasticSearch

### ISSUE THREAD

**Issue by Khlebovsky** [doka-guide/content#2872]
Было бы не лишним рассказать про удобную NoSQL поисковую систему ElasticSearch.

Статью напишу в течение апреля.

**Comment by nlopin** [comment]
Привет! Будем ждать 👍 

Обрати внимание на [руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md). Если захочешь обсудить структуру или повествование, то создавай PR в статусе драфт и будем итерироваться в нём
