### ISSUE TITLE
Новый список фичеринга

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2876]
Ниже будет собран список статей, предлагаемых на фичеринг. Нужно будет доделать по ним задачи типа редактуры, обложек, демок. При составлении списков ориентировалась на статистику посещаемости статей. Раз статью читают, то неплохо было бы привести её в порядок.

Жирным в скобках после ссылки выделено то, без чего статья в фичеринг не попадёт. Остальное не является блокером.

### Готовы

- [x] https://doka.guide/html/article/ (есть _редактура_, _дескрипшен_, обложка)
- [x] https://doka.guide/html/img/ (есть _редактура_, обложка, демки, _дескрипшен_)
- [x] https://doka.guide/js/var-let/ (есть обложка, _дескрипшен_, _редактура_)

### HTML

- [ ] https://doka.guide/html/form/ (есть демки, _редактура_, _дескрипшен_, нужна обложка)
- [ ] https://doka.guide/html/nav/ (есть _редактура_, _дескрипшен_, демки, нужна обложка)
- [ ] https://doka.guide/html/section/ (есть _редактура_, _дескрипшен_, нужна обложка)

### CSS

- [ ] https://doka.guide/css/position/ (есть _редактура_, _дескрипшен_, демки, нужна обложка)
- [ ] https://doka.guide/css/attr/ (есть _редактура_, _дескрипшен_, демки, нужны обложка)
- [ ] https://doka.guide/css/media/ (есть _редактура_, _дескрипшен_, нужны обложка, демки)
- [ ] https://doka.guide/css/pseudoelements/ (есть _редактура_, _дескрипшен_, демки, нужна обложка)
- [ ] https://doka.guide/css/specificity/ (есть _дескрипшен_, _редактура_, нужны обложка)

### JS

- [ ] https://doka.guide/js/function/ (есть демки, дескрипшен, редактура, нужна обложка)
- [ ] https://doka.guide/js/function-context/ (есть дескрипшен и редактура, нужна обложка)
- [ ] https://doka.guide/js/infinite-scroll/
- [ ] https://doka.guide/js/oop/ (есть дескрипшен и редактура, нужна обложка)

### TOOLS

- [ ] https://doka.guide/tools/agile/ (есть редактура, дескрипшен, схемы, нужна обложка)
- [ ] https://doka.guide/tools/markdown/ (есть дескрипшен, демки и редактура, нужна обложка)
- [ ] https://doka.guide/tools/network/ (есть схемы, дескрипшен и редактура, нужна обложка)
- [ ] https://doka.guide/tools/bundlers/ (есть редактура, дескрипшен, нужна обложка)
- [ ] https://doka.guide/tools/gitlab-ci-cd/ (есть схемы, дескрипшен, редактура, нужна обложка)

**Comment by skorobaeus** [comment]
До конца этого месяца уложусь.

**Comment by tachisis** [comment]
Моя оценка — 3 недели, тоже до конца месяца.

Если у всех будет примерно так, давайте заводить такой пост в начале каждого месяца?

**Comment by solarrust** [comment]
19.04.2022: обновила список, пометила что у всех статьей теперь есть дескрипшены.

**Comment by skorobaeus** [comment]
Демки готовы.
