### ISSUE TITLE
Не хватает материала о ...

### ISSUE THREAD

**Issue by sabina-99** [doka-guide/content#2894]
### Зачем

- [ ] Я напишу этот материал

**Comment by solarrust** [comment]
Привет. 
Кажется, это задачка была создана случайно. У неё нет темы, в ней не описано, что хотелось бы улучшить в Доке или какого материала нам не хватает.
Пожалуйста, если задача всё же актуально создай её ещё раз и опиши подробнее, какие изменения требуются. 
Спасибо! 🙌
