### ISSUE TITLE
Формулировка в чек-листах к PR

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#2923]
В наших PR есть чеклист, выглядит так:

> ## Чек-лист
> 
> - [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
> - [ ] Ссылки на внутренние материалы абсолютные и заканчиваются слэшем (`/css/color/`, `/tools/json/`)
> - [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)
> 

Из-за пункта про ссылки может возникнуть желание добавить слэш в конце ссылок на якоря, а так якорь работать не будет, а Link Checker будет выдавать ошибку. 

Предлагается изменить формулировку в:

> ## Чек-лист
> 
> - [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
> - [ ] Ссылки на внутренние материалы абсолютные и заканчиваются слэшем (`/css/color/`, `/tools/json/`)
> - [ ] Ссылки на заголовки-якоря во внутренних материалы абсолютные и не заканчиваются слэшем (`/css/color/#podskazki`, `/tools/json/#kak-pishetsya`)
> - [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)
>

**Comment by pepelsbey** [comment]
Вместо расширения чек-листа можно в один из примеров добавить якорь:

> /css/color/ или /tools/json/#id

**Comment by nlopin** [comment]
Согласен с @pepelsbey, так будет нежнее
