### ISSUE TITLE
Не хватает материала о микро и макрозадачах

### ISSUE THREAD

**Issue by corocoto** [doka-guide/content#2938]
## Тема

К сожалению, в справочнике не нашел информации об этом. Хотя тема  микро и макрозадач очень важная, и крайне необходима в процессе изучения.

### Зачем

Микро и макрозадачи принимают непосредственное участие в порядке выполнения кода в разных средах (будь то браузер, или же нода). Понимание процесса выполнения дает четкое осознание того, как устроена/работает та или иная область исполнения кода. 

Эти знания помогут:
* Писать наиболее оптимальные решения (например, в каких случаях лучше применить `queueMicrotask`, а в каких-то `setTimeout`);
* Понимать, почему одна функция будет выполнена после другой (например, функция a выполнится после функции b, так как a - микротаска, b - макротаска);
* С какими проблемами можно столкнуться.

### Дополнительно:

Небольшой раздел про микро и макрозадачи есть в [PR про `queueMicrotask`](https://github.com/doka-guide/content/pull/2915/files#diff-eb11979d20d0335093cb545bf3b60eed144475863e50e9d6298fa04c40c4f0edR54). C @nlopin [договорились, что этот блок остается в доке `queueMicrotask` до тех пор, пока не будет сформирована отдельная статья](https://github.com/doka-guide/content/pull/2915#discussion_r863922559). После чего, его (блок) можно удалить, оставив лишь необходимую ссылку.

- [ ] Я напишу этот материал

**Comment by vitalybaev** [comment]
Вообще это упоминается в статье про асинхронность https://doka.guide/js/async-in-js/
Нужно подумать, стоит ли добавить больше про микро/макро таски туда или же выделить (и как) в отдельную статью

**Comment by nlopin** [comment]
Дублирование не страшно, это статьи не DRY тут не применим. Мне кажется хорошо, если будет отдельная статья по этому вопросу. Это частая тема для обсуждений на собесах 😁

**Comment by G-Milevski** [comment]
Интересная тема. Готов взяться.

 @nlopin  закрепишь ее за мной ?

**Comment by nlopin** [comment]
Да, забирай. 

У нас есть два материала, где эта тема затрагивается:
* [`queueMicrotask()`](https://doka.guide/js/queuemicrotask/)
* [Асинхронность в JS](https://doka.guide/js/async-in-js/#promisy-promise)
 
Обрати на них внимание, пожалуйста. Важно не рассказать разное в трёх разных местах.

**Comment by HellSquirrel** [comment]
Статья ищет своего нового автора :)

**Comment by Realetive** [comment]
@danborisov

**Comment by shumik323** [comment]
Готов взяться могу дополнить про микро и макро задачи, про рендер, про очереди, затронуть аспекты про 16 милисекунд на задчу, про обработку больших задач, про влияние fps и герцовку монитора на event loop.

**Comment by TatianaFokina** [comment]
> Готов взяться могу дополнить про микро и макро задачи, про рендер, про очереди, затронуть аспекты про 16 милисекунд на задчу, про обработку больших задач, про влияние fps и герцовку монитора на event loop.

Круто! Закрепила за тобой.

**Comment by shumik323** [comment]
информация собранна, начинаю офромление )

**Comment by solarrust** [comment]
@shumik323 привет! Как дела с этим материалом? Нужна какая-то помощь?

**Comment by ByMarsel** [comment]
Привет! 

Назначьте на меня, пожалуйста, я бы забрал

**Comment by TatianaFokina** [comment]
> Назначьте на меня, пожалуйста, я бы забрал

Привет, держи!
