### ISSUE TITLE
Ошибка в forEach для Map

### ISSUE THREAD

**Issue by KostinIlia** [doka-guide/content#2939]
https://doka.guide/js/map/#obhod-znacheniy

Приветствую! У вас неверно указан порядок параметров метода for.Each для map и соответственно вывод в консоль у вас неправильный  тоже.  
У вас : `map.forEach((key, value)`.  Должно быть: `map.forEach((value, key)`

Ссылка на документацию:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach

С наилучшими пожеланиями !

**Comment by nlopin** [comment]
Привет! Спасибо за репорт
