### ISSUE TITLE
Ошибка в Link Checker

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#2944]
## Описание

Во время проверки линк чекером на ряде статей появляется ссылка на на неопределённого пользователя: [undefined](https://doka.guide/people/undefined/) — не могу понять, откуда ноги растут. 

### Пруфы

[Link Checker](https://github.com/doka-guide/content/runs/6423107841?check_suite_focus=true)

**Comment by StarHamster** [comment]
@furtivite, вроде поправили в #3812, как считаешь?

**Comment by furtivite** [comment]
@StarHamster привет, ты супер-прав, но почему-то я не закрыл этот issue. Спасибо за твою внимательность и прости за сверх-поздный ответ.
