### ISSUE TITLE
Статья "Использование Web Workers"

### ISSUE THREAD

**Issue by vitaliyirtlach** [doka-guide/content#2956]
## Тема

"Web Worker-ы предоставляют простое средство для запуска скриптов в фоновом потоке" это является мощным инструментом для оптимизации веб приложений

### Зачем

Оптимизация приложений. Кеширование запросов. Notification API и многое другое

- [ ] Я напишу этот материал

**Comment by ivan75238** [comment]
Я забираю

**Comment by solarrust** [comment]
@ivan75238  привет! Как дела с этим материалом? Нужная какая-то помощь?

**Comment by ByMarsel** [comment]
Привет! Я бы хотел забрать эту тему и написать статью на доку? Я правильно понимаю что сейчас никто этим не занимается?

**Comment by ivan75238** [comment]
Привет, да верно. Так и не смог выделить время для написания статьи к сожалению.

**Comment by TatianaFokina** [comment]
> Привет! Я бы хотел забрать эту тему и написать статью на доку? Я правильно понимаю что сейчас никто этим не занимается?

Тогда закрепляю за тобой!
