### ISSUE TITLE
Ошибка в доке про `<blockquote>`

### ISSUE THREAD

**Issue by baradusov** [doka-guide/content#2961]
Ссылка на статью: https://doka.guide/html/blockquote/

## Описание

В статье про цитату написано, что:

> [...] у цитаты может быть свой футер, подвал. Именно в нём принято указывать автора цитаты.

Хотя в спеке написано, что атрибуция должна быть вынесена из blockquote: 

> Attribution for the quotation, if any, must be placed outside the blockquote element.

### Пруфы

https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element
![image](https://user-images.githubusercontent.com/29180060/170117823-8b6968c6-2c3a-4790-883a-4cc3a9870f65.png)

**Comment by solarrust** [comment]
Привет! Спасибо большое, что заметил этот недочёт 🙏
Не хочешь сам поправить формулировку чтобы было верно?

**Comment by baradusov** [comment]
> Не хочешь сам поправить формулировку чтобы было верно?

Ок, на днях сделаю пулл реквест :)
