### ISSUE TITLE
Уточнение в статье про JSON

### ISSUE THREAD

**Issue by bodrovdev** [doka-guide/content#2963]
Ссылка на статью: https://doka.guide/tools/json/

## Описание

Стоит уточнить, какие типы данных и свойства объектов JavaScript метод JSON.stringify() пропускает, а именно:

- Функции
- Свойства-функции объектов
- Значения объектов с **undefined**
- Символьные ключи объектов

![Opera Снимок_2022-05-25_125037_doka guide](https://user-images.githubusercontent.com/79087208/170236269-c3af4e52-6007-4691-8496-ba0981ddaed4.png)

### Пруфы

https://learn.javascript.ru/json#json-stringify

![Opera Снимок_2022-05-25_130633_learn javascript ru](https://user-images.githubusercontent.com/79087208/170237864-0413a069-6211-42a5-9a87-44b84877507d.png)

**Comment by nlopin** [comment]
Привет! Спасибо за такой чёткий репорт. Сможешь добавить сам?
