### ISSUE TITLE
Статьи для нового фичеринга

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2970]
**HTML**

- [ ] https://doka.guide/html/screenreaders/ (есть схемы, _дескрипшен_, нужны **редактура**, обложка)

**CSS**

- [ ] https://doka.guide/css/transform-function/ (есть демки, нужны ~редактура~, ~дескрипшен~, обложка)
- [ ] https://doka.guide/css/keyframes/ (нужны ~редактура~, ~дескрипшен~, обложка)

**JS**

- [ ] https://doka.guide/js/boolean/ (нужны **редактура**, ~дескрипшен~, обложка)
- [ ] https://doka.guide/js/typecasting/ (есть обложка, нужны **редактура**, ~дескрипшен~)

**TOOLS**

- [ ] https://doka.guide/tools/ssl-certificates/ (нужны **редактура**, ~дескрипшен~, обложка)
- [ ] https://doka.guide/tools/microservices/ (есть дескрипшен, схемы, нужны **редактура**, обложка)

**Comment by solarrust** [comment]
@nlopin Закинешь статьи в новый фичеринг? Те, что с редактурой

**Comment by nlopin** [comment]
Не понял, что ты имеешь ввиду?

**Comment by solarrust** [comment]
Добавить статьи, которые готовы для фичеринга, в файл _settings/featured.md_
