### ISSUE TITLE
Что такое Доступность

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2978]
Статья о:
- что такое Доступность в глобальном смысле, 
- в вебе конкретно, 
- какими инструментами достигается, 
- какие плюсы, минусы, подводные камни, 
- перспективы развития, 
- юридические документы и требования

**Comment by TatianaFokina** [comment]
Ещё было бы полезно, например, после «Доступность в глобальном смысле» разобраться с тем, чем доступность отличается от юзабилити, инклюзии, UX, универсального дизайна. Провести границы между разными подходами. Кажется важным. Часто, например, встречается идея, что раз доступно, то и с юзабилити всё хорошо. Но это не так.

**Comment by solarrust** [comment]
Just in case: если захочется собрать платформу локально, то там нужно переключиться на ветку с таким же названием.

**Comment by solarrust** [comment]
Friendly reminder 🌚
