### ISSUE TITLE
Уровни доступности

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2979]
Рассказ про уровни доступности.

- Что такое, как связаны с WCAG 2.
- Где и для чего нужны: аудит доступности, соответствие требованиям законов о доступности.
- Какие примерные изменения будут с уровнями во WCAG 3.

## Ссылки для старта

- https://www.w3.org/WAI/standards-guidelines/wcag/wcag3-intro/#structure
- https://www.w3.org/TR/WCAG22/#cc1
- https://ifap.ru/ictdis/wcag.htm#521
- https://web-standards.ru/articles/wcag3-changes/#section-6
- https://web-standards.ru/articles/a11y-audit-basics/

**Comment by skorobaeus** [comment]
Добавлю формулировку, в которой я гуглила: "что такое AAA и AA доступность"
