### ISSUE TITLE
Введение в ARIA

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2983]
- Что это такое
- Как надо использовать
- Когда не надо использовать

**Comment by TatianaFokina** [comment]
Готова взяться.

**Comment by solarrust** [comment]
@TatianaFokina — неутомимый автор! Закрепила задачку за тобой ♥️

**Comment by TatianaFokina** [comment]
@solarrust, у меня возник вопрос про демки. Уже есть идеи, какие цвета будут использоваться для раздела про доступность?  Какие цвета мне использовать, если нет?

**Comment by solarrust** [comment]
Хороший вопрос. Если мне не изменяет память, то пока новый цвет не подбирали. Призываю @skorobaeus для точного ответа.

**Comment by skorobaeus** [comment]
Привет!

Мы подобрали цвет для раздела о доступности: аквамариновый `#10F3AF`. Если потребуется ещё один цвет, то в пару к нему подойдет розовый `#F498AD`.

![доступность-демо](https://user-images.githubusercontent.com/29401439/184120094-9342d216-051b-4f80-899c-995b0d999308.png)
