### ISSUE TITLE
Основы доступного HTML

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2984]
Собрать самые базовые рекомендации по доступной разметке. К примеру, можно рассказать про:

- Как HTML помогает вспомогательным технологиям.
- Почему семантическая вёрстка лучше ARIA.
- Что есть у тегов по умолчанию: роли, состояния, свойства (хорошо видно на примере `<dialog>`).
- Почему круто использовать текстовое содержимое тегов в качестве имён.
- Плохие практики в HTML. К примеру, почему не стоит использовать в `<meta>` атрибуты `user-scalable=no` или `maximum-scale=1`, как это влияет на доступность.
- Иногда фичи из HTML не работают как надо. Всё надо проверять и тестить. Например, `<details>`, `<video>`, `<dialog>`.

## Ссылки для старта

- https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML
- https://web.dev/learn/html/semantic-html/
- https://tetralogical.com/blog/2022/10/05/foundations-html-semantics/
- https://www.tempertemper.net/blog/html-isnt-quite-accessible-out-of-the-box
- https://russmaxdesign.github.io/accessible-forms/

**Comment by imeugenia** [comment]
Привет! Я бы хотела взяться за написание этой статьи. 

Это будет первый опыт на русском, но до этого я писала [статьи на английском](https://medium.com/@imeugenia) и была автором в [Web Almanac](https://almanac.httparchive.org/en/2022/third-parties). 

@solarrust нужно ли мне ждать подтверждения, что могу начать?

**Comment by solarrust** [comment]
Привет! Можешь смело начинать. Задачку закреплю за тобой 🫶
