### ISSUE TITLE
Skip link

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2985]
- Что это
- Зачем нужно
- Лучший вариант реализации

**Comment by xpleesid** [comment]
Привет! Готов сделать

**Comment by TatianaFokina** [comment]
> Привет! Готов сделать

Привет, замечательно! Пиши, если нужна будет помощь.

Пара полезных ссылок:
- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).

Пока раздел скрыт, так что используй веточку `new-section/a11y`.

Основной цвет для демок — #10F3AF (аквамариновый). Дополнительный цвет — #F498AD (розовый).
