### ISSUE TITLE
`forced-colors`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2987]
В доке можете рассказать про то, для чего нужно это медиа-выражение, разобрать его значения, привести пример кода (будет круто, если сделаете ещё и демку).

Здесь также можно упомянуть про устаревшую медиафичу `ms-high-contrast` и рассказать, когда она может понадобиться.

Ссылки для старта:

- https://drafts.csswg.org/mediaqueries-5/#forced-colors
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors
- https://polypane.app/blog/forced-colors-explained-a-practical-guide/
- https://tatiana-fokina-blog.ru/posts/css-media-features-for-a11y/
- https://doka.guide/css/media/

Полезные ссылки по тексту и демкам в Доке:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

Для этой доки уже готов плейсхолдер. Это просто черновик материала. Можете дополнить его или переписать всё с нуля 🐶

**Comment by TatianaFokina** [comment]
Здесь же можно упомянуть про устаревшую медиафичу `ms-high-contrast` и рассказать, когда она может понадобиться.
