### ISSUE TITLE
Влияние CSS на Доступность

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2990]
## Тема

Рассказать про то, что хоть CSS и про представление, он может влиять на доступность.

## Примерный план
- `list-style: none`.
- `display: none`.
- `display: table`.
- `visibility: hidden`.
- `width: 0` + `height: 0`.
- `::before`, `::after` и `::marker`.
- `text-transform: uppercase`.
- `order` (подсветить, что порядок для скринридеров не меняет).

## Ссылки для старта
- https://benmyers.dev/blog/css-can-influence-screenreaders/
- https://uselessdivs.com/blog/the-effect-of-css-on-screen-readers/
- https://html5accessibility.com/stuff/2021/11/04/super-short-note-on-css-text-again/
- https://moderncss.dev/modern-css-upgrades-to-improve-accessibility/
- https://webaim.org/search/?q=CSS
- https://web.dev/state-of-css-2022

**Comment by IPogorelova** [comment]
Привет!

Хотела бы попробовать взяться, но смогу начать только через 1-2 недели. Если это ок, то с удовольствием впишусь :)

**Comment by TatianaFokina** [comment]
> Привет!
> 
> Хотела бы попробовать взяться, но смогу начать только через 1-2 недели. Если это ок, то с удовольствием впишусь :)

Привет! Звучит отлично 🙂 Пиши, если нужна будет помощь.

Пара полезных ссылок:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).

Пока раздел скрыт, так что используй веточку `new-section/a11y`.

Основной цвет для демок — #10F3AF (аквамариновый). Дополнительный цвет — #F498AD (розовый).

**Comment by TatianaFokina** [comment]
@IPogorelova, раздел уже есть на сайте, так что совет про отдельную ветку под доступность не актуален.
