### ISSUE TITLE
Доступные формы

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2992]
Рассказать про общие принципы создания доступных форм. Что делать обязательно, что желательно, а чего точно не нужно делать. Разобрать разные контролы, явные и скрытые лейблы, aria-атрибуты. Правильную валидацию формы.

**Comment by OskarStud** [comment]
Готов взять

**Comment by solarrust** [comment]
@OskarStud привет! Как дела? Могу я чем-то помочь?

**Comment by OskarStud** [comment]
@solarrust Привет! Все супер, спасибо. До конца июня 2023 доделаю.
