### ISSUE TITLE
Голосовое управление

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#2998]
## Тема

Голосовое управление

- Что это такое, примеры.
- Кто им пользуется.
- Как работают.
- Как тестировать.

### Зачем

Голосовое управление тоже стоит учитывать при разработке сайтов. И это напрямую связано с доступностью, так как часть пользователей с разными состояниями опорно-двигательного аппарата навигаруются по сайтам с помощью голосовых команд.

## Ссылки для старта

- [Designing and Coding for Voice](https://www.briandeconinck.com/designing-coding-voice/).
- [Browsing with speech recognition](https://tetralogical.com/blog/2021/11/15/browsing-with-speech-recognition/).

## Полезные ссылки по тексту и демкам в Доке

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

**Comment by VishniakovaAlina** [comment]
Готова взять

**Comment by TatianaFokina** [comment]
@VishniakovaAlina, привет! 👋 Собираешься писать материал? Может быть нужна наша помощь?
