### ISSUE TITLE
aria-роли

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#3003]
## Тема

aria-роли

Можно написать про модель ролей в WAI-ARIA. В целом про то, что бывают явные и неявные роли, про другие типы, про правила использования и перечислить и кратко описать существующие роли из спеки.

### Зачем

Уже есть ишью про aria-атрибуты, так что не хватает ролей. Кажется, что такая ишью уже была, но я не смогла её найти.

**Comment by TatianaFokina** [comment]
Я бы тоже взялась, у меня набрался материал на эту тему. Но я бы написала статью по типу статьи про [`@media`](https://doka.guide/css/media/), так как для того, чтобы быть докой, она слишком обзорная и разводная. По крайней мере, мне кажется, что так будет лучше поступить.

Будет краткое описание типов ролей, выпадающие списки со всеми значениями с супер краткой характеристикой, а ещё базовые правила использования `role=""`.

**Comment by solarrust** [comment]
Звучит как отличный план. Потом напишем по каждой отдельной роли свою доку и сможем ссылаться на них из это обзорной статьи 👍
