### ISSUE TITLE
Не получается запустить проект. Ругается [11ty] HttpError

### ISSUE THREAD

**Issue by BernarBerdikul** [doka-guide/content#3018]
Стянул себе проект, попробовал запустить (Macbook M1) и столкнулся с этой ошибкой. Подскажите пожалуйста как её решить

<img width="917" alt="Screen Shot 2022-06-06 at 19 24 00" src="https://user-images.githubusercontent.com/61005409/172172997-af1ea832-3a93-4a6e-956f-810344b99d4d.png">

**Comment by furtivite** [comment]
@BernarBerdikul привет, нужно завести себе токен для работы с GraphQL на гитхабе. Вот [инструкция](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). Мы пишем об этом [в документации платформы](https://github.com/doka-guide/platform/blob/main/docs/how-to-run.md#запуск-с-реальным-контентом).

Если не получится, приходи с вопросами, поможем)
