### ISSUE TITLE
`aria-disabled`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3021]
В доке можете рассказать про то, для чего нужен этот атрибут, есть ли аналог в HTML, привести пример кода (будет круто, если сделаете ещё и демку), каким тегам и ролям можно его задавать, какие есть особенности и подводные камни.

Не забудьте упомянуть, что `aria-disabled` можно задавать ссылкам без `href`.

Ссылки для старта:

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled
- https://www.w3.org/TR/wai-aria-1.2/#aria-disabled
- https://a11y-101.com/development/aria-disabled
- https://css-tricks.com/making-disabled-buttons-more-inclusive/
- https://doka.guide/html/disabled/
- https://doka.guide/a11y/aria-attrs/
- https://a11ysupport.io/

Полезные ссылки по тексту и демкам в Доке:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

Для этой доки уже готов плейсхолдер. Это просто черновик материала. Можете дополнить его или переписать всё с нуля 🐶

**Comment by teplostanski** [comment]
Готов взять!

**Comment by TatianaFokina** [comment]
> Готов взять!

Е-е-е-е, закрепила за тобой.

**Comment by teplostanski** [comment]
а демку в код вставить или куда то залить нужно?

**Comment by TatianaFokina** [comment]
> а демку в статью кодом вставить или куда то залить нужно?

Мы держим демки локально, в одном файле _index.html_. Можно заглянуть [в пример про тег `<b>`](https://github.com/doka-guide/content/tree/main/html/b/demos/view).

**Comment by teplostanski** [comment]
хорошо, а если несколько демок? есть ли рекомендации по неймингу html файлов?

**Comment by TatianaFokina** [comment]
> хорошо, а если несколько демок? есть ли рекомендации по неймингу html файлов?

В этом случае закидываешь в _demos_ отдельную папку под каждую демку. Например, _bad-example_ и _good-example_. А в самой статье указываешь путь к нужной папке.

```md
Не делайте так:

<iframe title="Плохой пример" src="demos/bad-example/" height="300"></iframe>

Делайте так:

<iframe title="Хороший пример" src="demos/good-example/" height="400"></iframe>
```

**Comment by teplostanski** [comment]
PR [#5345](https://github.com/doka-guide/content/pull/5345)
