### ISSUE TITLE
`aria-live`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3044]
В доке можете рассказать про то, для чего нужен этот атрибут, есть ли аналог в HTML, привести пример кода (будет круто, если сделаете ещё и демку), каким тегам и ролям можно его задавать, какие есть особенности и подводные камни.

Ссылки для старта:

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live
- https://www.w3.org/TR/wai-aria-1.2/#aria-live
- https://gomakethings.com/how-and-why-to-use-aria-live/
- https://dequeuniversity.com/library/aria/liveregion-playground
- https://web.dev/hiding-and-updating-content/
- https://web-standards.ru/articles/aria-live-regions/
- https://doka.guide/a11y/aria-attrs/
- https://a11ysupport.io/

Полезные ссылки по тексту и демкам в Доке:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

Для этой доки уже готов плейсхолдер. Это просто черновик материала. Можете дополнить его или переписать всё с нуля 🐶

**Comment by Kirrrusha** [comment]
Готов взять тему

**Comment by Kirrrusha** [comment]
Коллеги, статья уже есть https://doka.guide/a11y/aria-live/

**Comment by TatianaFokina** [comment]
@Kirrrusha, привет! 👋 Собираешься писать материал? Может быть нужна наша помощь?

**Comment by TatianaFokina** [comment]
@Kirrrusha, снимаю с тебя задачку. Если найдёшь время и силы, заходи 🐶

**Comment by OskarStud** [comment]
@TatianaFokina Привет. Можно попробовать взять описание aria-live? 
Также на [данной странице](https://web-standards.ru/articles/aria-live-regions/) уже частично есть информация от вас по поводу aria-live, можно ли использовать эту информацию?

**Comment by TatianaFokina** [comment]
> @TatianaFokina Привет. Можно попробовать взять описание aria-live? Также на [данной странице](https://web-standards.ru/articles/aria-live-regions/) уже частично есть информация от вас по поводу aria-live, можно ли использовать эту информацию?

Конечно можно! И можно использовать ту инфу, что по ссылке.

**Comment by OskarStud** [comment]
Пишу пишу. Хотел сделать PR. Но решил попробовать добавить демку.
