### ISSUE TITLE
`aria-atomic`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3046]
В доке можете рассказать про то, для чего нужен этот атрибут, есть ли аналог в HTML, привести пример кода (будет круто, если сделаете ещё и демку), каким тегам и ролям можно его задавать, какие есть особенности и подводные камни.

Ссылки для старта:

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-atomic
- https://www.w3.org/TR/wai-aria-1.2/#aria-atomic
- https://dequeuniversity.com/library/aria/liveregion-playground
- https://web.dev/hiding-and-updating-content/
- https://web-standards.ru/articles/aria-live-regions/
- https://doka.guide/a11y/aria-attrs/
- https://a11ysupport.io/

Полезные ссылки по тексту и демкам в Доке:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

Для этой доки уже готов плейсхолдер. Это просто черновик материала. Можете дополнить его или переписать всё с нуля 🐶

**Comment by Progpogod** [comment]
Постараюсь написать!)

**Comment by solarrust** [comment]
Мы поможем =)

**Comment by TatianaFokina** [comment]
@Progpogod, привет! 👋 Собираешься писать материал? Может быть нужна наша помощь?

**Comment by Progpogod** [comment]
@TatianaFokina, привет! Да, были небольшие трудности (заканчивал ВУЗ), напишу)

**Comment by TatianaFokina** [comment]
@Progpogod, привет! Всё ещё планируешь писать эту доку?

**Comment by TatianaFokina** [comment]
@Progpogod, пока откреплю задачку, но ты возвращайся, если что 🐶
