### ISSUE TITLE
aria-роль `alert`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3073]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role
- https://w3c.github.io/aria/#alert
- https://www.w3.org/WAI/ARIA/apg/patterns/alert/examples/alert/
- https://web-standards.ru/articles/aria-live-regions/

**Comment by aleksanderlamkov** [comment]
Готов взять :)

**Comment by aleksanderlamkov** [comment]
@TatianaFokina я правильно понимаю, что речь идёт о незавершенной статье https://doka.guide/a11y/role-alert/?

**Comment by TatianaFokina** [comment]
> @TatianaFokina я правильно понимаю, что речь идёт о незавершенной статье https://doka.guide/a11y/role-alert/?

Ага! Текст можно вообще полностью переписать или дополнить его.
