### ISSUE TITLE
aria-роль `alertdialog`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3110]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role
- https://w3c.github.io/aria/#alertdialog

**Comment by AgarkovRoman** [comment]
эту тоже могу взять, так как она схожа с #3125

**Comment by TatianaFokina** [comment]
> AgarkovRoman

Круто, бери!
