### ISSUE TITLE
aria-роль `button`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3114]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
- https://w3c.github.io/aria/#button

**Comment by jkorichneva** [comment]
Привет, хочу попробовать взять этот issue для старта. Можно его закрепить за мной? 😸

**Comment by TatianaFokina** [comment]
> Привет, хочу попробовать взять этот issue для старта. Можно его закрепить за мной? 😸

Привет! Очень круто, закрепила.
