### ISSUE TITLE
aria-роль `dialog`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3125]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role
- https://w3c.github.io/aria/#dialog

**Comment by AgarkovRoman** [comment]
привет, могу взяться 👨🏻‍💻

**Comment by TatianaFokina** [comment]
> привет, могу взяться 👨🏻‍💻

Привет! Круто, закреплю задачку за тобой.
