### ISSUE TITLE
aria-роль `mark`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3144]
В доке можете рассказать про то, для чего нужна эта роль, у какого HTML-тега она есть по умолчанию, привести пример кода (будет круто, если сделаете ещё и демку), какие ARIA-свойства можно использовать и для чего, какие есть особенности и подводные камни.

Роль новая, так что что-то может поменяться чуть позже 🚧

Ссылки для старта:

- https://w3c.github.io/aria/#mark
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/mark_role
- https://www.tpgi.com/screen-readers-support-for-text-level-html-semantics/
- https://doka.guide/html/mark/
- https://doka.guide/a11y/aria-roles/
- https://a11ysupport.io

Полезные ссылки по тексту и демкам в Доке:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

Для этой доки уже готов плейсхолдер. Это просто черновик материала. Можете дополнить его или переписать всё с нуля 🐶

**Comment by bellabzhu** [comment]
Хочу взять задачу
