### ISSUE TITLE
aria-роль `navigation`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3153]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role
- https://w3c.github.io/aria/#navigation

**Comment by katokdoescode** [comment]
Привет @solarrust, хотел бы взять в работу

**Comment by solarrust** [comment]
Привет! Без проблем, передам @TatianaFokina, которая у нас редактор раздела =)
Закрепила задачку за тобой. Пиши если нужна будет любая помощь!

**Comment by TatianaFokina** [comment]
> Привет @solarrust, хотел бы взять в работу

Привет, да, очень круто.

Пока в документации нет цветов раздела. Если что, то основной цвет для демок — #10F3AF (аквамариновый), а дополнительный цвет — #F498AD (розовый).

**Comment by katokdoescode** [comment]
> Пока в документации нет цветов раздела. Если что, то основной цвет для демок — #10F3AF (аквамариновый), а дополнительный цвет — #F498AD (розовый).

Спасибо. Ознакомлюсь со стайлгайдом и приступлю.
