### ISSUE TITLE
aria-роль none

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3154]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/none_role
- https://w3c.github.io/aria/#none

**Comment by TatianaFokina** [comment]
Предлагаю объединить `none` в одну доку с `presentation` (#3157). Это синонимы, придётся дублировать в двух доках инфу.

**Comment by TatianaFokina** [comment]
Закрою это ишью, так как лучше написать в одной доке про `presentation` и `none`.
