### ISSUE TITLE
aria-роли presentation, none

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3157]
Источники:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role
- https://w3c.github.io/aria/#presentation
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/none_role
- https://w3c.github.io/aria/#none

**Comment by TatianaFokina** [comment]
Готова начать осваивать формат док :)
