### ISSUE TITLE
Что может читать сайт, кроме пользователя?

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#321]
Рассказать про скрин ридер, роботов поисковиков

**Comment by igsekor** [comment]
Если никто не против, беру в работу. @nlopin

**Comment by nlopin** [comment]
погоди, давай приоритеты обсудим. мне эта таска кажется вообще малонужной, лучше джуну рассказать про работу с терминалом

**Comment by igsekor** [comment]
Давай.
