### ISSUE TITLE
Live Regions

### ISSUE THREAD

**Issue by glafirazhur** [doka-guide/content#3229]
## Тема

В статье рассмотреть:

- что такое live regions;
- как они работают;
- когда их надо использовать;
- залинковать на статьи про `aria-live`, `aria-busy`, `aria-atomic`, `aria-relevant`, `alert`, `status`, `marquee`, `log`, `progressbar`, `timer`.

### Зачем

Эта тема в последнее время особенно часто поднимается, потому что многие элементы интерфейса обновляются автоматически, но у пользователя нет об этом никакой информации. Тут как раз помогают live regions. Динамический поиск по сайту, количество опций при автокомплите, фильтрация товаров в каталоге, появление срочной информации (алертов) и т. д.

## Ссылки для старта

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
- https://dequeuniversity.com/library/aria/liveregion-playground
- https://web-standards.ru/articles/aria-live-regions/

## Полезные ссылки по тексту и демкам в Доке

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

**Comment by MargaritaKozyreva** [comment]
Беру себе

**Comment by TatianaFokina** [comment]
@MargaritaKozyreva, привет! 👋 Собираешься писать материал? Может быть нужна наша помощь?

**Comment by TatianaFokina** [comment]
@MargaritaKozyreva, откреплю задачку. Если будет время, силы и желание, можешь снова взяться за неё или что-то другое.
