### ISSUE TITLE
Ошибка в css/:not

### ISSUE THREAD

**Issue by artur-demidov** [doka-guide/content#3250]
Ссылка на статью: [:not()](https://doka.guide/css/not/#kak-pishetsya)

## Описание

> Важно помнить, что внутри скобок не может быть составного селектора!
> Например, вот такая конструкция не сработает вообще: a:not(.link a) 😞

Вроде это не так.

### Пруфы

[Демка](https://codesandbox.io/s/mutable-shadow-2euo4c) - работает в последнем chrome, safari, ff. В ней :not() содержит в себе сложный селектор `.card > .text`

[MDN eng версия](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) пишет
> syntax :not( \<complex-selector-list\> )

Идем в [спеку](https://drafts.csswg.org/selectors/#negation), тут пишут

> The negation pseudo-class, :not(), is a functional pseudo-class taking a [selector list](https://drafts.csswg.org/selectors/#selector-list) as an argument.

Дальше нужна помощь человека который понимает как "расшифровать спецификацию".

Как я понял, если в спеке указан `selector list` без уточнения типа, то он является [list of complex selectors](https://drafts.csswg.org/selectors/#list-of-simple-selectors) по дефолту(как и пишет MDN).

Если пытаться понять что такое `list of complex selectors` то получается что это "перечисленные через запятую селекторы, которые могут содержать в себе комбинаторы(пробел, ~, +, \>)"

P.S. надеюсь понятно объяснил😊

**Comment by solarrust** [comment]
Очень понятно объяснил, спасибо большое! 
Обожаю CSS, каждый день что-то новое =)
Присылай пул-реквест с уточнением. Я бы даже демку добавила, чтобы показать, как работают аргументы с комбинированными селекторами или с перечислением селекторов 👍

**Comment by artur-demidov** [comment]
Добавлю PR👍

**Comment by SelenIT** [comment]
Такое ограничение действительно было в спецификации 3 уровня. В нынешней спецификации 4 уровня его убрали. На canIUse есть [отдельная табличка ](https://caniuse.com/?search=%3Anot())для новой редакции (например, IE9-11 понимали `:not()` только «по старому стилю», с одним простым селектором). Может быть, есть смысл оставить упоминание в виде исторического примечания.
