### ISSUE TITLE
Ошибка в Специфичность

### ISSUE THREAD

**Issue by artur-demidov** [doka-guide/content#3251]
Ссылка на статью: [Специфичность](https://doka.guide/css/specificity/#ves-selektorov)

## Описание

> Комбинаторы `+`, `>`, `~`, универсальный селектор `*` и псевдокласс `:not()` веса не имеют.

Если сравнивать `:not()` с `:hover`, то `:not()` не имеет веса, но формулировка не столь правильная. Он не имеет веса сам по себе, а выбирает самый сильный вес из аргументов и применяет его. + по такой же логике тут должен быть `:is()` и `:where()`.

Не знаю как правильно "разжевать" и изложить, но считаю стоит указать что:

- псевдоклассы `:not()` и `:is()` имеют вес самого специфичного селектора из перечисленных в аргументах(скобках)
- универсальный селектор `*` и `:where()` - имеют нулевой вес, вне зависимости от аргументов в случае с `:where()`
- комбинаторы `+`, `>`, `~`, `пробел` не добавляют веса к селектору

Примерно так

### Пруфы

[css-specificity-calculator](https://polypane.app/css-specificity-calculator/)

[Дока :where](https://doka.guide/css/where/)
> Различие заключается в специфичности у :where() она нулевая, а у :is() равна наиболее специфичному из переданных селекторов.

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) - взять бы тут целый блок, перевести и кратко пересказать
> No value
The universal selector ([*](https://developer.mozilla.org/en-US/docs/Web/CSS/Universal_selectors)) and the pseudo-class [:where()](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) and its parameters aren't counted when calculating the weight, but they do match elements. The value for both the universal selector and the pseudo-class is 0-0-0; these selectors do not impact the specificity weight value.

> Combinators, such as [+](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator), [>](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator), [~](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator), [" "](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator), and [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Column_combinator), may make a selector more specific in what is selected but they don't add any value to the specificity weight.

> The negation pseudo-class, [:not()](https://developer.mozilla.org/en-US/docs/Web/CSS/:not), itself has no weight. Neither does the [:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) pseudo-class. The parameters in these selectors, however, do. The values of both come from the parameter in the list of parameters that has the highest specificity. The [:not() and :is() exceptions](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the-is-and-not-exceptions) are discussed below.

**Comment by solarrust** [comment]
Эта информация отлично дополнит доку про специфичность. Пришлёшь пул-реквест?
Я бы добавила в список в разделе «Вес селекторов» пункт про `:not()` и `:is()`. А про `:where()` добавил бы в предложение под списком, вместо `:not()`.

**Comment by artur-demidov** [comment]
Скину PR. По оформлению уже в обсуждении PR
