### ISSUE TITLE
Ошибка в Гайд по флексбокс

### ISSUE THREAD

**Issue by e-astapkovich** [doka-guide/content#3277]
Ссылка на статью:
[Гайд по flexbox](https://doka.guide/css/flexbox-guide/#order)
[Order](https://doka.guide/css/order/#kak-pishetsya)

## Описание

Кажется, на картинке, демонстрирующей работу свойства order, не правильно расположены элементы.
У элементов №2 и №5 свойство order не задано, т.е. по умолчанию равно 0.
У элемента №4 свойство order задано и равно 1.
Элементы встают по возрастанию значения свойства order.
Значит элементы №2 и №5 (order: 0) должны располагаться раньше элемента №4 (order: 1)
А на картинке сначала идет элемент №4 (order: 1), а после него элементы №2 и №5 (order: 0)

Если я прав, то вот готовая исправленная картинка (PNG, 1440 x 832, 16kb):
https://disk.yandex.ru/i/LqtNdm0lizfqhw

Если же, это просто я не до конца разобрался в теме, то извините за беспокойство!
Но ниже ссылка на кодпен, где я экспериментировал с эти свойством и постарался воспроизвести ситуацию, показанную на картинке.

### Пруфы

https://codepen.io/Astapkovich/pen/rNdeVrb

**Comment by skorobaeus** [comment]
Вы правы! Большое спасибо за наблюдательность :)
