### ISSUE TITLE
Дока `preventDefault`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#3338]
Рассказать, как предотвращать поведение по умолчанию при обработке событий

**Comment by G-Milevski** [comment]
Привет, готов написать статью. Мне надо приблизительно неделя.

**Comment by nlopin** [comment]
Привет! Конечно, забирай.

Так как это дока, то нужно выдержать [структуру доки](https://github.com/doka-guide/content/blob/main/docs/examples/doka.md).

Тебе так же может пригодиться [гид по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
