### ISSUE TITLE
data-атрибуты

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3360]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

**Comment by solarrust** [comment]
@TatianaFokina хочу посоветоваться, нужна ли нам краткая статья про дата-атрибуты в HTML? А внутри неё сослаться на более подробную статью в a11y. Или это будет странно и слегка похоже на раздвоение личности? 🤔

**Comment by TatianaFokina** [comment]
> @TatianaFokina хочу посоветоваться, нужна ли нам краткая статья про дата-атрибуты в HTML? А внутри неё сослаться на более подробную статью в a11y. Или это будет странно и слегка похоже на раздвоение личности? 🤔

Мне казалось, что они больше про манипуляцию DOM и JS. И такая чисто HTML-штука, которая не то, чтобы сильно связана с доступностью. Так что вполне себе подходит для раздела про HTML.

Но можно упомянуть об `aria` как глобальном атрибуте, наверное. Что-то супер-краткое, чтобы был доступ и из раздела про HTML.

**Comment by KrAnatoly** [comment]
Возьму в работу

**Comment by solarrust** [comment]
@KrAnatoly привет! Нужна ли какая-то помощь с написанием?

**Comment by KrAnatoly** [comment]
@solarrust привет. Помощь не нужна, только если с недостатком времени летом) 
Пока, к сожалению, не успеваю, но в ближайшее время напишу.
