### ISSUE TITLE
Ошибка в демке статьи JSON

### ISSUE THREAD

**Issue by rx1310** [doka-guide/content#3436]
Ссылка на статью: https://doka.guide/tools/json/#primer-preobrazovaniya-obekta-javascript-v-format-json

## Описание

На мобильной версии версии сайта при просмотре демки первый блок с примером кода до перевода JS в формат JSON не отображается полностью, а торчит немного из левого края, как на скриншоте снизу:

![IMG_20220802_192336.png](https://user-images.githubusercontent.com/33829769/182424708-53e5766e-6976-4fb0-82af-ab29f7c5fa72.png)

_Я подметил положение скролл бара (синяя полосочка) для убедительности в том, что я нормально и ровными руками скролил влево (хотя было бы странно, если бы демка изначально начиналась справа)._

### Пруфы

Нет 😐

> P.S. Блин, я забыл указать, что все это дело на мобильном Chrome 100+ (а точнее 103.0.5060.129) для Android (в моем случае это версия 12). Ну мало ли инфа понадобится.

**Comment by nlopin** [comment]
Спасибо за репорт! Подлатаем

**Comment by rx1310** [comment]
Блин, я забыл указать, что все это дело на мобильном Chrome 100+ (а точнее 103.0.5060.129) для Android (в моем случае это версия 12). Ну мало ли инфа понадобится.
