### ISSUE TITLE
Обновить док про контрибьютинг

### ISSUE THREAD

**Issue by tachisis** [doka-guide/content#346]
Он изрядно устарел.

**Comment by tachisis** [comment]
@pepelsbey а есть ли у нас тут какие-то подвижки?

**Comment by pepelsbey** [comment]
Пока нет 😥 Возьмусь после переезда на новый домен

**Comment by solarrust** [comment]
Кажется, сейчас там всё ок. @pepelsbey @tachisis что-то нужно ещё исправить?

**Comment by pepelsbey** [comment]
Думаю это уже забытая задача, проще закрыть 😅
