### ISSUE TITLE
Продумать систему заголовков и вывод оглавления

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#348]
- Нормализовать существующие заголовки
- Продумать группировку материалов при выводе в оглавлении
- Придумать систему создания заголовков

**Comment by tachisis** [comment]
Я долго думала, и предлагаю вот что. У нас совершенно очевидно есть материалы об общих концепциях, а есть о конкретных штуках (тегах, свойствах, методах). Статей много и будет еще больше, и нам необходимы подразделы. Я вижу их примерно так:

- Основы (сюда идут статьи типа CSS-правило, Поток документа, Как браузер рисует страницы, Системы управления версиями)
- Конкретика — этот раздел или разделы будут называться по-разному в зависимости от темы (Теги в HTML, Свойства в CSS, Методы в JS, Инструмент такой-то в Инфраструктуре, ну вы поняли).
- Какие-то специфические разделы типа Гайды.

И мой главный инновационный пойнт — **избавиться от деления на Справочник и Лонгриды**. Сделать оглавление по смыслу, а на то, что перед нами лонгрид, указывать, например, иконкой. Так читателю будет проще найти материалы по теме, не мотаясь между разнесенными на расстоянии блоками.

Теперь о заголовках и структурировании информации вообще.

- Предлагаю стремиться к структуре «одна штука — один материал», и называть по имени штуки. Например доку [«grid-auto-columns, grid-auto-rows»](https://y-doka.site/css/doka/grid-auto-columns-rows) разбить на две. Пусть лучше они будут маленькие и с повторами.
- Если мы по каким-то причинам все же сгруппировали штуки, не перечислять их в названии, а написать словами: «Неявные ряды и колонки грида». Но все же лучше стремиться к раздельности, мне кажется: чаще всего читатель ищет информацию о конкретном свойстве. Можно создавать и отдельные статьи, и группирующие.
- Избавляемся от лишних слов в заголовке: например, «Комментарии в CSS» — мы уже в разделе CSS. «Promise. Метод catch» — лучше объединить в раздел Promise, чем повторять в каждом заголовке.
- Стиль заголовка.
-- В заголовках с конструкцией «Что такое N» лучше не ставить знак вопроса. И вообще не злоупотреблять этой конструкцией, например, «Что такое Node.js» — это хорошо, а в «Что такое методологии разработки и Agile» вполне можно обойтись без Что такое.
-- Заголовки должны быть в едином стиле и тоне. Например, «Webpack, краткий обзор» — это сухо, технически «Краткий обзор Webpack» смотрится уже человечески.
-- Предлагаю не злоупотреблять метафорами в зголовках — они должны быть максимально понятны. «Node.js — дом инструментов разработки» — почему дом? это дом в смысле жилище или DOM? Меньше путаницы — больше ясности.

👆 Я предлагаю лидам посмотреть на свои разделы и подумать, на какие подразелы их можно разбить, вмещается ли все в предложенную мной структуру — или нет, и написать здесь свое мнение.

@nlopin @solarrust

**Comment by solarrust** [comment]
Мои мысли по структуре [тут](https://disk.yandex.ru/i/IsdexK6jR5VwOQ)

**Comment by tachisis** [comment]
@solarrust замечательно получилось! Я правильно понимаю, что порядок разделов ты хочешь сделать, как в твоей таблице, где легенда? Еще я бы убрала примечание (растр и вектор) и, может быть, стоит немного подумать наз названием «философия» — нет ли какого-то более приближенного к IT понятия для статей общего характера.

**Comment by pepelsbey** [comment]
Меня тоже немного цапнуло «философия», у него бывают осуждающие коннотации, мол, «развели тут философию, а мне работать нужно». Тут скорее «история» или секция «спецификации» (спеки?).

**Comment by solarrust** [comment]
> Я правильно понимаю, что порядок разделов ты хочешь сделать, как в твоей таблице, где легенда

Нет, пока они там не по порядку расположены. Просто добавляла по мере необходимости.

> стоит немного подумать наз названием «философия»

Это рабочее название

**Comment by tachisis** [comment]
Мне нравится «концепции». Может быть, «Основные» или «Базовые».

**Comment by nlopin** [comment]
Я собрал [страничку](https://www.notion.so/praktikum/d82a666a662844eb8e09022dfe02f83f), как это может выглядеть в разделе JS и инфра.

Если мы говорим, что дублировать статьи между подразделами можно, то я думаю получится хорошо. Надо только технически продумать, как статьи размечать и генерить оглавление автоматически

**Comment by pepelsbey** [comment]
@nlopin очень здорово выглядит в такой структуре, особенно для JS, где типов сущностей кажется больше.

Я тут подумал, что карту навигации можно было бы собрать как-то так: представь файл **js.yml**

```yml
- WebAPI
  - alert
  - confirm
- DOM
  - element
  - events
```

Где корневые элементы — это названия разделов, а вложенные — псевдонимы статей. Я вижу, что есть некоторые случаи, когда коневые элементы сами являются вводными статьями раздела, но думаю это тоже можно разрулить в формате.

Главное тут, что это позволит сделать **ручную** сортировку по важности, логике, порядку. Плюс можно будет что-то не выводить, если вдруг это понадобится. Например, если это черновик — но это так, фича сбоку. Главное — ручной контроль.

Я пока не вижу, как это можно удобно собрать руками с помощью тегов. Мы точно захотим выводить внутри категории что-то посложнее, чем алфавитный порядок.

**Comment by nlopin** [comment]
У меня есть идея указывать в метаданных статьи ссылку на родительские статьи. Такое удобно собирать и в статье сразу видно к каким разделам она относится + это сложнее забыть сделать, чем идти в какой-то внешний файл.

Основной минус такого подхода в том, что неудобно делать ручную соритровку. Нужно вводить «вес» статьи, который сложно контролировать между статьями. В итоге будет такой же бардак как с `z-index` в css.

**Comment by pepelsbey** [comment]
Можно попробовать скомбинировать подходы. И главное: сделать защиту от случайностей: если цикл в шаблоне не находит какой-то статьи в порядке, то она просто выводится последней.

В файле статьи сделать принадлежность с категории, например:

```
tags
  - dom
```

А дальше уже разруливать в файлах-картах:

Порядок категорий внутри раздела в **index.yml**

```yml
- webapi
- dom
- etc
```

Порядок статей внутри категории в **js/dom.yml**

```yml
- element
- events
```

И положить это как-нибудь так:

```
map/
  index.yml
  js
    dom.yml
    webapi.yml
```

**Comment by tachisis** [comment]
@nlopin мне очень-очень нравится, что получилось! Отличная структура, мне самой, как не слишком продвинутому в js разработчику, было бы очень понятно и полезно!

**Comment by tachisis** [comment]
Я думаю, мы можем с чистой совестью закрыть это ишью — все сделали и получилось круто :)
