### ISSUE TITLE
Как скрыть контент от скринридера

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#3561]
## Тема

Поняла, что нет какой-то доки или коротенькой статьи о том, как скрывать контент от вспомогательных технологий. Можно коротко описать и сравнить разные способы скрытия контента:
- HTML-атрибут `hidden`.
- ARIA-атрибут `aria-hidden`.
- `display: none` и `visibility: hidden`.
- Класс `.visually-hidden`. 

Про `aria-hidden` можно обратить внимание на то, что его не надо путать и сочетать с `role="presentation"`.

**Comment by solarrust** [comment]
Отлично подмечено! Такая статья точно нужна 👍

**Comment by MariannaSpb** [comment]
@solarrust @TatianaFokina  могу взять

**Comment by TatianaFokina** [comment]
> @solarrust @TatianaFokina могу взять

Е-е-е! Закреплю за тобой задачу. Если что, пиши, если нужна будет помощь.

Пара полезных ссылок:
- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).

Пока раздел скрыт, так что используй веточку `new-section/a11y`.
