### ISSUE TITLE
Не хватает материала о CORS

### ISSUE THREAD

**Issue by RoNUII** [doka-guide/content#3564]
## CORS

Есть статья про [`fetch()`](https://doka.guide/js/fetch/), а от `fetch()` недалеко и до _**Access to fetch at '[https://anotherwebsite.com](RoNUII)' from origin [**'http://mywebsite.com'**](RoNUII) has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**_ 

Упоминания CORS в темах [**Безопасность веб-приложений и распространённые атаки**](https://doka.guide/js/web-security/#kak-zashchititsya-4), [**`@font-face`**](https://doka.guide/css/font-face/#podskazki), [**`<link>`**](https://doka.guide/html/link/#atributy) уже имеются, а вот в статье про [`fetch()`](https://doka.guide/js/fetch/) к сожалению нету

**Comment by nlopin** [comment]
Всё так, надо написать. Добавил в горящий бэклог 👍

**Comment by denisputnov** [comment]
Так может быть есть смысл посвятить CORS отдельную статью и ссылаться на нее постоянно? Да, она будет не такая большая, зато ее можно будет редактировать в одном месте, плюс это достаточно частый запрос в гугле.
Мне кажется там есть что рассказать на небольшую статейку

**Comment by nlopin** [comment]
@denisputnov , да, в этом идея. Тебе интересно взяться?

**Comment by levinside** [comment]
Статье быть?

**Comment by izosimov** [comment]
Я бы взял 👌

**Comment by denisputnov** [comment]
@izosimov @TatianaFokina, привет

Набросок статьи есть чуть ваше в #4476
