### ISSUE TITLE
Ошибка в js/bom/#history

### ISSUE THREAD

**Issue by artur-demidov** [doka-guide/content#3566]
Ссылка на статью: [bom/history/pushState](https://doka.guide/js/bom/#history)

## Описание

Если менять по минимуму: ссылка на caniuse в пометке про поддержку второго параметра в `pushState()` битая
![Снимок экрана 2022-08-12 162538](https://user-images.githubusercontent.com/98117545/184363278-da4146d0-1d5b-421e-a388-07effcc251b3.png)
Если копать глубже: в eng версии [MDN](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) второй параметр(новый title) называется `unused` и после есть пометка

> This parameter exists for historical reasons, and cannot be omitted; passing an empty string is safe against future changes to the method.

Верная ссылка на [caniuse](https://caniuse.com/mdn-api_history_pushstate_unused_parameter) - и тут тоже пишут что

> This feature is deprecated/obsolete and **should not be used**.

Думаю стоит поменять в статье параметр `title` на `unused` и добавить пометку что параметр планировался как новый заголовок, но его реализовали только apple, и то планируют удалить.

Мб в этом же pr поправить момент

> Для более точного управления историей рекомендуется использовать pushState():
>
> State — любые данные, которые связаны с переходом; бывает полезно, когда нужно разбить форму на несколько шагов, но при этом помнить, какие данные были введены на каждом из них — их можно сохранять в state:

Не понятно что за State, откуда взялся, почему не оформлен как код. Дальше же `state` идет уже как первый параметр, вот его бы и описывать

**Comment by nlopin** [comment]
Привет! Спасибо за репорт! Я исправил битую ссылку. Интересно ли тебе поправить остальное?

**Comment by artur-demidov** [comment]
Привет, возьму в работу. Переделаю на указание что параметр не используется, не поддерживается, в сафари будет удален, но задумывался как новый заголовок для страницы
