### ISSUE TITLE
Строчно-блочная модель и японское письмо

### ISSUE THREAD

**Issue by smigles** [doka-guide/content#3580]
В статье [«Поток документа»](https://github.com/doka-guide/content/blob/main/html/flow/index.md), в разделе «Контекст форматирования», некорректно следующее предложение:

> Но, например, в случае с японским языком мы видим совершенно другую картину: блочные элементы будут располагаться слева направо, а строчные — сверху вниз».

## Что не так

В современном японском языке используется два вида письма — вертикальное и горизонтальное.

При вертикальном, традиционном, письме символы в строке (или, точнее, в колонке) идут сверху вниз, а сами строки (колонки) — справа налево. Вертикальное письмо в основном сохраняется в художественной литературе и газетах.

В горизонтальной форме письма расположение символов и строк аналогично европейским языкам: символы идут слева направо, а строки — сверху вниз.

Таким образом, процитированное предложение некорректно по двум причинам:
1. В нём говорится лишь о том, как располагались бы блочные и строчные элементы при вертикальном направлении письма, при этом отсутствует уточнение, что речь идёт именно о нём (в горизонтальном письме «совершенно другой картины» нет).
2. Следование элементов при вертикальном письме описано с ошибкой: блочные элементы должны располагаться не слева направо, а справа налево, в соответствии с порядком колонок текста.

### Первый вариант

Исправить предложение примерно так:

> Но, например, в случае с японским языком, когда в тексте используется вертикальное письмо, мы видим совершенно другую картину: блочные элементы будут располагаться справа налево, а строчные — сверху вниз.

### Второй вариант

Так как вертикальное письмо, одновременно с горизонтальным, в той или иной степени [применяется](https://ru.wikipedia.org/wiki/Горизонтальное_и_вертикальное_письмо_в_языках_Восточной_Азии) не только в японском языке, но и в китайском и корейском, можно обобщить:

> Но, например, в случае с восточноазиатскими языками, такими как китайский, японский и корейский, когда в тексте используется вертикальное письмо, мы видим совершенно другую картину: блочные элементы будут располагаться справа налево, а строчные — сверху вниз.

**Comment by solarrust** [comment]
Ого, вау! Не ишью, а целая справка о видах азиатского письма. Сегодня я узнала много нового. Спасибо за это ♥️

Мне нравится второй вариант, где ты приводишь в качестве примера группу языков с уточнением. Принесёшь эту правку в пул-реквесте?
