### ISSUE TITLE
Не хватает материала о создании правила для stylelint

### ISSUE THREAD

**Issue by ab34b266** [doka-guide/content#3602]
## Тема
Статья для раздела "Рецепты".  Опишу процесс создания плагина с простым правилом для stylelint, которое будет переводить цвета из hex в rgb. Также будут вставки про внутреннее устройство stylelint.

### Зачем
Во-первых, это улучшит понимание инструментов, которые мы ежедневно используем в разработке.
Во-вторых, статья сподвигнет читателя разбираться в библиотеках, которые он использует, читать их исходный код.
В-третьих, у читателя появится возможность сделать вклад в большой open source проект. 
В-четвертых, такого материала нет на русском языке. 

- [x] Я напишу этот материал

Если именно эта статья не подходит под формат доки, то буду рад предложениям с темами, которые, возможно, как-то пересекаются с библиотеками / open source'ом.

**Comment by nlopin** [comment]
@solarrust ты проставила раздел «Инструменты», но кажется это рецепт. Или думаешь он не попадает в формат раздела?

**Comment by solarrust** [comment]
> @solarrust ты проставила раздел «Инструменты», но кажется это рецепт. Или думаешь он не попадает в формат раздела?

Поставила лейбочку не глядя 😅 
Кажется, что это вполне себе рецепт, если будет пошаговая инструкция. Хорошая тема для материала 🙌

**Comment by ab34b266** [comment]
Теперь сильно сомневаюсь, что хватит времени и сил для написания чего-то стоящего, поэтому закрою issue.
