### ISSUE TITLE
Доступное имя и описание элемента

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#3623]
## Тема

- Что такое доступное имя (accessible name) и источники имён.
- Что такое доступное описание (accessible description) и источники описаний.
- Подписи (labels / visible indicators) в разрезе доступности.
- Для каких тегов и ролей нужны.
- Основные правила.

## Ссылки для старта

- https://www.w3.org/TR/accname-1.2/
- https://w3c.github.io/accname/#dfn-accessible-name
- https://w3c.github.io/accname/#dfn-accessible-description
- https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/
- https://www.tpgi.com/what-is-an-accessible-name/
- https://www.scottohara.me//blog/2021/11/02/names-and-labels.html
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names
- https://twitter.com/hdv/status/1569674199928651776?s=20&t=J3vBD4inGmGDmViqNpLFuQ
- https://hidde.blog/better-accessible-names/
- https://jarango.com/2023/07/10/how-to-write-good-labels/
- https://tetralogical.com/blog/2023/04/05/accessible-names-and-descriptions/

## Полезные ссылки по тексту и демкам в Доке

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

**Comment by Harperok** [comment]
Готов взять

**Comment by TatianaFokina** [comment]
@Harperok, привет! 👋 Собираешься писать материал? Может быть нужна наша помощь?

**Comment by Harperok** [comment]
> @Harperok, привет! 👋 Собираешься писать материал? Может быть нужна наша помощь?

Привет, да, добрался наконец то, думаю сделаю за недели 2 сейчас сажусь за материалы)

**Comment by solarrust** [comment]
@Harperok привет! Как дела с этим материалом? Нужна какая-то помощь?

**Comment by MariannaSpb** [comment]
Привет! готова взять задачку

**Comment by TatianaFokina** [comment]
> Привет! готова взять задачку

Ооооо, привет! Рада видеть тебя и тут. Бери!
