### ISSUE TITLE
Язык сайта и содержимого

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#3758]
## Тема

- Почему правильно задавать язык важно для вспомогательных технологий.
- Как задать язык страницe.
- Как задать язык отдельной части страницы.
- Особенности взаимодействия скринридеров с некоторым контетом (например, числа могут читать по-разному в зависимости от языка).
- ARIA- и HTML-атрибуты, значения которых надо не забывать переводить.

## Ссылки для старта

- https://webaim.org/techniques/language/
- https://www.w3.org/TR/wai-aria-1.2/#translatable-states-and-properties
- https://w3c.github.io/aria/#translatable-attributes

## Полезные ссылки по тексту и демкам в Доке

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

**Comment by alexTaraskina** [comment]
Привет! хочу взять эту задачу в работу

**Comment by TatianaFokina** [comment]
@alexTaraskina, привет! Планируешь браться за статью? Может быть нужна моя помощь?

**Comment by alexTaraskina** [comment]
@TatianaFokina привет! да, я постараюсь на этих выходных закоммитить
