### ISSUE TITLE
Неточность в блоке "На практике" у заголовков

### ISSUE THREAD

**Issue by kazakov-al** [doka-guide/content#3761]
Ссылка на статью: [`<h1>...<h6>`](https://doka.guide/html/h1-h6/#doka-dog-sovetuet)

## Описание

Мне кажется нужно убрать `Используй <h1> на странице не больше одного раза; <h2> — не больше двух, максимум трёх раз; <h3> — можно 4-5 раз и так далее.`

По нескольким причинам:
1) про h1 уже сказано в подсказках.
2) а про h2/h3 мне кажется заблуждение, ведь получается, нам прямым текстом запрещается структура:
```
<h1>Заголовок</h1>
<h2>Наши товары</h2>
<h3>Товар 1</h3>
<h3>Товар 2</h3>
<h3>Товар 3</h3>
<h3>Товар 4</h3>
...
```

### Пруфы
[Accessible heading structure](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/)
[Accessibility and SEO](https://www.a11yproject.com/posts/accessibility-seo/)

**Comment by solarrust** [comment]
Привет. Блок «На практике» это личный совет от человека, основанный на его опыте. Если твой опыт отличается от описанного, то ты тоже можешь дать свой совет в этой рубрике. Приноси пул-реквест с твоим мнением — с радостью опубликуем!

**Comment by KazakovAS** [comment]
> Привет. Блок «На практике» это личный совет от человека, основанный на его опыте. Если твой опыт отличается от описанного, то ты тоже можешь дать свой совет в этой рубрике. Приноси пул-реквест с твоим мнением — с радостью опубликуем!

Но тогда ведь получится несостыковка, в одном месте одно, а в другом противоположное

**Comment by solarrust** [comment]
Есть два возможных пути как избавиться от этой неточности:
- Ты можешь прислать _уточняющий_ совет, в котором аргументированно оспоришь ту точку зрения.
- Ты можешь взять существующий совет за основу и переписать его так, чтобы он был корректным. Тогда он будет под твоим авторством.

Какой из вариантов был бы для тебя удобнее?

**Comment by KazakovAS** [comment]
> Есть два возможных пути как избавиться от этой неточности:
> 
> * Ты можешь прислать _уточняющий_ совет, в котором аргументированно оспоришь ту точку зрения.
> * Ты можешь взять существующий совет за основу и переписать его так, чтобы он был корректным. Тогда он будет под твоим авторством.
> 
> Какой из вариантов был бы для тебя удобнее?

Довольно проблематично аргументированно оспорить вещь взятую с форумов бородатых годов (и там такие же холливары, где один говорит подобное и ему 10 человек доказывают, что оно так не работает), по сути не возможно создать чистые тепличные условия и как следствие фиг проверишь + разработчики поисковиков не раскрывают подобные алгоритмы (но опять же в их рекомендациях подобного нет, там только про h1)  =/

**Comment by solarrust** [comment]
Значит второй вариант?

**Comment by KazakovAS** [comment]
> Значит второй вариант?

Да.. Но ближе ко вт/ср только смогу)

**Comment by solarrust** [comment]
No rush, приноси пул-реквест как тебе будет удобно =)

**Comment by solarrust** [comment]
@kazakov-al привет! Планируешь ли принести ПР?

**Comment by kazakov-al** [comment]
> @kazakov-al привет! Планируешь ли принести ПР?

Привет, вылетело из головы в связи с сентябрем) На неделе подумаю чего можно с этим сделать

**Comment by solarrust** [comment]
@kazakov-al привет! Пинг по этой задаче
