### ISSUE TITLE
Ошибка при предпросмотре статей

### ISSUE THREAD

**Issue by kalpovskii** [doka-guide/content#3828]
Не могу запустить предпросмотр с помощью docker. 
_Ошибка:_ This endpoint requires you to be authenticated. 
Докер у меня работает, пробовал с sudo и без. Использую ubuntu 20.04. Ничего не нашел по теме :(
Что я делаю не так?

**Comment by kalpovskii** [comment]
![image](https://user-images.githubusercontent.com/64479736/192479524-266a7d63-2d7c-4ca3-baf8-d1a761c87bb6.png)

**Comment by alexTaraskina** [comment]
@furtivite привет! 

Склонировала platform в ту же папку - теперь content и platform лежат на одном уровне. 
Установила пакеты, создала .env файл с переменными окружения, сгенерировала персональный токен и запустила платформу локально. 

При запуске ./start.sh из content вижу ту же ошибку. Что-то упустила?

**Comment by solarrust** [comment]
Надеюсь, что проблема решилась и ишью больше не актуально. Если всё же что-то ещё не работает — приноси новое! 🙏
