### ISSUE TITLE
Написать в документации об ограничении блоков кода в 72 символа

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#3876]
## Зачем

Если ограничиваться 72 символами при написании блоков кода (которые ```css и т.п.), то на большинстве экранов (которые > 800) скрола появляться не будет. Удобно. Красиво. Практично.

## Попросить, а не ограничить

Уложиться в 72 символа не всегда получится. Так что можно написать что-то такое:

> Если все строки вашего кода короче 72 символов, то на десктопе не будет появляться горизонтальный скролл, а вы будете булочками с корицей (✿◡‿◡)

**Comment by nlopin** [comment]
Мне нравится рекомендация. @solarrust как тебе?

**Comment by StarHamster** [comment]
@solarrust, что думаешь по предложению? 👀

**Comment by solarrust** [comment]
Оу, упустила, прошу прощения.
Да, давайте мягко намекнём про длину строки, но без давления. Всё же не всегда получится соблюдать это правило.
