### ISSUE TITLE
Бот автоматически удаляет лейблы

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#3889]
Он это делает сразу после публикации превью. Из-за этого очень сложно ориентироваться в открытых ПР и считать для статистики закрытые.

**Comment by igsekor** [comment]
Разберусь окончательно с этой проблемой

**Comment by StarHamster** [comment]
Поправка: он это делает, когда кто-то коммитит в ветку

**Comment by furtivite** [comment]
> Поправка: он это делает, когда кто-то коммитит в ветку

Да, при каждой пересборке.

**Comment by StarHamster** [comment]
@igsekor, а лейблер сейчас вообще какие-нибудь лейблы ставит? Или только удаляет проставленные? Мб, тогда до фикса отключить этот экшен?

**Comment by nlopin** [comment]
Я поресёрчил ишью и проблема понятна — сейчас лейблер работает по стратегии `replace`. Это означает, что в момент, когда робот проставляет свои лейблы, он сбрасывает все уже установленные.

Легким первым шагом будет перевести его в стратегию `append`, где робот только добавляет лейблы, но это решает лишь часть проблемы. 

Если посмотреть на #3896 , то можно заметить, что лейблер вообще не ставит лейблов, хотя я ожидаю, что он должен установить три лейбла: _улучшение_, _html_, _демо_.

**Comment by nlopin** [comment]
Выпустил версию 1.0.1 лейблера, которая ничего не удаляет. Фикс будет работать во всех новых пул-реквестах и в старых, если в них вмёржить `main`
