### ISSUE TITLE
Как это понять → Как понять

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#3892]
Было бы круто во имя единообразия переписать все заголовки «Как это понять» в «Как понять». В [примере доки](https://github.com/doka-guide/content/blob/main/docs/examples/doka.md) фигурирует заголовок «Как понять», а по факту более длинный заголовок используется чаще 👎

Если верить поиску гитхаба (и мне), то сейчас в репозитории всего:

- 186 фраз «Как это понять»,
- 184 фразы «Как понять».

**Comment by solarrust** [comment]
Привет тут!
Круто, что заметил. Проблемы справочника с множеством авторов 😅
Давай оставим вариант покороче. Принесёшь пиар?

**Comment by StarHamster** [comment]
Без проблем)
