### ISSUE TITLE
Про принцип Pixel Perfect

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#390]
Рассказать что за зверь, зачем нужен. Про плагинчики и альтернативу через наложение картинки. Про допустимые отклонения (по правилам платформы-заказчика до 30px).

**Comment by xpleesid** [comment]
Привет! Готов взяться

**Comment by solarrust** [comment]
С огромной радостью прочитаю статью от тебя по этой теме!
Тут, кстати, не обязательно ограничиваться стандартной структурой доки. Пиши как пишется. Важно только сохранить раздел «Кратко», чтобы можно было быстро получить основную инфу.
