### ISSUE TITLE
Добавляет .DS_Store в gitignore

### ISSUE THREAD

**Issue by kxnkxv** [doka-guide/content#3908]
Ранее ври создании PR вместе с коммитом после 'git add .' в одном из моих PR прилетел [.DS_Store](https://github.com/doka-guide/content/pull/3907/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86)

**Comment by StarHamster** [comment]
Предлагаю что-то такое:

```gitignore
# Игнорировать директории IDE от JetBrains
.idea/

# Игнорировать служебные директории macOS
**/.DS_Store
```

**Comment by nlopin** [comment]
тогда надо и VsCode добавить, он вроде тоже создает

**Comment by StarHamster** [comment]
> тогда надо и VsCode добавить, он вроде тоже создает

Что он создаёт?.. 👀 Он ничего не создаёт...

**Comment by kxnkxv** [comment]
Глобальный gitignore это не повсеместная практика, её мало кто использует.
Я лично первый раз услышал про глобальный gitignore, за все те годы, сколько я работаю.
Давайте делать "как у всех"?
