### ISSUE TITLE
Как реально работают flex-shrink и flex-grow

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#391]
Рассказать про механизм расчёта свободного места. Дать прикольные фишки про адаптивное на основе этих свойств.

**Comment by openysheva** [comment]
Возьму)

**Comment by solarrust** [comment]
@openysheva привет! Как дела? Может быть есть какие-то вопросы по процессу написания?

**Comment by openysheva** [comment]
привет! на этой неделе постараюсь сделать)
