### ISSUE TITLE
Стайлгайд: радио-кнопки тоже должны быть цветными

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#3920]
Считаю, что радио-кнопки тоже должны должны быть цветными, как и чекбоксы. Зачем в этом бренном мире делать чёрно-белые кнопки? 🥺

**Comment by skorobaeus** [comment]
Это сделано намеренно :) Чекбоксы и радиокнопки это разные сущности, они должны отличаться. Но по форме они очень похожи, значит, пусть отличаются цветом :)

Мне кажется, это не ошибка в контенте, поэтому я закрываю ишью. А поболтать за дизайн всегда рада в дискорде :)
