### ISSUE TITLE
Добавить ссылку на Дискорд в ридми обоих репозиториев

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3979]
Мы подумали, что нигде не подсвечиваем наличие у нас Дискорда. Был пост в соцсетях, но он пропал из ленты.
Будет круто добавить ссылочку (https://discord.gg/Ncpvbun2mr) в ридми этого репозитория и в репо платформы.

**Comment by StarHamster** [comment]
Можно бейдж использовать

https://img.shields.io/discord/1006904139969724436

**Comment by solarrust** [comment]
Боюсь, что бэджик не будет обращать на себя достаточно внимания, сольётся со всеми остальными =(
Но точно можно попробовать! И посмотреть, как получиться =)

**Comment by Saimon398** [comment]
Здравствуйте, я бы хотел взять задачу себе, если это еще актуально

**Comment by solarrust** [comment]
Привет! Классно, спасибо большое ♥️
Закреплю задачку за тобой.
Пожалуйста, пиши, если тебе понадобиться любая помощь 🙌
