### ISSUE TITLE
Привести все юзернеймы в _people/_ к единому формату

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#3987]
Мы сперва старались следить за тем, чтобы папки именовались в нижнем регистре. Но пара имён с заглавными появились со временем. Было бы здорово соблюдать консистентность и переименовать папки.
Важно не забыть пройтись по контенту и заменить все использования юзернейма на новый формат.

**Comment by StarHamster** [comment]
Закрепишь за мной? 😅

**Comment by solarrust** [comment]
@StarHamster done!
