### ISSUE TITLE
Mobile first vs. Desktop First

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#399]

**Comment by mikola911** [comment]
Пробую взять

**Comment by solarrust** [comment]
@mikola911 привет! Нужна ли какая-то помощь с написанием статьи?

**Comment by mikola911** [comment]
@solarrust привет, пока главная проблема - сесть и начать.

**Comment by solarrust** [comment]
Мне обычно помогает на пустом листе написать «Блин, короче» (или посильнее) и начать объяснять как для друга =)
А уже потом форматировать и причёсывать.

**Comment by solarrust** [comment]
@mikola911  привет! Как дела с этим материалом? Нужная какая-то помощь?

**Comment by danakun** [comment]
Привет! А это еще актуально @solarrust  ? у меня есть информация на эту тему, могу написать статью!

**Comment by solarrust** [comment]
@danakun Привет! Пинг по этой задачке =)

**Comment by reznikovAndrey** [comment]
@solarrust , привет)
интересная тема, готов поресерчить и написать статью)

**Comment by TatianaFokina** [comment]
> @solarrust , привет) интересная тема, готов поресерчить и написать статью)

Притворюсь Алёной и прокричу: «Ура, закрепила задачу за тобой».

**Comment by reznikovAndrey** [comment]
@TatianaFokina , @solarrust , я бы хотел с вами посоветоваться по поводу плана статьи, я написал несколько блоков, но чувствую, что нужно что-то еще, буду рад вашему фидбеку)

1. Кратко рассказать о 2 подходах в современном вэбе
2. Особенности mobile-first
3. Особенности desktop-first

Собственно, какие есть идеи дальше:
- стоит рассказать о том, для каких приложений какой подход более подходящий?
- привести базовые примеры с версткой (как несколько колонок на десктопе превращаются в одну на мобилке) 
- рассказать, что современные css фреймворки используют mobile-first подход

**Comment by solarrust** [comment]
Мне нравится идея привести пример с вёрсткой и показать на нём оба подхода. Кажется, это будет полезно и наглядно. То, как при этом пишутся правильно медиавыражения, тоже стоит подсветить.

А интересный факт про фреймворки можно вполне добавить в блок «На практике», это прикольно!
