### ISSUE TITLE
Добавляет вопрос: Для чего используется оператор "&&"?

### ISSUE THREAD

**Issue by kxnkxv** [doka-guide/content#3995]
Для чего используется оператор "&&"?

**Comment by AndreiDetenkov** [comment]
@HellSquirrel, @solarrust  возьму этот issue? только было бы хорошо сразу добавлять мета теги для related или это не так важно?

**Comment by skorobaeus** [comment]
@AndreiDetenkov привет! Планируешь добавить ответ на этот вопрос? Мета-теги мы создали 😁

Чтобы добавить ответ, достаточно будет в [папку](https://github.com/doka-guide/content/tree/main/interviews/logical-and) положить .md с ответом по такой структуре:

```
answers/
  твой-ник/
    index.md
```

И вот тут [инструкция](https://github.com/doka-guide/content/blob/main/docs/interviews.md#%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%BE%D1%82%D0%B2%D0%B5%D1%82) на всякий случай.
