### ISSUE TITLE
Стилизация чекбоксов

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#401]

**Comment by loonlylokly** [comment]
Привет)
Хотел бы написать статью об этом. Можно попробовать?

**Comment by TatianaFokina** [comment]
> Привет) Хотел бы написать статью об этом. Можно попробовать?

Привет, бери, конечно!

**Comment by loonlylokly** [comment]
Мне кажется можно объединить темы "Стилизация чекбокса" и "Стилизация радио кнопки" так как там отличие только в указании типа инпута. Ну и в тексте тогда надо будет как-то это сформулировать.
