### ISSUE TITLE
Добавить вопрос: В чем разница между операторами `==` и `===`?

### ISSUE THREAD

**Issue by kxnkxv** [doka-guide/content#4014]
В чем разница между операторами "==" и "==="?

**Comment by solarrust** [comment]
Осталось оформить это всё в виде ответа на вопрос для собеседования =)
Кто возьмёт?

**Comment by AntonVolkov71** [comment]
Двойное равно - это не строгое сравнение, тройное равно - строгое.
При не строгом сравнении оператор равенства приводит левый и правый операнд к единому типу, после сравнивает значения .
При стогом сравнении сначала сравниваются типы операндов, и только после сравниваются значения.

Пример нестрогого сравнения: строка "1" и число 1 результатом будет true.
Пример строгого сравнения: строка "1" и число 1 результатом будет false.

**Comment by solarrust** [comment]
Привет. Это ишью нужно для того, чтобы написать ответ на заданный вопрос в виде файла для публикации в рубрике «На собеседовании». А не для обсуждения верного ответа прямо здесь, в переписке. Цель — ответ должен появиться на сайте, чтобы каждый читатель Доки мог его увидеть.
Как оформить ответ для рубрики «На собеседовании» можно почитать [в документации](https://github.com/doka-guide/content/blob/main/docs/interviews.md).

**Comment by AndreiDetenkov** [comment]
@solarrust а есть в interviews уже созданная папка для этого issue?

**Comment by solarrust** [comment]
На сколько я вижу — пока нет

**Comment by AndreiDetenkov** [comment]
@solarrust мне самому создать папку и сделать ПР по этой [доке](https://github.com/doka-guide/content/blob/main/docs/interviews.md) ?

**Comment by HellSquirrel** [comment]
@AndreiDetenkov приветик! Да, все верно. Создавай сразу и вопрос и свой ответ, открывай PR. Дальше я приду его смотреть, править и мержить :)

**Comment by AndreiDetenkov** [comment]
@HellSquirrel ок. мета теги потом только сами пропишете, я пока не знаю куда и что =)

**Comment by AndreiDetenkov** [comment]
@HellSquirrel мой ПР https://github.com/doka-guide/content/pull/4683
