### ISSUE TITLE
@supports

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#410]

**Comment by IPogorelova** [comment]
Привет, хочу попробовать взяться :)
Вижу, что уже есть плейсхолдер, но постараюсь дополнить информацией.
Если есть что-то, что обязательно нужно упомянуть - буду рада любым дополнениям/предложениям :)

**Comment by solarrust** [comment]
Привет!

Круто, спасибо за твою инициативность 🙌
Закрепляю задачку за тобой.

Пара полезных ссылок, которые могут тебе пригодиться в процессе написания:
- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).

Присылай вариант, который напишется и мы вместе с тобой обсудим его и доработаем, если это потребуется =)
