### ISSUE TITLE
Свойство word-wrap

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#411]
Рассказать подробно про это чудо-свойство. Какие значения может принимать, к каким элементам применяется.
Как можно сочетать с другими свойствами?
Показать в демо работу свойства.

Референсы:
- https://sebhastian.com/css-word-wrap/
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text

**Comment by punkmachine** [comment]
Возьмусь. Попробую сделать.

**Comment by solarrust** [comment]
Супер!
Назначила задачку на тебя. Пиши если понадобиться любая помощь 🙌
