### ISSUE TITLE
Ответ на вопрос: Каков типичный случай использования анонимных функций?

### ISSUE THREAD

**Issue by punkmachine** [doka-guide/content#4142]
Вопрос уже опубликован, а ответа нет. 
Возьмусь. 
Ник в дискорде: punkmachine#4202

**Comment by TatianaFokina** [comment]
@punkmachine, планируешь браться или ну его?

**Comment by punkmachine** [comment]
Тааак. Извиняюсь, зашив на работ+учёбе последние месяцы. На новогодних праздниках возьмусь за ишьюсы на мне висящие.

**Comment by TatianaFokina** [comment]
> Тааак. Извиняюсь, зашив на работ+учёбе последние месяцы. На новогодних праздниках возьмусь за ишьюсы на мне висящие.

Слушай, тут не за что извиняться. Это подвиг, что ты вообще какое-то время на оупенсорс находишь. Спасибо тебе!

**Comment by skorobaeus** [comment]
Закрываю ишью, т.к. вопрос опубликован.
