### ISSUE TITLE
Поисковая оптимизация для начинающих

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#415]

**Comment by punkmachine** [comment]
Я, как сеошник сбежавший во фронтенд, обязан написать такую статью, но, я максимально не уверен в своих силах и думаю, что буду делать её долго. 

Возьмусь, поможете?😅

**Comment by solarrust** [comment]
Конечно поможем! Не беспокойся =) Закрепляю задачку за тобой?

**Comment by punkmachine** [comment]
Да, закрепляй, спасибо).

**Comment by punkmachine** [comment]
если что по вопросам сюда или в дискорд?

**Comment by solarrust** [comment]
Если уже будет текст, то всё можно обсуждать в рамках пулреквеста. А если появятся вопросы по ходу работы — пиши где тебе удобно. Можно тут, а можно и в дискорде 🤗
