### ISSUE TITLE
Неточность в подсказках статьи z-index

### ISSUE THREAD

**Issue by fpetrakov** [doka-guide/content#4158]
### Ссылка на статью

https://doka.guide/css/z-index/

### Описание

В первой подсказке написано, что z-index срабатывает только для элементов с позиционированием (свойство position), отличающимся от статичного (значения relative, absolute, fixed, sticky). 

Дело в том, что z-index также будет работать, если элемент находится во flex layout. Прикладываю небольшую демку на которой нет св-ва position, но при этом z-index работает. 

### Пруфы

https://codesandbox.io/s/relaxed-elion-jbhugm?file=/src/styles.css

**Comment by solarrust** [comment]
Привет!

Спасибо за внимательность. Да, всё так, `z-index` работает не только внутри флексов, но ещё и внутри гридов. Короче везде, где создаётся новый контекст. 
Предлагаю эту подсказку сделать не такой категоричной, а ниже дописать ещё одну про флексы, гриды и другие случаи.

Возьмёшься за эти правки?

**Comment by fpetrakov** [comment]
Да, могу попробовать. Еще можно усложнить имеющийся или добавить более сложный пример с контекстами, [например такой](https://codesandbox.io/s/nostalgic-antonelli-y0jqt4?file=/src/styles.css). В нем, без знания о контекстах, кажется неочевидным, почему элемент с ```z-index: 9999``` не на самом верху. По нему можно объяснить, что внутри `main` создается новый контекст и т.д.
