### ISSUE TITLE
Псевдокласс :first-line

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#417]

**Comment by punkmachine** [comment]
Привет! Хочу дополнить статью. 

После дополнения, себя как автора указать, как с ::first-letter или как соавтора?

**Comment by punkmachine** [comment]
Оно в работе. Просто пока не успеваю, но сделаю.

**Comment by solarrust** [comment]
Не беспокойся, задачка закреплена за тобой, никто другой её не возьмёт. Take your time, как говорится =)
