### ISSUE TITLE
Ошибка в `HTMLCollection и NodeList`: демка не адаптирована к тёмной теме

### ISSUE THREAD

**Issue by rakleed** [doka-guide/content#4172]
### Ссылка на статью

https://doka.guide/js/htmlcollection-and-nodelist/#kak-ponyat

### Описание

Демка не адаптирована к тёмной теме.

![image](https://user-images.githubusercontent.com/19418601/209025962-58c32064-96e7-4853-8596-1c17481885d4.png)

**Comment by rakleed** [comment]
А также в статье [Set](https://doka.guide/js/set/#kak-ponyat):

![Screenshot 2022-12-22 at 03 45 48](https://user-images.githubusercontent.com/19418601/209030714-7e7b02bd-127e-4554-b159-0bcf74d14783.png)

**Comment by rakleed** [comment]
На сколько я понимаю, достаточно поменять стили. Тогда в течение двух недель постараюсь найти время и обновить демки.

**Comment by rakleed** [comment]
@skorobaeus решил поискать другие демки с такой же проблемой, и обнаружил ещё несколько проблем:

1. Вы приглушили цвета в тёмной теме (https://github.com/doka-guide/platform/issues/536#issuecomment-1119499520, _PR или коммит не смог найти_), но в [стайлгайде по демкам в разделе про цвета](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#цвета) вы почему-то указали цвета разделов для светлой темы. Хотя в [самом начале](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#с-чего-начать) сказано, что демки должны быть в тёмной теме, да и написали вы стайлгайд после обновления цветов для тёмной темы (https://github.com/doka-guide/content/pull/3273). Из-за этого, когда демки занимают большую часть страницы, и у них задний фон как раз использует цвета разделов, получается большая часть страницы с ярким задним фоном, что очень неприятно для глаз, когда находишься в тёмном помещении. Пример [раз](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4), [два](https://doka.guide/html/picture/#:~:text=%3Cimg%3E.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) и [три](https://doka.guide/html/picture/#:~:text=%D1%81%20%D1%83%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%3A-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5).
2. Почему в [шаблон демки](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#шаблон) не было добавлено свойство `:root { color-scheme: dark }` (как [предлагал cergmin](https://github.com/doka-guide/content/issues/2303#:~:text=%D0%A1%D1%82%D0%BE%D0%B8%D1%82%20%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D1%82%D1%8C%20color%2Dscheme%3A%20dark%3B%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D1%84%D0%BE%D0%BD%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%B9%2C%20%D1%87%D1%82%D0%BE%D0%B1%D1%8B%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%B2%D0%B4%D1%80%D1%83%D0%B3%20%D0%BF%D0%BE%D1%8F%D0%B2%D0%B8%D0%BB%D1%81%D1%8F%20%D1%81%D0%BA%D1%80%D0%BE%D0%BB%D0%BB%D0%B1%D0%B0%D1%80%2C%20%D1%82%D0%BE%20%D0%BE%D0%BD%20%D1%82%D0%BE%D0%B6%D0%B5%20%D0%B1%D1%8B%D0%BB%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%BC.))? Ведь из-за этого скролл бар светлого цвета у демок со скроллом при использовании тёмной темы на сайте (например, [здесь](https://doka.guide/css/position/#:~:text=%D0%BD%D0%B5%20%D0%BE%D0%BA%D0%BD%D0%B0%20%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-sticky)).

Ну и более общие проблемы с тёмной темой:

3. Почему вы для тёмной темы не приглушаете контрастность текста? Сейчас он выглядит слишком ярким на тёмном фоне. Подробнее [раз](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images) и [два](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images).
4. Почему у вас нет никаких гайдов для картинок и их заднего фона? Ведь в тёмной теме картинки с белым задним фоном очень неприятны для глаз. Наглядный пример — [гайд по grid](https://doka.guide/css/grid-guide/#osnovnye-terminy).

Наверное стоит для каждой проблемы завести отдельные issues, да? Но чтобы потом опять не переделывать демки, хотелось бы узнать твоё мнение по первой и второй проблеме.

**Comment by skorobaeus** [comment]
@rakleed

> @skorobaeus решил поискать другие демки с такой же проблемой, и обнаружил ещё несколько проблем:
> 
> 1. Вы приглушили цвета в тёмной теме ([Контрастность цветов для тёмной темы platform#536 (comment)](https://github.com/doka-guide/platform/issues/536#issuecomment-1119499520), _PR или коммит не смог найти_), но в [стайлгайде по демкам в разделе про цвета](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%86%D0%B2%D0%B5%D1%82%D0%B0) вы почему-то указали цвета разделов для светлой темы. Хотя в [самом начале](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%81-%D1%87%D0%B5%D0%B3%D0%BE-%D0%BD%D0%B0%D1%87%D0%B0%D1%82%D1%8C) сказано, что демки должны быть в тёмной теме, да и написали вы стайлгайд после обновления цветов для тёмной темы ([Добавляет руководство по стилю демок #3273](https://github.com/doka-guide/content/pull/3273)). Из-за этого, когда демки занимают большую часть страницы, и у них задний фон как раз использует цвета разделов, получается большая часть страницы с ярким задним фоном, что очень неприятно для глаз, когда находишься в тёмном помещении. Пример [раз](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4), [два](https://doka.guide/html/picture/#:~:text=%3Cimg%3E.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) и [три](https://doka.guide/html/picture/#:~:text=%D1%81%20%D1%83%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%3A-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5).
> 2. Почему в [шаблон демки](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD) не было добавлено свойство `:root { color-scheme: dark }` (как [предлагал cergmin](https://github.com/doka-guide/content/issues/2303#:~:text=%D0%A1%D1%82%D0%BE%D0%B8%D1%82%20%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D1%82%D1%8C%20color%2Dscheme%3A%20dark%3B%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D1%84%D0%BE%D0%BD%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%B9%2C%20%D1%87%D1%82%D0%BE%D0%B1%D1%8B%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%B2%D0%B4%D1%80%D1%83%D0%B3%20%D0%BF%D0%BE%D1%8F%D0%B2%D0%B8%D0%BB%D1%81%D1%8F%20%D1%81%D0%BA%D1%80%D0%BE%D0%BB%D0%BB%D0%B1%D0%B0%D1%80%2C%20%D1%82%D0%BE%20%D0%BE%D0%BD%20%D1%82%D0%BE%D0%B6%D0%B5%20%D0%B1%D1%8B%D0%BB%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%BC.))? Ведь из-за этого скролл бар светлого цвета у демок со скроллом при использовании тёмной темы на сайте (например, [здесь](https://doka.guide/css/position/#:~:text=%D0%BD%D0%B5%20%D0%BE%D0%BA%D0%BD%D0%B0%20%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-sticky)).
> 
> Ну и более общие проблемы с тёмной темой:
> 
> 3. Почему вы для тёмной темы не приглушаете контрастность текста? Сейчас он выглядит слишком ярким на тёмном фоне. Подробнее [раз](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images) и [два](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images).
> 4. Почему у вас нет никаких гайдов для картинок и их заднего фона? Ведь в тёмной теме картинки с белым задним фоном очень неприятны для глаз. Наглядный пример — [гайд по grid](https://doka.guide/css/grid-guide/#osnovnye-terminy). Может стоит делать отдельные картинки для светлой и тёмной темы? Или как с демками сразу адаптировать для тёмной темы? UPD: нашёл [PR](https://github.com/doka-guide/content/pull/4170), где вы как раз добавляете стайлгайд для картинок (схем), и в макете в Figma фон чёрного цвета. Но вот что делать, если у картинки большая часть контента будет светлого цвета (к вопросу про различные изображения для светлой и тёмной темы)?
> 
> Наверное стоит для каждой проблемы завести отдельные issues, да? Но чтобы потом опять не переделывать демки, хотелось бы узнать твоё мнение по первой и второй проблеме.

1. Фон демок никогда не окрашивается в цвета разделов и всегда тёмно-серый: `#18191C`.  
Цвета разделов используются акцентно: для окрашивания кнопок, чекбоксов и радио, ссылок, и т.п.

2. Это хорошее предложение, его стоит добавить в гайд. Можно завести ишью, можно сразу прислать PR.

3, 4. К сожалению, у нас нет временных и человеческих ресурсов для создания отдельных версий изображений для тёмной и светлой темы сайта. Поэтому для схем и демок выбран единый компромиссный дизайн, который одновременно и выполняет свои задачи, и остаётся доступным в тёмной и светлой темах. Обилия белого цвета в этом дизайне мы стараемся избегать.

**Comment by rakleed** [comment]
1. Я же привёл примеры, где в качестве заднего фона полностью или по большей части у демок используются акцентные цвета. Вот они ещё раз: [раз](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4), [два](https://doka.guide/html/picture/#:~:text=%3Cimg%3E.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) и [три](https://doka.guide/html/picture/#:~:text=%D1%81%20%D1%83%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%3A-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5).
2. PR #4185 готов.

По 3-ей проблеме создал отдельную issue https://github.com/doka-guide/platform/issues/1082, а насчёт 4-ой отписался в PR https://github.com/doka-guide/content/pull/4170#issuecomment-1368136789.

**Comment by StarHamster** [comment]
Ееее, разговоры о дизайне, это я люблю, позволите вклиниться? 👉👈

1. Лично мне нравятся нынешнее цветовое решение в демках. И примеры @rakleed меня устраивают. Да, [первый](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4) нарушает принципы стайлгайда (цветной фон), но правила на то и правила, чтобы их можно было нарушить один раз в году. Если вы так не считаете, то можно тексту задать цвет `#FF8630`, а фону классический `#18191C`. А у [второго](https://doka.guide/html/picture/#:~:text=%3Cimg%3E.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) и [третьего](https://doka.guide/html/picture/#:~:text=%D1%81%20%D1%83%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%3A-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) примера всё хорошо, ИМХО.
2. 👍
3. 🤔
4. Думаю, нужно просто перерисовать в тёмную тему все белые схемы, а с остальными светлыми картинками смириться 🤷‍♀️

**Comment by rakleed** [comment]
@StarHamster 
1. Проблема со вторым и третьим примером в том, что у них большая часть фона задана акцентным светлым цветом, и из-за этого глазам в тёмном помещении неприятно. А почему не нравится идея использовать акцентные цвета из тёмной темы сайта?

**Comment by skorobaeus** [comment]
> 1. Я же привёл примеры, где в качестве заднего фона полностью или по большей части у демок используются акцентные цвета. Вот они ещё раз: [раз](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4), [два](https://doka.guide/html/picture/#:~:text=%3Cimg%3E.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) и [три](https://doka.guide/html/picture/#:~:text=%D1%81%20%D1%83%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%3A-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5).
> 2. PR [Добавляет в шаблон в стайлгайде по демкам свойство `color-scheme: dark;` #4185](https://github.com/doka-guide/content/pull/4185) готов.
> 
> По 3-ей проблеме создал отдельную issue [doka-guide/platform#1082](https://github.com/doka-guide/platform/issues/1082), а насчёт 4-ой отписался в PR [#4170 (comment)](https://github.com/doka-guide/content/pull/4170#issuecomment-1368136789).

С новым годом!

Согласна, что все три примера яркие.  

В [первом](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%D1%8B%D0%B2%D0%BE%D0%B4) примере, действительно, лучше поменять местами цвета, как @StarHamster предлагает.

Во [втором](https://doka.guide/html/picture/#:~:text=%3Cimg%3E.-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) и [третьем](https://doka.guide/html/picture/#:~:text=%D1%81%20%D1%83%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%3A-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%92%20%D1%8D%D1%82%D0%BE%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5) можно снизить общую яркость, если вынести поясняющий код под изображения, а сами изображения обрезать до небольшой по высоте полоски. Примерно такой:

![image](https://user-images.githubusercontent.com/29401439/211297878-d83965f3-c5ae-43ea-a61b-88b2d811cf7e.png)

(Сразу поясню о каких изображениях идёт речь — цветные прямоугольники в данных примерах это не раскрашенные `<div>`, а PNG-файлы, которые браузер отображает в зависимости от условий, прописанных в теге `<picture>`, о котором статья).

Эти правки звучат как хороший старт для начинающих контрибьюторов, я заведу ишью.

Твой ПР одобрила, в свой ПР уточнение добавила.

> А почему не нравится идея использовать акцентные цвета из тёмной темы сайта?

Во всех уже имеющихся схемах и демках используются акцентные цвета из светлой темы. Это значит, что можно использовать приглушенные цвета в обсуждаемых прямо сейчас примерах, но в ещё 400+ примеров эти цвета останутся. 

Поэтому при решении задач нужно отвечать на вопрос "могу ли я это сделать, оставаясь в рамках текущей системы?". Чтобы разовые исключения в долгосрочной перспективе не привели проект к состоянию, описываемому прекрасной русской идиомой "кто в лес, кто по дрова".

:)

**Comment by rakleed** [comment]
> > А почему не нравится идея использовать акцентные цвета из тёмной темы сайта?
> 
> Во всех уже имеющихся схемах и демках используются акцентные цвета из светлой темы. Это значит, что можно использовать приглушенные цвета в обсуждаемых прямо сейчас примерах, но в ещё 400+ примеров эти цвета останутся.
> 
> Поэтому при решении задач нужно отвечать на вопрос "могу ли я это сделать, оставаясь в рамках текущей системы?". Чтобы разовые исключения в долгосрочной перспективе не привели проект к состоянию, описываемому прекрасной русской идиомой "кто в лес, кто по дрова".

Ну не во всех статьях есть демки, а также не все демки используют эти акцентные цвета.

А если я сделаю PR с изменением светлых акцентных цветов на тёмные, то примите такой PR?

**Comment by skorobaeus** [comment]
Нет, я не приму такой ПР.

**Comment by rakleed** [comment]
Почему?

**Comment by rakleed** [comment]
@solarrust спасибо за такой развёрнутый ответ! А что насчёт того, чтобы в [стайлгайд, в раздел с цветами](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#цвета), добавить упоминание, что можно также использовать акцентные цвета из тёмной темы? А то сейчас получается так, что можно использовать акцентные цвета только из светлой темы, хотя, например, в [этой демке](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%A7%D0%B5%D0%BC) как раз используется акцентный цвет из тёмной темы, и это нормально смотрится.

**Comment by skorobaeus** [comment]
Я не solarrust :)

Эта демка — флуктуация. В идеале здесь нужно ровно обратное: привести выбивающуюся из правил демку в соответствие с ними.

**Comment by rakleed** [comment]
А моё предложение было не относительно этой демки, а в целом для любой демки в стайлгайде в явном виде указать возможность использования акцентных цветов из тёмной темы.

**Comment by rakleed** [comment]
@skorobaeus так что насчёт этого предложения?

> А что насчёт того, чтобы в [стайлгайд, в раздел с цветами](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#цвета), добавить упоминание, что можно также использовать акцентные цвета из тёмной темы? А то сейчас получается так, что можно использовать акцентные цвета только из светлой темы, хотя, например, в [этой демке](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%A7%D0%B5%D0%BC) как раз используется акцентный цвет из тёмной темы, и это нормально смотрится.

**Comment by skorobaeus** [comment]
> @skorobaeus так что насчёт этого предложения?
> 
> > А что насчёт того, чтобы в [стайлгайд, в раздел с цветами](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%86%D0%B2%D0%B5%D1%82%D0%B0), добавить упоминание, что можно также использовать акцентные цвета из тёмной темы? А то сейчас получается так, что можно использовать акцентные цвета только из светлой темы, хотя, например, в [этой демке](https://doka.guide/html/deprecated-tags/#:~:text=%D0%A1%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-,%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BC%D0%BE%20%D0%B2%20%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B5,-%D0%A7%D0%B5%D0%BC) как раз используется акцентный цвет из тёмной темы, и это нормально смотрится.

Спасибо за это предложение и твою наблюдательность! Пока в списке задач редакции не стоит переработка дизайн-систем, но мы продолжим слушать фидбек по этому вопросу и, если созреет необходимость, вернёмся к нему.
