### ISSUE TITLE
Тег `<optgroup>`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#418]
Уже есть плейсхолдер.
Нужно расширить доку.
Дать подробности синтаксиса, наглядные примеры, уместные ситуации для использования и особенности стилизации.
Важно сказать про атрибуты для этого тега.
Как отдельный случай можно рассмотреть выбор всех опций в конкретной группе.

**Comment by pepelsbey** [comment]
Fixed #1282

**Comment by solarrust** [comment]
Уже есть плейсхолдер.
Нужно расширить доку. 
Дать подробности синтаксиса, наглядные примеры, уместные ситуации для использования и особенности стилизации.
Важно сказать про атрибуты для этого тега.
Как отдельный случай можно рассмотреть выбор всех опций в конкретной группе.

**Comment by Granondo** [comment]
Всем привет, хотел бы взять эту тему)

**Comment by solarrust** [comment]
@Granondo привет! Отлично, буду очень ждать пул-реквест от тебя =)
Тебе может пригодится док с [советами для авторов](https://github.com/doka-guide/content/blob/main/docs/styleguide.md). Пиши, если понадобиться любая помощь!

**Comment by Granondo** [comment]
#2788
