### ISSUE TITLE
Ошибка в статье "Атрибут value"

### ISSUE THREAD

**Issue by SergeyK2004** [doka-guide/content#4183]
### Ссылка на статью

https://doka.guide/html/value/

### Описание

В разделе https://doka.guide/html/value/#input input есть неточность. Сейчас там есть фраза

Для типов text, password, и hidden задаёт начальное значение. В первых двух случаях пользователь сможет стереть его и написать что-то своё.

Дело в том, что пользователь изменяет не Атрибут value, а значение value

У поля ввода есть `атрибут value` и есть `значение value` 
Атрибут используется как значение по умолчанию. В случае если пользователь ничего не ввел в поле, то именно это значение будет отправлено на сервер. 
Значение - это тот текст, который вводит пользователь в само поле инпута. 

nameInput.value и nameInput.getAttribute('value') это два разных значения

Атрибут value и текст в поле ввода могут отличаться. Вот, например http://joxi.ru/vAW1N5nF3PMVvm

Так-же можно обратить внимание на свойства объекта
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/70875520/210103941-b833729a-06f5-42da-8b9d-4c2b8f13bd3f.png">

Таким образом. получается, что пользователь как раз таки не может стереть значение атрибута и написать свое. Пользователь может только изменять value, являющийся значением, но не атрибутом. Атрибут может быть установлен только методом setAttribute() или указан в html

### Пруфы

Найти какие-то ссылки на данную особенность я не смог. Это результат собственных изысканий. Либо это просто две самостоятельных статьи, одна про Атрибут value и его роль как значение по умолчанию, устанавливаемое для инпута, какая-нибудь другая про работу с данными, вбиваемыми пользователем в поля.

**Comment by solarrust** [comment]
Привет!
Спасибо за это уточнение. Не могу пока понять, на сколько такие тонкости нужны в статье про атрибут `value`. Кажется, уместнее будет об этом рассказать в JS. Например, в статье [про работу с формами](https://doka.guide/js/deal-with-forms/). А статью в HTML оставить максимально простой. Можем переформулировать или убрать конкретно эту фразу, которая вызвала у тебя сомнения. 
Что скажешь?

**Comment by solarrust** [comment]
Пока закрываю это ишью. Приноси новое или сразу пулреквест с правками в статью про работу с формами из раздела JS, если будет желание! ♥️
