### ISSUE TITLE
Не хватает материала о новых единицах измерения

### ISSUE THREAD

**Issue by lattelix** [doka-guide/content#4186]
### Тема

lvw / lvmin / lvmax / svh / svw / svmin / svmax / dvh / dvw / dvmin / dvmax

### Зачем

Эти единицы измерения уже используются во всем, а на доке о них ни слова, нужно исправить ситуацию

### Вопрос

Уже существует дока про vh / vw / vmax / vmin Написать новую доку или в приоритете изменить старую?

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by Realetive** [comment]
@fat32elena

**Comment by fat32elena** [comment]
Меня можно назначить на это issue @Realetive @TatianaFokina

**Comment by lattelix** [comment]
Я не против, могу скинуть подобранные материалы. Изначально мне это казалось хорошей идеей, но в последствии я просто не смог получить опыт разработки, где это было бы действительно необходимо и полезно. 
Напишите пожалуйста, если материалы понадобятся. Telegram: lattelix.t.me
@fat32elena, после того, как вы сольёте форк в оригинальный репозиторий (если я не ошибаюсь) появиться ссылка на прототип доки с вашими изменениями и можно будет сразу посмотреть, как это выглядит в любом браузере.

**Comment by solarrust** [comment]
@fat32elena привет! Все материалы в Доке пишуться в формате Маркдаун прямо в репозитории. Форкай к себе, пиши материал, а потом присылай пулреквест. В нём мы вместе отредактируем и долифуем текст, после чего сольём. Тогда твой материал окажется на сайте.
Любые вопросы по ходу работы можешь задавать здесь. Обещаю быть на связи и оперативно отвечать 🙌

**Comment by solarrust** [comment]
@fat32elena привет! Как дела с этим материалом? Нужная какая-то помощь?

**Comment by AlexMosiakin** [comment]
@lattelix @TatianaFokina 

Всем привет, я так понял, что данная issue осталась без исполнителя, могу ли я попробовать написать статью о новых единицах измерения? Как раз у меня где-то лежит презентация с митапа, где я рассказывал о новых фичах хрома, там было что-то по единицы измерения тоже 🤓

**Comment by TatianaFokina** [comment]
> @lattelix @TatianaFokina @solarrust
> 
> Всем привет, я так понял, что данная issue осталась без исполнителя, могу ли я попробовать написать статью о новых единицах измерения? Как раз у меня где-то лежит презентация с митапа, где я рассказывал о новых фичах хрома, там было что-то по единицы измерения тоже 🤓

Да вообще я исключительно только за. В 2024 году эта статья уже не просто напрашивается, она кричит! Закрепляю за тобой тогда.
