### ISSUE TITLE
Ответ на вопрос: В чём отличия rest и spread операторов?

### ISSUE THREAD

**Issue by punkmachine** [doka-guide/content#4192]

**Comment by almostxyz** [comment]
привет! я с холи, был бы рад помочь с этой темой, но я не уверен, получится ли написать достаточно текста, можете помочь с планом этой статьи?

**Comment by HellSquirrel** [comment]
@almostxyz приветик :)
Эта ишью подразумевает не статью, а короткий ответ на вопрос в разделе собеседование. Инструкцию для создания ответа можно найти вот тут https://github.com/doka-guide/content/blob/main/docs/interviews.md

Примеры других ответов можно найти вот тут https://github.com/doka-guide/content/tree/main/interviews

Дальше можешь набросать текст примерно с такой структурой
1. Как выглядит оператор rest
2. Как выглядит оператор spread (ой-ой они одинаковые :)
3. Отличия

Несколько полезных референсов для составления ответа:
- Статья про spread https://doka.guide/js/spread/
- Спецификация раз https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-SpreadElement
- Спецификация два https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-ArgumentList
- Спецификация три https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-PropertyDefinition

**Comment by skorobaeus** [comment]
Вопрос добавлен на платформу в ПР #5124

**Comment by iren-a** [comment]
Привет) Я готова взять задачу.
