### ISSUE TITLE
Адаптировать к тёмной теме примеры в статье Устаревшие теги

### ISSUE THREAD

**Issue by skorobaeus** [doka-guide/content#4196]
По мотивам дискуссии в #4172 

В примерах статьи "[Устаревшие теги](https://doka.guide/html/deprecated-tags/)" крупные области окрашены в яркие цвета, это может вызвать дискомфорт у пользователей тёмной темы.

**Пример "[Тег marquee](https://doka.guide/html/deprecated-tags/demos/marquee/)"**

- Уменьшить высоту белого и оранжевого контейнеров в 1,5-2 раза, при необходимости подогнать размеры шрифтов.

**Пример "[Имитация marquee](https://doka.guide/html/deprecated-tags/demos/marquee-fallback/)"**

- Заменить оранжевый цвет фона на `#18191C`, а цвет текста на `#FF8630`.
- Добавить перед демо комментарий о том, что анимация воспроизводится при наведении курсора или при тапе.

**Comment by catbutfat** [comment]
Возьмусь
