### ISSUE TITLE
Адаптировать к тёмной теме примеры в статье `<picture>`

### ISSUE THREAD

**Issue by skorobaeus** [doka-guide/content#4197]
По мотивам дискуссии в https://github.com/doka-guide/content/issues/4172

В примерах статьи <[picture](https://doka.guide/html/picture/)> крупные области окрашены в яркие цвета, это может вызвать дискомфорт у пользователей тёмной темы.

**Во всех примерах**

- уменьшить высоту встроенных изображений до ~100 пикселей;
- на уменьшенных изображениях написать актуальные размеры;
- перенести код под изображения.

Сейчас:

![afore](https://user-images.githubusercontent.com/29401439/211314404-526544aa-6834-4db8-956c-a706609112e4.png)

Предполагаемый результат:

![after](https://user-images.githubusercontent.com/29401439/211315600-ec7e751c-d7af-4894-bb71-e362ffb994fa.png)

Параметры шрифта на изображении: Roboto, нормальное начертание, размер `60px`.

**Comment by catbutfat** [comment]
Хочу взять задачку

**Comment by catbutfat** [comment]
А может в демо сделать input range, который будет менять размер фрейма для наглядности?

**Comment by skorobaeus** [comment]
> А может в демо сделать input range, который будет менять размер фрейма для наглядности?

Привет!

Если мне не изменяет память, то изнутри демо менять размер фрейма, в который оно встроено, невозможно 🤔 К тому же, в одном из демо картинка меняется в зависимости не от размера, а от плотности пикселей, а это через input range не сымитировать.

Но почему бы не поэкспериментировать :)

**Comment by catbutfat** [comment]
Оки, спасибо, взялся! все проверю и вернусь)

**Comment by catbutfat** [comment]
> Привет!
> 
> Если мне не изменяет память, то изнутри демо менять размер фрейма, в который оно встроено, невозможно 🤔 К тому же, в одном из демо картинка меняется в зависимости не от размера, а от плотности пикселей, а это через input range не сымитировать.
> 
> Но почему бы не поэкспериментировать :)

Сначала я хотел встроить фрейм внутрь фрейма, чтоб менять размер внутреннего фрема, но действительно DPR изменить не получится и отказался от этой идеи)
