### ISSUE TITLE
Рецепт про тесты

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#4209]
### Тема

Написать рецепт о том, как тестировать код проекта (продукта)

### Зачем

Этот рецепт будет полезен для читателей и контрибьюторов платформы

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by solarrust** [comment]
@HellSquirrel подскажи, пожалуйста, можно ли закрыть это ишью?

**Comment by HellSquirrel** [comment]
Можно :)
