### ISSUE TITLE
role-атрибуты

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#421]

**Comment by punkmachine** [comment]
Речь о html атрибуте, типа `role="dialog"` и т.п.?

**Comment by TatianaFokina** [comment]
> Речь о html атрибуте, типа `role="dialog"` и т.п.?

Ага, но уже есть [статья про ARIA-роли](https://doka.guide/a11y/aria-roles/), так что даже не знаю, как написать без повторов и имеет ли смысл вообще. @solarrust, что думаешь?

**Comment by solarrust** [comment]
Да, пожалуй, существующая статья в разделе о Доступности полностью закрывает эту тему. Тогда эта задачка не актуальна. Закрою её. Спасибо! ♥️
