### ISSUE TITLE
Ссылки на законодательство в статье «Что такое доступность»?

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#4214]
В разделе [«Законодательство России о веб-доступности»](https://doka.guide/a11y/chto-takoe-a11y/#zakonodatelstvo-rossii-o-veb-dostupnosti) есть ссылки на систему Гарант и Консультант. 

Это коммерческие продукты, которые могут закрыть доступ к части документации.

Предлагаю поменять ссылки на государственные ресурсы, которые будут доступны бесплатно и всегда. 

- [Федеральный закон от 01.12.2014 г. № 419-ФЗ](http://www.kremlin.ru/acts/bank/39141)
- [Федеральный закон от 09.02.2009 г. № 8-ФЗ](http://www.kremlin.ru/acts/bank/28858)
- [Приказ Минкомсвязи России «Об установлении Порядка обеспечения условий доступности для инвалидов по зрению официальных сайтов федеральных органов государственной власти, органов государственной власти субъектов Российской Федерации и органов местного самоуправления в сети “Интернет”»](https://digital.gov.ru/ru/documents/4985/?utm_referrer=https%3a%2f%2fyandex.ru%2fsearch%2f%3fclid%3d1906725%26text%3d%25D0%259E%2b%25D0%259F%25D0%25BE%25D1%2580%25D1%258F%25D0%25B4%25D0%25BA%25D0%25B5%2b%25D0%25BE%25D0%25B1%25D0%25B5%25D1%2581%25D0%25BF%25D0%25B5%25D1%2587%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2b%25D1%2583%25D1%2581%25D0%25BB%25D0%25BE%25D0%25B2%25D0%25B8%25D0%25B9%2b%25D0%25B4%25D0%25BE%25D1%2581%25D1%2582%25D1%2583%25D0%25BF%25D0%25BD%25D0%25BE%25D1%2581%25D1%2582%25D0%25B8%2b%25D0%25B4%25D0%25BB%25D1%258F%2b%25D0%25B8%25D0%25BD%25D0%25B2%25D0%25B0%25D0%25BB%25D0%25B8%25D0%25B4%25D0%25BE%25D0%25B2%2b%25D1%2581%25D0%25B0%25D0%25B9%25D1%2582%25D0%25BE%25D0%25B2%2b%25D1%2584%25D0%25B5%25D0%25B4%25D0%25B5%25D1%2580%25D0%25B0%25D0%25BB%25D1%258C%25D0%25BD%25D1%258B%25D1%2585%2b%25D0%25BE%25D1%2580%25D0%25B3%25D0%25B0%25D0%25BD%25D0%25BE%25D0%25B2%2b%25D0%25B3%25D0%25BE%25D1%2581%25D1%2583%25D0%25B4%25D0%25B0%25D1%2580%25D1%2581%25D1%2582%25D0%25B2%25D0%25B5%25D0%25BD%25D0%25BD%25D0%25BE%25D0%25B9%2b%25D0%25B2%25D0%25BB%25D0%25B0%25D1%2581%25D1%2582%25D0%25B8%252C%2b%25D0%25BE%25D1%2580%25D0%25B3%25D0%25B0%25D0%25BD%25D0%25BE%25D0%25B2%2b%25D0%25B3%25D0%25BE%25D1%2581%25D1%2583%25D0%25B4%25D0%25B0%25D1%2580%25D1%2581%25D1%2582%25D0%25B2%25D0%25B5%25D0%25BD%25D0%25BD%25D0%25BE%25D0%25B9%2b%25D0%25B2%25D0%25BB%25D0%25B0%25D1%2581%25D1%2582%25D0%25B8%2b%25D1%2581%25D1%2583%25D0%25B1%25D1%258A%25D0%25B5%25D0%25BA%25D1%2582%25D0%25BE%25D0%25B2%2b%25D0%25A0%25D0%25BE%25D1%2581%25D1%2581%25D0%25B8%25D0%25B9%25D1%2581%25D0%25BA%25D0%25BE%25D0%25B9%2b%25D0%25A4%25D0%25B5%25D0%25B4%25D0%25B5%25D1%2580%25D0%25B0%25D1%2586%25D0%25B8%25D0%25B8%2b%25D0%25B8%2b%25D0%25BE%25D1%2580%25D0%25B3%25D0%25B0%25D0%25BD%25D0%25BE%25D0%25B2%2b%25D0%25BC%25D0%25B5%25D1%2581%25D1%2582%25D0%25BD%25D0%25BE%25D0%25B3%25D0%25BE%2b%25D1%2581%25D0%25B0%25D0%25BC%25D0%25BE%25D1%2583%25D0%25BF%25D1%2580%25D0%25B0%25D0%25B2%25D0%25BB%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2b%25D0%25B2%2b%25D0%25B8%25D0%25BD%25D1%2584%25D0%25BE%25D1%2580%25D0%25BC%25D0%25B0%25D1%2586%25D0%25B8%25D0%25BE%25D0%25BD%25D0%25BD%25D0%25BE-%25D1%2582%25D0%25B5%25D0%25BB%25D0%25B5%25D0%25BA%25D0%25BE%25D0%25BC%25D0%25BC%25D1%2583%25D0%25BD%25D0%25B8%25D0%25BA%25D0%25B0%25D1%2586%25D0%25B8%25D0%25BE%25D0%25BD%25D0%25BD%25D0%25BE%25D0%25B9%2b%25D1%2581%25D0%25B5%25D1%2582%25D0%25B8%2b%25E2%2580%259E%25D0%2598%25D0%25BD%25D1%2582%25D0%25B5%25D1%2580%25D0%25BD%25D0%25B5%25D1%2582%25E2%2580%259C%26lr%3d106076%26redircnt%3d1673867560.1)

**Comment by furtivite** [comment]
@TatianaFokina, @solarrust что думаете?

**Comment by TatianaFokina** [comment]
Почему бы и нет, но можешь тогда помочь найти [правильную ссылку на проект этого приказа](https://www.garant.ru/products/ipo/prime/doc/56820943/)? Та ссылка, что есть, это старый приказ, который отменяет вот этот новый.

**Comment by furtivite** [comment]
> Почему бы и нет, но можешь тогда помочь найти [правильную ссылку на проект этого приказа](https://www.garant.ru/products/ipo/prime/doc/56820943/)? Та ссылка, что есть, это старый приказ, который отменяет вот этот новый, который на Гаранте.

Проект ещё не вступил в законную силу, поэтому можем сохранить ссылку как есть, но добавить ссылку на существующую норму. К сожалению, пока не нашёл норму на официальном сайте.

**Comment by TatianaFokina** [comment]
Ок! Я тогда закину правки сегодня.

**Comment by furtivite** [comment]
> Ок! Я тогда закину правки сегодня.

Подари мне пиарчик?)

**Comment by TatianaFokina** [comment]
> Подари мне пиарчик?)

Замётано 🙂
