### ISSUE TITLE
Скринридеры (с примерами)

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#423]

**Comment by TatianaFokina** [comment]
Если никто ещё не нашёлся, могу взяться за эту статью.

**Comment by solarrust** [comment]
@TatianaFokina закрепила задачку за тобой! 
Пиши, если понадобится любая помощь! 🙏

**Comment by solarrust** [comment]
Абсолютна согласна по поводу шорткатов с уточнением при первом использовании. Звучит очень органично. Напомню на всякий случай, что обозначения клавиш нужно оборачивать в `<kbd>`. 

Очень жду статью! 🙌

**Comment by TatianaFokina** [comment]
solarrust, поняла, спасибо!
