### ISSUE TITLE
Свойство user-select

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#424]
Рассказать, что это за свойство, когда надо использовать, какие проблемы решает. Показать в демо работу свойства. Про экспериментальные или устаревшие значения можно не рассказывать.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
- https://css-tricks.com/almanac/properties/u/user-select/

**Comment by punkmachine** [comment]
Возьмусь.
