### ISSUE TITLE
Адаптировать схемы к тёмной теме в Гайде по grid (Figma)

### ISSUE THREAD

**Issue by rakleed** [doka-guide/content#4249]
### Ссылка на статью

https://doka.guide/css/grid-guide/

### Описание

В `Гайде по grid` схемы не адаптированы к тёмной теме ([требования к схемам](https://github.com/doka-guide/content/blob/main/docs/schemes.md)), из-за чего читать статью в тёмном помещении или ночью очень неприятно для глаз.

![image](https://user-images.githubusercontent.com/19418601/216856205-d7078cbd-b2f9-41b2-af51-55be29cfa9b1.png)

**Comment by solarrust** [comment]
Привет! Обязательно доберёмся до этих схем и адаптируем их.

**Comment by skorobaeus** [comment]
Исходники схем лежат на странице [🔥 Ждут исполнителя](https://www.figma.com/file/QkdJkiqJDWpQFCfY2AU6Pp/%D0%9F%D1%83%D0%B1%D0%BB%D0%B8%D1%87%D0%BD%D0%B0%D1%8F-%D0%94%D0%BE%D0%BA%D0%B0%3A-%D0%A1%D1%85%D0%B5%D0%BC%D1%8B?node-id=207%3A88) в фигме Доки. 

Со мной можно обсудить задачу и попросить помощи на любом этапе.

**Comment by skorobaeus** [comment]
Задачку забирает @StarHamster

**Comment by StarHamster** [comment]
👀
