### ISSUE TITLE
Добавить интерактивную демку в доку про `position`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#4317]
Добавить интерактивную демку в статью, в которой можно выбирать тип позиционирования и координаты элемента.

Параллельно посмотреть текст доки на предмет актуальности, переписать или дописать недостающее.

Можно перелинковать с докой про `inset`.

**Comment by AnnaBaraulina** [comment]
Привет! Есть ли дедлайн по задаче? Я бы хотела ее взять!

**Comment by solarrust** [comment]
Супер! Да, задачка актуальная, разве что ссылочка на `inset` уже есть. А демка очень нужна 🙏

**Comment by AnnaBaraulina** [comment]
> Супер! Да, задачка актуальная, разве что ссылочка на `inset` уже есть. А демка очень нужна 🙏

отлично, тогда попробую!
