### ISSUE TITLE
Добавить интерактивный пример в доку про `animation-name`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#4318]
Сейчас в доке очень мало инфы, предполагается, что читатель пойдёт читать большую статью про анимации. Лучше будет дополнить эту доку и привести там больше примеров использования. Можно также добавить интерактивный пример, в котором можно выбирать имя применяемой к элементу анимации и видеть изменения.

**Comment by goingtogogo** [comment]
привет! готова взять это ишью тоже🫡

**Comment by goingtogogo** [comment]
@TatianaFokina привет!) не уверена, кого нужно призывать тут и [здесь](https://github.com/doka-guide/content/issues/4321)
