### ISSUE TITLE
Плиточная раскладка на чистом CSS

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#4361]
## Тема

Как сделать masonry layout на CSS во времена с не очень хорошей поддержкой `grid-template-rows: masonry`.

У рецептов в Доке особая структура. В подразделе «Задача» описываем, что надо сверстать, в «Готовое решение» — добавляем финальный код и демку, в «Разбор решения» подробно рассказываем про решение.

Можете заглянуть [в рецепт «Разноцветный текст»](https://doka.guide/recipes/multicolor-text/) для вдохновения.

### Зачем

Частый запрос от дизайнеров.

## Полезные ссылки по тексту и демкам в Доке

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

**Comment by haiatov** [comment]
Готов взять

**Comment by alexTaraskina** [comment]
Привет! Хочу взять в работу

**Comment by TatianaFokina** [comment]
> Привет! Хочу взять в работу

Привет, супер!

**Comment by solarrust** [comment]
@alexTaraskina Привет! Как дела с этим рецептом? Нужна ли какая-то помощь?

**Comment by alexTaraskina** [comment]
@solarrust привет! Всё под контролем, помощь пока не нужна) Постараюсь на неделе закончить
