### ISSUE TITLE
Как добавить фавиконку на сайт

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#4370]
### Тема

Как правильно добавить фавиконку на сайт. Плюс чтобы она изменялась в зависимости от выбранной темы в браузере/системе. 

### Зачем

Фавиконка ну очень часто встречающаяся штука в вебе.

**Comment by s-pyadyshev** [comment]
За основу можно взять https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
