### ISSUE TITLE
Ошибка в `async/await`

### ISSUE THREAD

**Issue by maridoroshuk** [doka-guide/content#4398]
### Ссылка на статью

https://doka.guide/js/async-await/

### Описание

> ☝️ Ключевое слово await работает только внутри асинхронных функций. Вызов его вне функции будет синтаксической ошибкой:
```
function getMainActorProfileFromMovie(id) {
  // код примера выше
}

await getMainActorProfileFromMovie(1)
```

c ES2022 разрешено использовать await на верхнем уровне, не будет возникать SyntaxError и код выполнится

### Пруфы

https://262.ecma-international.org/13.0/

https://habr.com/ru/articles/651161/ (№3)

![image](https://user-images.githubusercontent.com/59647513/232427437-31295e1b-e1ee-4ec3-98d1-8cc0dea5dc43.png)

**Comment by vitya-ne** [comment]
Привет, я могу взять этот тикет ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять этот тикет ?

А то! Закреплено за тобой.
