### ISSUE TITLE
aria-роль `blockquote`

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#4404]
В доке можете рассказать про то, для чего нужна эта роль, у какого HTML-тега она есть по умолчанию, привести пример кода (будет круто, если сделаете ещё и демку), какие ARIA-свойства можно использовать и для чего, какие есть особенности и подводные камни.

Ссылки для старта:

- https://www.w3.org/TR/wai-aria-1.2/#blockquote
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/structural_roles
- https://doka.guide/html/blockquote/
- https://doka.guide/a11y/aria-roles/
- https://a11ysupport.io/

Полезные ссылки по тексту и демкам в Доке:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
- [Подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

**Comment by alexTaraskina** [comment]
Привет, хочу взять эту задачу в работу

**Comment by TatianaFokina** [comment]
> Привет, хочу взять эту задачу в работу

Привет, круто! Закрепляю задачку за тобой.

Пиши, если нужна будет помощь. Пара полезных ссылок:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
