### ISSUE TITLE
Тег `<search>`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#4425]
### Тема

Новый тег `<search>` 
- https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element
- https://alvaromontoro.hashnode.dev/new-html-element-search

### Зачем

В Доке обязательно нужно рассказать о новом теге, потому что мало где он описан.

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by AndreySukhov** [comment]
Готов взять в разработку

**Comment by AndreySukhov** [comment]
привет, как раз разобрался с делами и появилось время вернуться к статье
