### ISSUE TITLE
Атрибуты `defer`, `async` и разница между ними

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#444]

**Comment by ra1nbow1** [comment]
Могу начать хоть сейчас

**Comment by pepelsbey** [comment]
@nlopin у вас были планы о чём-то таком писать?

**Comment by solarrust** [comment]
Привет!
Прости, что долго пришлось ждать ответа — новогодние каникулы =)
Должна получиться очень интересная дока, буду очень ждать!

**Comment by ra1nbow1** [comment]
@solarrust привет еще раз. Думаю, как можно понятно и кратко назвать статью. Может "Разница между `defer` и `async`?". Я правильно понимаю, что она для раздела "Глобальные атрибуты"?

**Comment by ra1nbow1** [comment]
@solarrust =)

**Comment by solarrust** [comment]
Ох, пропустила уведомление. Извини, пожалуйста.
Я бы предложила название «Атрибуты `defer` и `async`». Не будем спойлерить всю интригу в заголовке =)
Это не универсальные атрибуты, они подходят только для скриптов. Так что скорее разместим статью в подраздел «Связи с другими языками».

**Comment by ra1nbow1** [comment]
Хорошо, а каким примерно должно быть содержание?

**Comment by solarrust** [comment]
1. Обозначаем проблему
2. Атрибут 1: принцип работы, плюсы-минусы
3. Атрибут 2: принцип работы, плюсы-минусы
4. Сравнение когда какой использовать

Примерно так. Можешь изменять структуру смело, если посчитаешь нужным!

**Comment by ra1nbow1** [comment]
Привет. Очень много дел сейчас появилось. В ближайшее время точно не смогу доку написать. Если это критично, наверное, нужно закрепить эту статью за другим желающим

**Comment by ra1nbow1** [comment]
@solarrust , принимай работу) #2815
