### ISSUE TITLE
Рецепт: массив из 100 котиков

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4450]
### Тема

Привести несколько способов создать массив из большого количества повторяющихся элементов

### Зачем

Это очень распространенная задача

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by Sapfir0** [comment]
Попробую взять

**Comment by solarrust** [comment]
Мы поможем с написанием! Задавай любые вопросы, можем всё обсуждать =)

**Comment by Sapfir0** [comment]
Есть несколько разных способов для создания массива с котиками) Допустим, нам нужно завести котиков в 100 комнату, по одному на комнату, как это сделать? Можно выделить место (память) для котиков, а потом заселить туда котиков:
Array(100).fill("😸")  // Чуть более функциональный стиль

Также мы можем выделить 100 комнат, а потом пройти в каждую и руками туда посадить кота. 
const mapper = () => "😸"
[...Array(100)].map(mapper)
Array.from(Array(100), mapper)

Можно создать пустой массив, создать цикл и поселить в каждую комнату по ее индексу по коту
const arr = []
for(let i=0; i<100;i++){
    arr[i] = "😸"
}


Будет еще дорабатываться)

**Comment by HellSquirrel** [comment]
Мяу! Когда будет готово, велкам открыть PR по вот этой инструкции https://github.com/doka-guide/content/blob/main/docs/interviews.md. Ну или просто призови меня сюда и я все сделаю

Псст, а есть еще Array.form({ length: 100}, () => '🐈')

**Comment by Sapfir0** [comment]
Написал, можешь посмотреть, пожалуйста?

**Comment by HellSquirrel** [comment]
Написали, молодцы :)
