### ISSUE TITLE
Дока про WeakMap

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4451]
### Тема

Хочется добавить доку про WeakMap

https://tc39.es/ecma262/multipage/keyed-collections.html#sec-weakmap-objects - референс

### Зачем

Очень полезная структура данных

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by vsezol** [comment]
Беру эту тему

**Comment by HellSquirrel** [comment]
Написали
