### ISSUE TITLE
Вопрос для собеседования: Как отфильтровать не уникальные элементы в коллекции

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4453]
### Вопрос

Есть коллекция произвольных объектов. Вам нужно выкинуть все не уникальные элементы.
Порядок не важен

### Кто ответит на вопрос

- [ ] Я знаю ответ!

**Comment by egordidenko** [comment]
Беру!

**Comment by egordidenko** [comment]
@HellSquirrel привет! 

Есть ли входные данные для примера?

**Comment by HellSquirrel** [comment]
@egordidenko отсутствие входных данных это как раз важная часть вопроса. Я предложу начать с 
[1,2,2,3,3,4,5]

продолжить
[1,2,3,4,5,6]

потом попробовать
[1,2,'test', 'foo', 2, 3]

потом 
[{ foo: 'bar' }, { foo: 'bar'}, { foo: 'baz' }]

Дальше можно подумать о том что такое коллекция и для каких кейзов ее вообще надо фильтровать

**Comment by skorobaeus** [comment]
Вопрос добавлен на платформу в ПР #5124

**Comment by vitya-ne** [comment]
@HellSquirrel у меня вопрос:
[{ foo: 'bar' }, { foo: 'bar'}] - это коллекция из 2х уникальных элементов или по условию задачи они равны ?

**Comment by HellSquirrel** [comment]
Отличный вопрос. Так как это раздел про собеседование, то ожидаются вопросы с подвохом. Вот ты его как раз нашел. Ответ - рассмотри оба варианта. Если приведенная тобой коллекция содержит один уникальный элемент, что будет делать?
