### ISSUE TITLE
Вопрос для собеседования: Является ли JavaScript интерпретируемым языком?

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4456]
### Вопрос

Является ли JavaScript интерпретируемым языком?

Вопрос создан чтобы раскрыть популярные заблуждения.
Ответ: Да и Нет

### Кто ответит на вопрос

- [ ] Я знаю ответ!

**Comment by eshevlyakova** [comment]
Это должно быть оформлено как статья с подробным ответом?

**Comment by TatianaFokina** [comment]
> Это должно быть оформлено как статья с подробным ответом?

Нет, как ответ. Пример есть, например, [в статье про `const`, `let` и `var`](https://doka.guide/js/var-let/#na-sobesedovanii).

Можно ещё заглянуть [в инструкцию как добавить ответ](https://github.com/doka-guide/content/blob/main/docs/interviews.md).
