### ISSUE TITLE
Не хватает материала о Deno

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4458]
### Тема

Deno - популярный JS-рантайми. Давайте о нем расскажем

### Зачем

no-de -> de-no

Если серьезно, у deno множество интересных особенностей и архитектурных решений

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by IrenKova** [comment]
попробуем

**Comment by DreamShaded** [comment]
Готов взяться!

**Comment by furtivite** [comment]
@DreamShaded, лови)

**Comment by solarrust** [comment]
@DreamShaded  привет! Как дела с этим материалом? Нужная какая-то помощь?

**Comment by DreamShaded** [comment]
@solarrust приветищее ^^ 

Пока техаю статью, собираю из уже созданных статей + видео и поставил заодно себе, попробовать, оценить)

**Comment by solarrust** [comment]
Нет, никакой спешки. Просто хотела уточнить, не поменялись ли у тебя планы и не пропало ли желание писать. Будем ждать пиар! ♥️

**Comment by solarrust** [comment]
@DreamShaded пинг по этой задачке =)

**Comment by DreamShaded** [comment]
> @DreamShaded пинг по этой задачке =)

Туть! Сделаю! Конфы закончились))

**Comment by solarrust** [comment]
@DreamShaded пока откреплю задачку. Возвращайся, как будет время и желание =)

**Comment by DreamShaded** [comment]
@solarrust а я дописываю прям ща)

**Comment by DreamShaded** [comment]
@solarrust https://github.com/doka-guide/content/pull/5438 тада! Не прошло и года! :rofl:

**Comment by zoto-ff** [comment]
тогда нужно еще и [Bun](https://bun.sh), он лучше и популярнее дено

**Comment by DreamShaded** [comment]
@zoto-ff согласен, да) но это отдельной статьёй нужно)
