### ISSUE TITLE
Ошибка в статье Пишем первые тесты

### ISSUE THREAD

**Issue by bohdanyezhlov** [doka-guide/content#4480]
Указана неверная ссылка. На данный момент ссылки на первое и третье видео ведут на одно и то же видео

https://github.com/doka-guide/content/blob/bfef65aae293b6a1bb7440ab1bb6388fefad928d/tools/testing-with-jest/index.md?plain=1#L29

**Comment by TatianaFokina** [comment]
Закрою это ишью как дубль #4690.
