### ISSUE TITLE
Ошибка в статье про ссылку

### ISSUE THREAD

**Issue by vetero4eg** [doka-guide/content#4500]
### Ссылка на статью

https://doka.guide/html/a/#alyona-batickaya-sovetuet

### Описание

Эта часть статьи содержит ряд неточностей.

По спецификации ссылка **не является** по умолчанию строчным элементом. Ссылка является элементом с прозрачной контентной моделью, то есть то, какой будет display  у ссылки по умолчанию зависит от его родителя. Так "умолчательный" display у ссылки, которая является прямым потомком flex или grid родителя - будет **block**, и такая ссылка будет адекватно реагировать на отступы, задание размеров  и прочие вещи,с которыми у строчных элементов проблемы. [Пример.](http://joxi.ru/DmBZw04UPke9km)

Также и в других материалах статьи ссылка упоминается как однозначно строчный по умолчанию элемент, например тут https://doka.guide/html/flow/

> Поскольку ссылка строчная, лучше вкладывать её в блочный элемент, а не наоборот. Для примера возьмём заголовок, который должен быть ссылкой.

Тут во-первых, из сказанного выше, ссылка не всегда строчная. Во-вторых спецификация разрешает использование внутри ссылки любого контента, в [примере из спецификации](http://joxi.ru/8AnbQ9WC09D1VA) в ссылку вкладывают не только заголовок, но и целую секцию, главное условие - одно, чтобы внутри ссылки не было иных интерактивных элементов, а также [элементов с указанным tabindex](http://joxi.ru/brRKBpjcVRKJWm), поэтому пример ["плохо"](http://joxi.ru/KAgBNX0CeGQ4o2) излишне категоричный.

### Пруфы

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element
https://html.spec.whatwg.org/multipage/dom.html#transparent
Пример на кодпене https://codepen.io/vetero4eg/pen/XWyXvJq

**Comment by solarrust** [comment]
Привет! Очень крутое уточнение! Принесёшь пулреквест с исправлениями в упомянутые статьи?

**Comment by vetero4eg** [comment]
Не уверена, что бегом и что правильно все оформлю, но постараюсь сделать и не сильно затягивать

**Comment by solarrust** [comment]
Я помогу с редактурой текста, не беспокойся об этом. Присылай как тебе будет удобно ♥️

**Comment by SelenIT** [comment]
> Так "умолчательный" display у ссылки, которая является прямым потомком flex или grid родителя - будет **block**, и такая ссылка будет адекватно реагировать на отступы, задание размеров и прочие вещи,с которыми у строчных элементов проблемы.

Это никак не связано с моделью содержимого. Обычный `span` на ее месте точно так же неявно получит `display:block`, потому что флекс- и грид-элементы всегда [блокифицируются](https://drafts.csswg.org/css-display/#transformations) и их display перестает быть дефолтным. В обычном же блочном контейнере ссылка, незавсимо от содержимого, останется с дефолтным `display:inline`. Никакой магической связи между моделью содержимого и дефолтными стилями не существует, в дефолтных стилях браузеров нет никаких особых правил для ссылок в зависимости от их родителя, а тем более от их содержимого (как и в [рекомендациях по рендерингу из спеки HTML](https://html.spec.whatwg.org/#phrasing-content-3)).

Учитывая, что в HTML сейчас понятия «блочный» и «строчный» не используются вообще, я не вижу проблемы называть ссылку строчным по умолчанию элементом — у нее дейстительно `display:inline` по умолчанию, и вложение в нее чего-то блочного может вызвать те же проблемы _в CSS_, что и вложение `div` в `span` (например, появление неуправляемой [анонимной блочной обертки](https://drafts.csswg.org/css-display/#anonymous)), если только прямо или косвенно (как в вашем примере с флекс-контейнером) не поменять ей `display`.

Насчет категоричности «плохого примера» — да, формально спецификация больше не считает ошибкой целую секцию в ссылке. Но можно — не значит нужно, а для доступности такая верстка действительно создает проблемы (к тому моменту, когда скринридер дочитает эту простыню текста и объявит, что это ссылка, пользователь забудет начало и запутается). Поэтому рекомендация не делать так _без действительно крайней нужды_, на мой взгляд, вполне актуальна. Другое дело, что, может быть, стоит пояснить, что это не строгое требование стандарта, а рекомендация по доступности.

**Comment by vetero4eg** [comment]
Частично согласна, тут связь скорее  с блокификацией... Исправлюсь, спасибо за замечание.

Блочный и строчный они не очень то про html и семантику, верно. Но специфика поведения - есть.  И либо мы полностью уходим от этой терминологии и не называем ссылки и что-либо строчным элементом, либо все-таки отмечаем,  как минимум в формате материалов о флексах и гридах, раз это таки из специфика, а не ссылки, что может быть вот так. Признаю, что ошиблась, связывая эти особенности с моделью содержимого.

**Comment by SelenIT** [comment]
Подумал, что дело во многом в определении понятия «по умолчанию» 😳. Либо это «если ничего специально не делать с самим элементом», либо «если не подключать никаких стилей, кроме встроенных браузерных». Лично я склоняюсь ко второй трактовке, потому что в первом случае получается, что почти все элементы могут менять «дефолтное» поведение в зависимости от контекста. А вот `display` во встроенных стилях браузера — штука достаточно однозначная. В статье про [поток документа](https://doka.guide/html/flow/), например, элементы тоже классифицируют (с оговоркой «условно») именно по встроенным браузерным стилям.

Полностью уйти от блочности/строчности, наверное, будет сложно — люди всё равно оперируют этими категориями, это уже слишком устоявшаяся традиция 😳. Да и общее правило, что строчное содержимое бывает в блочных контейнерах, а не наоборот, в целом полезная эвристика (даже со знанием, что семантика с этим связана лишь очень косвенно, а из самого правила бывают исключения). Но упоминание, что это дефолтное поведение может меняться, в т.ч. неявно, действительно нужно. Может быть, нужна отдельная небольшая статья про блокификацию и инлайнификацию, на которую можно ссылаться в статьях про гриды, флексы, и вообще везде, где нужно?

**Comment by vetero4eg** [comment]
Согласна, тут тонкое место, помещая ту же ссылку в грид мы вроде бы и тоже ничего не делаем, но...  браузерные стили display не несут для той же ссылки, а вот computed стиль начинает меняться.
Нужно что-то на эту тему, да. Подумаю как лучше сделать
