### ISSUE TITLE
Неточность в доке про `<header>`

### ISSUE THREAD

**Issue by Jan6o** [doka-guide/content#4569]
### Ссылка на статью

https://doka.guide/html/header/

### Описание

Header - это не шапка сайта 
header, footer - это спец группа  которые обозначают  специфику контента , которая содержится  внутри них 
сообщает в рамках семантике  поисковой машине о том что весь контент  внутри этой группы  ни имеет ни какого прямого отношения  к выполнению задачи  раскрытия  основного контента на текушей странице.Header так может использоваться  в любой части сайта  в зависимости  от цели которые преследует верстальщик, скорее всего я не правильно расписал, но мысль и смысл семантики передал.Html5 это нет только метод построения сайта ,а также способ передачи информаций машине тем  образом как видит ее человек так что бы другой кто обладет теми же знаниями мог также показать контент или понять основной посыл 

### Пруфы

https://html.spec.whatwg.org/multipage/sections.html#the-header-element

**Comment by solarrust** [comment]
Привет. Спасибо за твоё желание улучшать Доку. Можешь, пожалуйста, принести пулреквест с правками в статью? Я пока не очень вижу противоречия между текущим текстом статьи и твоим комментарием. В тексте нет утверждения, что header — обязательно шапка статьи. В первом же предложении сказано, что это может быть отдельный элемент любого блока. Возможно, в исправленном тексте это будет более очевидно.

**Comment by solarrust** [comment]
@Jan6o не дождалась от тебя ответа или пулреквеста. Пока ишью закрываю. Пожалуйста, создай его заново и предложи исправление там, где видишь противоречия. Можно в свободной форме, я подхвачу и отредактирую.
