### ISSUE TITLE
Не хватает материала о свойстве `rotate`

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#4614]
### Тема

Рассказать про то, что это за свойство, зачем нужно, как его правильно использовать, сравнить с `transform: rotate()`.

### Зачем

Свойство уже давно существует, а доки про него нет 😔

### Ссылки для старта

https://developer.mozilla.org/en-US/docs/Web/CSS/transform
https://css-tricks.com/almanac/properties/r/rotate/

**Comment by 29deepanshutyagi** [comment]
пожалуйста, поручите мне эту проблему @doka-guide, я могу поработать над этой проблемой

**Comment by StarHamster** [comment]
@solarrust, заасайнишь? 👉👈

**Comment by TatianaFokina** [comment]
> пожалуйста, поручите мне эту проблему @doka-guide, я могу поработать над этой проблемой

Закрепила задачку.

**Comment by nasty23-star** [comment]
беру эту тему

**Comment by solarrust** [comment]
@nasty23-star закрепила за тобой! 🙌
