### ISSUE TITLE
Ошибка в статье про псевдокласс «:has»

### ISSUE THREAD

**Issue by wonder-SMA** [doka-guide/content#4619]
### Ссылка на статью

https://doka.guide/css/has/

### Описание

В части статьи [Кратко](https://doka.guide/css/has/#kratko) указано, что _"Псевдокласс :has() позволяет выбрать элемент, уточнив основной селектор дополнительным, и при этом **не увеличив его вес**."_

и

в части статьи [Подсказки](https://doka.guide/css/has/#podskazki) указано, что "Использование :has() **не влияет** на [специфичность](https://doka.guide/css/specificity/), т. е. при расчёте веса селектора учитывается только целевой селектор, к которому применяется этот псевдокласс.".

Это не так, псевдокласс :has() принимает специфичность наиболее конкретного селектора в своих аргументах так же, как это делают :is() и :not().

### Пруфы

https://developer.mozilla.org/en-US/docs/Web/CSS/:has

_"The :has() pseudo-class takes on the [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) of the most specific selector in its arguments the same way as [:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) and [:not()](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) do."_

![image](https://github.com/doka-guide/content/assets/61292853/e5565fc8-46b3-44be-8ffe-603f42c5780e)
![image](https://github.com/doka-guide/content/assets/61292853/f3326233-38bb-49af-a209-939b8b7c0425)

**Comment by TatianaFokina** [comment]
@wonder-SMA, привет! А хочешь сам закинуть пулркувест с исправлениями? Это было бы очень круто.

**Comment by wonder-SMA** [comment]
> @wonder-SMA, привет! А хочешь сам закинуть пулркувест с исправлениями? Это было бы очень круто.

Привет! Готово 🙂

**Comment by TatianaFokina** [comment]
> Привет! Готово 🙂

О-о-о-о, супер! Спасибо огромное.
