### ISSUE TITLE
Свойство `backface-visibility`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#462]
Расширить плейсхолдер, рассказать, какие проблемы решает это свойство, когда пригодиться. В демо показать разницу между трансформированными элементами с этим свойством и без него. Какие значения может принимать, а какие нет.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility
- https://css-tricks.com/almanac/properties/b/backface-visibility/

**Comment by slavkapiyavka** [comment]
привет! могу взять задачу в работу.
в каком формате могу сделать демку? на своём codepen выложить?
