### ISSUE TITLE
Не хватает рецепта о темной теме

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#4620]
### Тема

Написать рецепт о том, как добавить на свой сайт поддержку тёмной темы, которая будет зависеть от устройства пользователя. 

### Зачем

Много пользователей поставили себе на устройство тёмную тему, но на Доке нет статьи, как эту тему настроить.

1. Нет отдельной статьи про медиа-выражение `prefers-color-scheme` (https://caniuse.com/?search=prefers-color-scheme)
2. Нет отдельной статьи про css-свойство `color-scheme` (https://caniuse.com/?search=color-scheme)

Можно добавить и кнопку переключения стилей

### Кто напишет материал

- [X] Я сам напишу этот материал

**Comment by TatianaFokina** [comment]
А твоё ишью отличается от моего? https://github.com/doka-guide/content/issues/4367

**Comment by furtivite** [comment]
Сорри, я что-то искал и не нашел)
