### ISSUE TITLE
Сыпется Maintainer Helper

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#4622]
Экшен [Maintainer Helper](https://github.com/doka-guide/content/actions/workflows/maintainer-helper.yml) уже как три недели перестал работать:

![image](https://github.com/doka-guide/content/assets/91747573/b4a4a5a5-a45b-4dad-8368-3aec0c1a8b1b)

**Comment by TatianaFokina** [comment]
@igsekor, и с продакт деплоем тоже проблемы.

**Comment by TatianaFokina** [comment]
Больше не сыпется, ееее.
