### ISSUE TITLE
Изменить анимацию появления шапки на сайте

### ISSUE THREAD

**Issue by denisputnov** [doka-guide/content#4623]
Привет, у `.header` есть переменная `--header-animation-time: 0.6s;`

Не совсем понятно, откуда взялось это время
Пользуясь сайтом, часто замечал, что с хедером что-то не то, ощущается заторможенным
Изменил время на 0.3s, выглядит лучше

Решил погуглить best practice о UX анимаций, выяснил следующее:
Оптмальным временем является диапазон от 100 до 400мс, где 400 - это уже очень долго

Так вот, почему 600 стоит? Может имеет смысл поменять? Не думаю, что я единственный, кого такая длинная анимация раздржает)

**Comment by TatianaFokina** [comment]
@denisputnov, ты не одинок! Мы планировали что-то придумать с анимацией шапки. Спасибо за то, что снова поднял эту тему.

**Comment by TatianaFokina** [comment]
Добавила твой комментарий [в ишью в платформе с этой проблемой](https://github.com/doka-guide/platform/issues/979). Так что закрою дубль.
