### ISSUE TITLE
Вопрос для собеседования: Функция, которая принимает любое количество аргументов и возвращает их сумму.

### ISSUE THREAD

**Issue by arudenkoofficial** [doka-guide/content#4641]
### Вопрос
Напишите функцию, которая принимает любое количество аргументов типа `string` или `number` и возвращает их сумму, если все аргументы являются числами, или конкатенирует их по правилам JS, если хотя бы один аргумент является строкой.
```
1,2,5 => 8
1,2,'5' => '35'
'1', 2, 5 => '125'
```
### Кто ответит на вопрос
- [x] Я знаю ответ!

**Comment by arudenkoofficial** [comment]
Это задача, которая встречалась мне на собеседованиях. Она отлично подходит для демонстрации работы метода .reduce()

**Comment by Raadius** [comment]
// для того, чтобы работать с любым числом используем устаревший arguments
// и преобразуем его спред-оператором в массив сразу
// и редьюсом переданный коллбэк у нас каждое значение суммирует
// а из-за приведения типов в js у нас конкатенация будет срабатывать

function addEverything(...args) {
  return args.reduce(function(currentSum, currentNumber) {
    return currentSum += currentNumber;
  })
};
