### ISSUE TITLE
skorobaeus нет в CODEOWNERS

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#4643]
Предлагаю добавить Свету в CODEOWNERS, чтобы её автоматически назначало ревьюиром, когда изменяют демки, с помощью следующей строки:

```
**/demos @skorobaeus 
```

**Comment by TatianaFokina** [comment]
Хорошая идея, поддерживаю.

**Comment by igsekor** [comment]
Тоже поддерживаю #4649
