### ISSUE TITLE
::marker

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#467]

**Comment by lordoys** [comment]
**Привет 👋 !**

Готов взять на себя.

**Comment by solarrust** [comment]
Привет!
Буду очень рада доке твоего авторства. 
Пиши, если нужна будет любая помощь =)

**Comment by solarrust** [comment]
@lordoys привет! Планируешь написать эту доку? Если нет — ничего страшного. Скажи и я откреплю задачу =)

**Comment by BlueInGreen68** [comment]
Привет! Готов взяться.

**Comment by solarrust** [comment]
@BlueInGreen68 просто нет слов ♥️

**Comment by BlueInGreen68** [comment]
@solarrust просто так вышло, что счётчики и псевдоэлемент `::marker` в одной спецификации описываются) И ещё, не подскажешь, во многих доках изображения как будто в одной и той же программе делают, хотелось бы узнать в какой. Спасибо!

**Comment by solarrust** [comment]
А можешь, пожалуйста, показать пример изображения, о котором ты спрашиваешь? А то у нас много всякого встречается в доках 😅

**Comment by BlueInGreen68** [comment]
1. [Как работают скринридеры](https://doka.guide/html/screenreaders/#kak-rabotayut-skrinridery).
1. [Выражения и инструкции](https://doka.guide/js/expressions-vs-statements/).
1. [text-rendering](https://doka.guide/css/text-rendering/).

**Comment by solarrust** [comment]
А, поняла, ты про схемы! Их рисуют наши дизайнеры. Ты можешь сделать набросок в любой программе, где тебе удобнее. А дизайнер потом дойдёт до этой статьи и перерисует красиво, в нашем стиле.
