### ISSUE TITLE
Неверная ссылка в статье "Пишем первые тесты"

### ISSUE THREAD

**Issue by gernowoy** [doka-guide/content#4690]
### Ссылка на статью

https://doka.guide/tools/testing-with-jest/

### Описание

В разделе "Как начать писать тесты?" есть ссылки на три видео.
Первая и третья ссылки ведут по одному адресу:

[Пишем первый тест в проект](https://youtu.be/-7G6WBYaTeU),
[Пишем тест для асинхронного кода](https://youtu.be/OSX9Fbr6faE),
[Пишем тест для работы с DOM](https://youtu.be/-7G6WBYaTeU).

**Comment by Lensco825** [comment]
Отличная работа по поиску этой проблемы, но для того, чтобы решить эту проблему, нам нужно найти ссылку на видео "Написание теста для работы с DOM". Вы, возможно, знаете, что это за ссылка?

**Comment by gernowoy** [comment]
Не могу знать, видео вероятно unlisted' ,как видео по другим ссылкам. Пусть владелец ютуб-канала доки поищет его.
