### ISSUE TITLE
Ошибка в `.removeEventListener()`

### ISSUE THREAD

**Issue by beardy-raccoon** [doka-guide/content#4732]
### Ошибка в статье ".removeEventListener()"

https://doka.guide/js/element-removeeventlistener/#egor-ogarkov-sovetuet

### Описание

В самом последнем примере в обработчик перелается неправильное название функции (объявлено handleKeypress, а перелается handleClick).

<img width="991" alt="Screenshot 2023-09-21 at 01 12 22" src="https://github.com/doka-guide/content/assets/77743494/607f0ac5-fde8-4c31-b905-4f095c30d6ac">

**Comment by artbutko** [comment]
поправил в #4765
