### ISSUE TITLE
Атрибут `dir`

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#4748]
## Тема

Рассказать и показать на примерах, как работает глобальный атрибут `dir` и для чего его используют. Перелинковать со статьями про `<bdo>` и `<bdi>`.

### Ссылки для старта

- https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir
- https://www.w3.org/International/questions/qa-html-dir

### Зачем

Неплохо было бы завести такой материал на Доке, тем более что атрибут упоминается в других статьях. Плюс есть связанное с ним ишью в разделе CSS.

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by s-dudko** [comment]
@TatianaFokina, привет. Можно взять?
