### ISSUE TITLE
Неправильная ссылка на linear-gradient в разделе: "Градиент на фоне"

### ISSUE THREAD

**Issue by Gre7** [doka-guide/content#4791]
### Ссылка на статью

https://doka.guide/css/background-image/

### Описание

На странице с описанием "background-image" в разделе "Градиент на фоне", неверная ссылка на linear-gradient, вместо него, ссылка ведет на "line-height"

**Comment by solarrust** [comment]
Спасибо большое, что подметил эту ошибку. Принесёшь правку?

**Comment by Gre7** [comment]
> Спасибо большое, что подметил эту ошибку. Принесёшь правку?

Да, конечно.

**Comment by TatianaFokina** [comment]
Исправила в другом ишью https://github.com/doka-guide/content/issues/5093.
