### ISSUE TITLE
Расширяем материалы о многопоточности в JavaScript: Atomics

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4798]
### Тема
Atomics:
https://tc39.es/ecma262/multipage/structured-data.html#sec-atomics-object

### Зачем

Расширяем материалы о многопоточности в JavaScript

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by vsezol** [comment]
Привет, хочу взять эту тему. Недавно делал доклад, где затрагивал Atomics. Есть что рассказать

**Comment by TatianaFokina** [comment]
> Привет, хочу взять эту тему. Недавно делал доклад, где затрагивал Atomics. Есть что рассказать

Хватай!
