### ISSUE TITLE
Вопрос по статье "Как устроена память" 

### ISSUE THREAD

**Issue by fpetrakov** [doka-guide/content#4803]
### Ссылка на статью

https://doka.guide/tools/trivial-memory-model/

### Описание

Привет, пара вопросом по этому кусочку:

> Для этого на стеке создаётся stack_frame. В нём хранятся аргументы и локальные переменные.

1. Это значит, что стек фрейм может содержать только аргументы и только локальные переменные? Если да, то, кажется, есть же еще глобальный фрейм, в котором могут храниться, например, глобальные переменные. 

2. Стек фрейм, контекст выполнения и окружение. В чем разница между этими понятиями? 

### Пруфы

https://262.ecma-international.org/5.1/#sec-10.4.1.1

**Comment by HellSquirrel** [comment]
Приветик. Чуть попозже отпишусь )

**Comment by HellSquirrel** [comment]
Замечательные вопросы! приноси такие еще 🤗
> Это значит, что стек фрейм может содержать только аргументы и только локальные переменные? Если да, то, кажется, есть же еще глобальный фрейм, в котором могут храниться, например, глобальные переменные.

Глобального фрейма (в модели описанной в статье) нет. Но есть отдельная область памяти, куда сложено все глобальное. Вот тут в статье об этом написано

> В этот кусочек памяти загружается код программы, глобальные переменные и ещё кое-что. В этом же кусочке памяти выделяются две важные области: стек (stack) и куча (heap). Стек — это область памяти, которую очень легко выделять.

> Стек фрейм, контекст выполнения и окружение. В чем разница между этими понятиями?
Опять же для модели в статьи - мы говорим про стек фреймы и стек выполнения. Как это мапится на JavaScript
Вот тут, спека описывает примерно ту же самую штуку https://tc39.es/ecma262/#sec-execution-contexts. Т.е execution context это примерно то же что и stack frame

**Comment by fpetrakov** [comment]
@HellSquirrel понял, спасибо за развернутый ответ :)
