### ISSUE TITLE
Атрибут `placeholder`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#481]
Подробно поговорить про атрибут `placeholder`. Рассмотреть уместные ситуации его использования, способы стилизации. Важно проговорить как с ним работает скринридер, что не стоит в форме использовать только его, но не лейблы. Дать подсказку про контрастность цвета плейсхолдера по шкале доступности.
Дать список тегов, к которым этот атрибут может быть применим.

**Comment by MariannaSpb** [comment]
Привет! Готова взять на себя

**Comment by solarrust** [comment]
Кайф!
Тебе может пригодиться [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
Пожалуйста, пиши если понадобиться любая помощь!
