### ISSUE TITLE
Ошибка в попапе "Первый вклад в Доку"

### ISSUE THREAD

**Issue by ITDOGTOR** [doka-guide/content#4810]
### Ссылка на статью

https://doka.guide/people/solarrust/

### Описание

Похоже на то, что слетела дата на 1 января 1970. Это не только на этой странице, я посмотрел несколько и кого-то нормально, а у кого-то 1 января 1970 стоит.

### Пруфы

![image](https://github.com/doka-guide/content/assets/38471794/e0d23633-c924-4ea3-80ca-776bad191b13)

**Comment by solarrust** [comment]
Привет! Да, знаем об этой баге, спасибо что подсветил. 
Это ишью относится к разработке платформы. В репозитории https://github.com/doka-guide/platform/ уже есть [аналогичное ишью](https://github.com/doka-guide/platform/issues/1205). Можешь докинуть туда свои скриншоты, чтобы у нас было больше кейсов для тестирования. 
В этом репозитории ишью закрою.
