### ISSUE TITLE
Методы массива: copyWithin

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4814]
### Тема
Методы массива: copyWithin

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> привет, я могу взять эту доку ?

Конечно! Закрепляю за тобой.
