### ISSUE TITLE
Методы массива: entries

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4815]
### Тема
Методы массива: entries

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> привет, я могу взять эту доку ?

Бери. Ты всерьёз взялся за массивы!

**Comment by vitya-ne** [comment]
> > привет, я могу взять эту доку ?
> 
> Бери. Ты всерьёз взялся за массивы!

обожаю массивы!
