### ISSUE TITLE
Методы массива: findLastIndex

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4818]
### Тема
Методы массива: findLastIndex

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> привет, я могу взять эту доку ?

Да-а-а-а! Закреплено.
