### ISSUE TITLE
Методы массива: join

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4819]
### Тема
Методы массива: join

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> привет, я могу взять эту доку ?

Для тебя методов массивов никогда не жалко!

**Comment by vitya-ne** [comment]
> > привет, я могу взять эту доку ?
> 
> Для тебя методов массивов никогда не жалко!

Спасибо, я ценю это )
