### ISSUE TITLE
Методы массива: slice

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4825]
### Тема
Методы массива: slice

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> привет, я могу взять эту доку ?

Привет, конечно да! Ты тут главный по методам массивов, как-никак.
