### ISSUE TITLE
Методы массива: toReversed

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4829]
### Тема
Методы массива: toReversed

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
Привет, я могу взять эту доку?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять эту доку?

Твоё второе имя точно продуктивность. Закреплено!
