### ISSUE TITLE
Методы массива: toSpliced

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4831]
### Тема
Методы массива: toSpliced

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
Привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять эту доку ?

Дыааа, закреплено.
