### ISSUE TITLE
Методы массива: toString

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4832]
### Тема
Методы массива: toString

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
Привет, я могу взять это доку ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять это доку ?

А то! Тебя не остановить 😃

**Comment by vitya-ne** [comment]
ага, как сказал бы БГ "теперь меня не остановить"
