### ISSUE TITLE
Методы массива: with

### ISSUE THREAD

**Issue by HellSquirrel** [doka-guide/content#4835]
### Тема
Методы массива: with

### Зачем
Хотим описать все методы массивов

### Кто напишет материал

- [] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
Привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять эту доку ?

Привет, конечно! Закреплю за тобой. @solarrust, можешь пока скипать плейсхолдер для этого метода.
