### ISSUE TITLE
Метод `.closest()` для DOM-элемента

### ISSUE THREAD

**Issue by gkhabada** [doka-guide/content#4838]
### Тема

Метод `.closest()`.

### Зачем

Используется для поиска нужного родительского DOM-элемента, и не нашел в Доке упоминания об этом методе.

### Ссылки для старта:

- https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
- https://dom.spec.whatwg.org/#ref-for-dom-element-closest%E2%91%A0
- https://css-tricks.com/practical-use-cases-for-javascripts-closest-method/

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
Привет, я могу взять эту доку ?

**Comment by TatianaFokina** [comment]
> Привет, я могу взять эту доку ?

Ты вернулся! Забирай, конечно.
