### ISSUE TITLE
Убрать описание свойства `button` в статье о событии `click`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#502]
Свойство неприменимо к событию клик, он всегда слушает клик левой кнопкой мыши

**Comment by rusakovdenis** [comment]
Привет
Готов поправить

Можно убрать данное свойство, но рассказать про свойство which, которое позволяет определить, какая кнопка мыши была нажата.

**Comment by nlopin** [comment]
класс, конечно присылай

**Comment by rusakovdenis** [comment]
оказалось _which_ устаревшее свойство

убрал свойство button и доабавил пару слов о свойстве _view_
