### ISSUE TITLE
Неверная ссылка в статье

### ISSUE THREAD

**Issue by shertowns** [doka-guide/content#5093]
### Ссылка на статью

https://doka.guide/css/background-image/

### Описание

![изображение](https://github.com/doka-guide/content/assets/86488248/f6104b84-a4a1-4489-a71a-be0c5b91fcc3)
 ссылка на статью linear-gradient() отсылает на статью о line-height вместо linear-gradient()

**Comment by TatianaFokina** [comment]
Исправила в https://github.com/doka-guide/content/commit/f0964f98ec2a0c811b3a8feeb079786ac151ac3d.
