### ISSUE TITLE
`text-wrap`

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/content#5170]
### Тема

Рассказать коротко про свойство, какие значения бывают, привести примеры использования (будет отлично с демками). В том числе рассказать о новых значениях `balance`, `stable` и `pretty`.

Ссылки для старта:

- https://drafts.csswg.org/css-text-4/#text-wrap
- https://codersblock.com/blog/nicer-text-wrapping-with-css-text-wrap/
- https://developer.chrome.com/blog/css-text-wrap-pretty
- https://developer.chrome.com/docs/css-ui/css-text-wrap-balance
- https://dev.to/olegchursin/mastering-css-balance-text-wrap-balance-3g21
- https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap

### Зачем

Базовое свойство, которое, оказывается, как-то умудрилось потеряться в Доке.

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by solarrust** [comment]
@nasty23-star Привет! Как успехи с этой задачкой?
