### ISSUE TITLE
Ошибка в описании роли tablist

### ISSUE THREAD

**Issue by novvember** [doka-guide/content#5174]
### Ссылка на статью

https://doka.guide/a11y/role-tablist/

### Описание

Указано, что в контейнере с ролью tablist должны находиться не только самы табы, но вкладки:

> Внутри элемента с этой ролью должна быть минимум одна панель вкладок с [ролью tabpanel](https://doka.guide/a11y/role-tabpanel/) **и связанная с ней вкладка с [tab](https://doka.guide/a11y/role-tab/)**.

Такое же поведение реализовано и в примере на странице:
```
<div class="tablist" role="tablist" aria-labelledby="label">
      <button class="tab" role="tab" type="button" id="tab-1" aria-selected="true" aria-controls="tabpanel-1">Тапиры</button>
      <button class="tab" role="tab" type="button" id="tab-2" aria-selected="false" aria-controls="tabpanel-2" tabindex="-1">Ламантины</button>
      <div class="tabpanel" role="tabpanel" id="tabpanel-1" tabindex="0" aria-labelledby="tab-1"></div>
      <div class="tabpanel tabpanel--hidden" role="tabpanel" id="tabpanel-2" tabindex="0" aria-labelledby="tab-2"></div>
</div>
```

Я попытался найти этому подтверждение, но нигде про это не написано. Везде указано, что такая роль указывается для контейнера с табами. В спецификации ничего про это [не написано](https://www.w3.org/TR/wai-aria-1.3/#tablist), в примерах использования сделано [по-другому](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/).

### Пруфы

https://www.w3.org/TR/wai-aria-1.3/#tablist

https://www.w3.org/WAI/ARIA/apg/patterns/tabs/

**Comment by TatianaFokina** [comment]
Ну это я, конечно, ляпнула глупость. Всё так! Поправлю.
