### ISSUE TITLE
Блок по центру экрана. Неявное поведение тега dialog

### ISSUE THREAD

**Issue by blasdfaa** [doka-guide/content#5175]
### Ссылка на статью

https://doka.guide/recipes/center/

### Описание

В примерах используется тег `dialog`, у которого по умолчанию `width` и `height` явно заданы браузером (как `fit-content`), по этому `margin-inline: auto` будет работать как надо. Если скопировать код из примера и применить к примеру на `div`, то работать уже не будет пока div-у не задать явные `width` и `height`.
Мне кажется это может путать, и лучше в статье об этом нюансе упомянуть.

**Comment by solarrust** [comment]
@blasdfaa отлично подмечено! Пришлёшь пулреквест с уточнением?

**Comment by blasdfaa** [comment]
> @blasdfaa отлично подмечено! Пришлёшь пулреквест с уточнением?

Да, могу сделать.

**Comment by TatianaFokina** [comment]
Теперь мы можем говорить, что в Доку контрибьютит Карл II!
