### ISSUE TITLE
Не хватает материала о свойстве CSS color-scheme

### ISSUE THREAD

**Issue by nasty23-star** [doka-guide/content#5195]
### Тема

Обзор на свойство color-scheme.

### Зачем

Тема важна, потому что довольно новое свойство, которое поддерживается почти во всех браузерах, с его помощью можно определять цветовую схему контента.

### Кто напишет материал

- [X] Я сам напишу этот материал

**Comment by solarrust** [comment]
@nasty23-star Пинг по этой задачке =)
