### ISSUE TITLE
Вопрос про justify-content: stretch в grid

### ISSUE THREAD

**Issue by splincool** [doka-guide/content#5199]
**Ссылка на статью**
https://doka.guide/css/grid-guide/#justify-content

**Вопрос**
Добрый день! 
У меня возник вопрос по `justify-content: stretch;`в гайде по grid. 
Я заметил, что во всех остальных примерах по justify-content (start, end, center,..) для `grid-template-columns` задается `repeat(3, 300px)`, (размер в пикселях), а для примера про `justify-content: stretch`  задется так: `grid-template-columns: 1fr 1fr 1fr;` во `fr`.

Если я правильно понимаю, то если задать`grid-template-columns: 1fr 1fr 1fr;` без `justify-content: stretch;`, то колонки и так займут все доступное пространство. То есть не совсем понятно, что конкретно делает `justify-content: stretch;` в этом примере с точки зрения визуальной части. 

Я пробовал воспроизвести этот пример в playground:

вот тут с `justify-content: stretch;`
![sample1](https://github.com/doka-guide/content/assets/8850606/3c65024d-403c-4062-9429-63da217d032c)

а вот тут без 
![sample2](https://github.com/doka-guide/content/assets/8850606/daf0d0a8-f786-410b-ad80-1f2adea2a62d)

и я не увидел разницы

Возможно я не так понял это свойство, поэтому решил задать вопрос :)

**Comment by solarrust** [comment]
Привет!
Отлично подмечено по поводу `1fr` в этом примере. То, что размер отличается от остальных примеров и правда немного подозрительно.

По поводу работы значения `stretch`: есть особенность, что свойство срабатывает только если у грид-элементов не заданы жёсткие размеры. Иначе растягивания по размерам контейнера не произойдёт.

> If the combined size of the items along the main axis is less than the size of the alignment container, any auto-sized items have their size increased equally (not proportionally), while still respecting the constraints imposed by max-height/max-width (or equivalent functionality), so that the combined size exactly fills the alignment container along the main axis.


Грубо говоря, растянутся сами ячейки грид-контейнера, а вот растянутся ли вложенные в эти ячейки элементы зависит от того, есть ли у них фиксированный размер.

Вот так выглядят ячейки при значении `center`
![CleanShot 2024-03-12 at 13 43 09@2x](https://github.com/doka-guide/content/assets/13676514/829663b9-1cb2-4816-81b5-eef6e4c17dd0)

А вот так при значении `stretch` (по центру блок с фиксированным размером)
![CleanShot 2024-03-12 at 13 43 49@2x](https://github.com/doka-guide/content/assets/13676514/163fec09-e942-4b18-a6b9-b922092a6951)

Надеюсь, у меня получилось ответить на вопрос. Давай придумаем, как отразить эту информацию в статье?

**Comment by splincool** [comment]
Да, большое спасибо, на твоем примере я сразу понял.

Получается не хватало упоминания, что ячейки должны быть без фиксированной ширины. Если отталкиваться от твоего примера, то те  div-ы (ячейки) у которых есть класс `fix` они не растягиваются под действием` justify-content: stretch;`

И кстати на рисунке из статьи заметно, что как будто средние ячейки поменьше чем крайние :)
![sample3](https://github.com/doka-guide/content/assets/8850606/6131e9ca-8059-4268-9bcb-311293629873)

Думаю, можно дописать, например так:

stretch — растягивает элемент на всю ширину грид-ячейки, при условии что у него не задана фиксированная ширина.

**Comment by gayratv** [comment]
@solarrust 
Проясните пожалуйста еще один момент :)

По Вашей ссылке на Codepen
[Ссылка на Codepen](https://codepen.io/solarrust/pen/PogzGdB)

div.container имеет высоту 250px 
В него вставлено 6 элементов - три на первой строке и три на второй

Из за того что высота div.container =250px - то на второй строке не отобразился background color

**Вопрос**: почему div.container не принял высоту 500px - по размеру двух строк своих детей?

**Comment by splincool** [comment]
@gayratv 
Привет!

Я думаю это потому, что у класса `.container` не задана собственная высота. А у тэга `div` ниже она задана и равна 250px, и получается что у `div.container` цвет background берется от класса `.container`, а высота берется от стилей для div. Поэтому div.container не смог принять высоту от своих детей, так как у него задана жесткая высота 250px;

Если для `.container` добавить `height: auto;` то высота будет задана автоматически и как раз растянется по высоте детей.
