### ISSUE TITLE
Функция `light-dark()`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#5229]
Описать работу функции, какие параметры принимает, механизм выбора цвета. Обязательно упомянуть поддержку. Привести пример (желательно демо) с тёмной темой.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark
- https://web.dev/articles/light-dark

**Comment by kozlovtseva** [comment]
@solarrust привет) могу я попробовать взять эту статью?

**Comment by solarrust** [comment]
@kozlovtseva Привет! Конечно, закрепляю за тобой задачку. Пиши, если нужна будет какая-нибудь помощь или подсказка =)
