### ISSUE TITLE
Не хватает материала об атрибуте alt для картинок

### ISSUE THREAD

**Issue by MariannaSpb** [doka-guide/content#5247]
### Тема

Рассказать как использовать alt и зачем он нужен для доступности и seo оптимизации. Упомянуть случаи когда можно использовать пустой alt.

### Зачем

Правильное использование атрибута alt помогает пользователям понять суть изображения, которое они не могут просмотреть, и улучшает их взаимодействие с контентом.

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by solarrust** [comment]
@MariannaSpb Привет!
Подходит ли статья «[Как описывать картинки](https://doka.guide/a11y/how-to-describe-pictures/)» для этого ишью?

**Comment by nasty23-star** [comment]
возьму эту тему
