### ISSUE TITLE
Монолиты и микросервисы

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#525]

**Comment by nlopin** [comment]
@bespoyasov синкнись с Игорем, он будет писать про монолиты на бэкенд

**Comment by bespoyasov** [comment]
Ой, так ведь мы же договорились, что не я пишу эту статью 😄 
Я мало знаю о микросервисах, поэтому толково рассказать не смогу.

(Удалю себя из assignee.)

**Comment by nlopin** [comment]
@igsekor ты расскажешь пару слов про монолиты? Я тогда этот тикет закрою
