### ISSUE TITLE
Улучшить и уточнить советы в статье про live-валидацию

### ISSUE THREAD

**Issue by BANOnotIT** [doka-guide/content#5273]
https://doka.guide/recipes/validation/

1. Форма не показывает что конкретно мне нужно заполнять после submit, вообще никакое поле не обрабатывает required
2. Поля показывают валидацию даже тогда, когда я ещё не закончил вводить правильное значение. Например я начинаю вводить me@bano.dev, а форма меня наказывает за неправильный ввод ещё на букве m.
3. Кнопка отправки почему то имеет disabled состояние, хотя зачем оно дизейблится вообще не понятно, а ещё она дизейблится через aria-disabled вместо нативного disabled. В общем кнопку дизейблить совершенно не обязательно, наоборот она может всегда быть активной, ведь мы всегда можем сказать, что что-то пошло не так после ее нажатия и перед отправкой формы.

Очень советую переписать материал с учётом тех проблем что я описал и возможно опираясь на материал smashing magazine посвященный именно этой форме валидации:
https://www.smashingmagazine.com/2022/09/inline-validation-web-forms-ux/

**Comment by TatianaFokina** [comment]
Было бы клёво, если бы ты принёс пиар с улучшениями. И ещё с учётом того, что написано про `aria-disabled` по ссылочкам, которыми с тобой поделилась.

**Comment by TatianaFokina** [comment]
Плюс к тому, что ещё стоит улучшить.

> @makarovaiuliia
>
> ![image](https://private-user-images.githubusercontent.com/1235286/320780078-7f446261-9104-4b81-a01a-74b5470c4f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTk0NjUsIm5iZiI6MTcxMjY1OTE2NSwicGF0aCI6Ii8xMjM1Mjg2LzMyMDc4MDA3OC03ZjQ0NjI2MS05MTA0LTRiODEtYTAxYS03NGI1NDcwYzRmMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTAzOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjYwOGM2N2JlNTFjYmY1MDc4Njc1OGI1MWRiNzY1YWNlNzgzMjZiYjY4OGJkOTVkMzhkNjY0NGE1OTViNjdhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uPzLMyvw6-dCNhWF_Q44ix-lyCrqDALmQNsLZF5KpjA) Спецсимвол `\s` матчит не только пробел, но и кучку других непечатаемых символов ([MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp#%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2_%D0%B2_%D1%80%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D1%85_%D0%B2%D1%8B%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D1%85:~:text=%D0%A1%D0%BE%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F%20%D1%81%20%D0%BE%D0%B4%D0%B8%D0%BD%D0%BE%D1%87%D0%BD%D1%8B%D0%BC%20%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC%20%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%BC%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9%20%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D0%B5%D1%82%20%D0%B2%20%D1%81%D0%B5%D0%B1%D1%8F%20%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%2C%20%D1%82%D0%B0%D0%B1%D1%83%D0%BB%D1%8F%D1%86%D0%B8%D1%8E%2C%20%D0%BF%D0%BE%D0%B4%D0%B0%D1%87%D1%83%20%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B%2C%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%20%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8%20%D0%B8%20%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%8B%20%D0%AE%D0%BD%D0%B8%D0%BA%D0%BE%D0%B4%D0%B0)), что может стать потенциальным вектором атаки. В данном примере в регулярке лучше явно указать пробел

**Comment by BANOnotIT** [comment]
4. Инпуты отличаются только цветом и наличием текста ошибки под инпутом. У многих инпутов бывает help text, поэтому кроме цвета и текста, который будет слипаться семантически с help text'ом тот же [SM](https://www.smashingmagazine.com/2023/02/guide-accessible-form-validation/#the-color-trap) советует использовать другие визуальные подсказки

**Comment by makarovaiuliia** [comment]
Ребят, привет! Пока не могу заняться, так как ну оч загружена. Если меня дождется, то я доделаю потом

**Comment by kozlovtseva** [comment]
@makarovaiuliia привет) могу перехватить у тебя задачку, если не против)

**Comment by makarovaiuliia** [comment]
Да, спасибо большое 🙏🏻
