### ISSUE TITLE
Ошибка в коде описанном в статье 'Выразительный React: интерактивность на клиенте'

### ISSUE THREAD

**Issue by vitya-ne** [doka-guide/content#5289]
### Ссылка на статью

https://doka.guide/recipes/expressive-react-maze/

### Описание

В финальной версии компонента Maze не учтена необходимость блокироки кнопок формирования стен после старта анимации. Если сначала нажать кнопку <kbd>Апорт!</kbd>, а потом быстро создать стены, то Собачка пройдёт их насквозь.

Предлагаю добавить код блокировки формирования лабиринта во время анимации:
```tsx
export const Maze = () => {
  ...
  const [running, setRunning] = useState<boolean>(false)
  ...
  const getBall = useCallback(() => {
    const start = { x: 0, y: 0 } // 🐶

    const end = { x: 0, y: fieldSize + 1 } // 🎾

    const path = generatePathAroundWalls(walls, start, end)
    setRunning(true) // запрещаем строить лабиринт

    dogRef.current?.animate(generateKeyframes(path), {
      duration: 3000,
      easing: 'linear',
      fill: 'forwards',
    })

    setTimeout(()=>{setRunning(false)}, 3000) // разрешаем строить лабиринт
  }, [walls])
  ...
  return (
    <>
      ...
      <div
        style={{
          width: size,
          height: size
        }}
        className={styles.maze}
      >
        {Array.from({ length: fieldSize }, (_, i) => (
          <button
            key={i}
            style={{ height: parrotsToPixels(1) }}
            className={styles.button}
            onClick={() => running ? undefined : toggleWall(i)}
          >
  ...
```

**Comment by vitya-ne** [comment]
@HellSquirrel, как вариант можно не менять код, а добавить описание существующей проблемы в финале статьи

**Comment by HellSquirrel** [comment]
Вариант с добавлением в конце мне нравится больше. Хочешь сам добавить или давай я? 

P.S. мы просто можем поменять везде собачка->собачка-призрак

**Comment by vitya-ne** [comment]
> Вариант с добавлением в конце мне нравится больше. Хочешь сам добавить или давай я?

Я могу попробовать. А ещё приведённых стилей не хватает. Я запускал локально. Выглядеть не так красиво

**Comment by HellSquirrel** [comment]
Попробуй, будет сложно я перехвачу :) 

по поводу стилей, все так. Там их просто слишком много получается. Но если интересно, оригинал вот тут сидит 
https://github.com/HellSquirrel/expressive-react-maze
