### ISSUE TITLE
Popover API

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#5302]
Референсы:
- https://developer.chrome.com/blog/introducing-popover-api/
- https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

**Comment by TatianaFokina** [comment]
+

- https://12daysofweb.dev/2023/popover-api/
- https://utilitybend.com/blog/open-ui-and-the-popover-api/
- https://hidde.blog/popover-accessibility/
- https://frontendmasters.com/blog/menus-toasts-and-more/

**Comment by TatianaFokina** [comment]
Кажется, это больше для раздела JS или HTML.
