### ISSUE TITLE
Не хватает материала о свойстве CSS `prefers-color-scheme`

### ISSUE THREAD

**Issue by nasty23-star** [doka-guide/content#5386]
### Тема

Подробнее чем оно может быть полезно, как связано с color-scheme

### Зачем

Можно делать на его основе переключение тёмной и светлой темы, улучшать внешний вид сайта

### Кто напишет материал

- [X] Я сам напишу этот материал

**Comment by solarrust** [comment]
Тебя не остановить! 🌬️
