### ISSUE TITLE
Как задавать цвета из пространства P3

### ISSUE THREAD

**Issue by Denis-GH** [doka-guide/content#5402]
В [статье про color()](https://doka.guide/css/color-function/) [говорится](https://doka.guide/css/color-function/#:~:text=%D0%9D%D0%B0%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%2C%20%D1%86%D0%B2%D0%B5%D1%82%D0%B0%20%D0%B8%D0%B7%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B0%20DCI%2DP3%20(%D0%BA%D0%BE%D1%80%D0%BE%D1%82%D0%BA%D0%BE%20P3)%20%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%20%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D1%8C%20%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D1%87%D0%B5%D1%80%D0%B5%D0%B7%20%D1%8D%D1%82%D1%83%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8E.%20%D0%A2%D0%B0%D0%BA%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F%20%D0%B0%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%20%D1%86%D0%B2%D0%B5%D1%82%D0%B0%20%2300bbff%3A), что цвета из пространства P3 можно задать только с помощью `color()`.
В PR по этой статье - #5366 - было небольшое [обсуждение](https://github.com/doka-guide/content/pull/5366#discussion_r1626544156), можем ли мы задавать цвета из P3 с помощью OKLCH (@HellSquirrel, @solarrust).

Я нагуглил несколько статей по этому вопросу:

- [раз](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl) (есть [перевод на русский](https://web-standards.ru/articles/oklch-in-css-why-quit-rgb-hsl/))
>OKLCH can be used for wide-gamut P3 colors.

>We can use the same color functions for both sRGB and P3 wide-gamut colors.
>```css
>.buy-button {
>  background: oklch(62% 0.19 145);
>}
>@media (color-gamut: p3) {
>  .buy-button {
>    background: oklch(62% 0.26 145);
>  }
>}
>```
Вроде можно и без `@media`, но автор рекомендует использовать `@media` здесь из-за возможных проблем с Chrome и Safari (статья 2022 года, сейчас не знаю как дела с этим).

Чтобы задать цвет из P3 с помощью `oklch()`, можно использовать [цветовой миксер OKLCH](https://oklch.com/#70,0.1,255,100): нужно выбрать цвет выше тонкой белой линии на графике и скопировать результат в формате `oklch()`.

Автор также отмечает преимущества `oklch()` перед `color()` для задания P3-цветов:
>We could, however, use the new `color(display-p3 1 0 0)`, but it still shares the readability problems of the RGB format.
>Luckily, OKLCH has a good readability, supports P3 and beyond, as well as any color visible to the human eye.

- [два](https://www.smashingmagazine.com/2023/08/oklch-color-spaces-gamuts-css/)

говоря о oklch, oklab, lch, lab, автор отмечает:
> they are all color spaces designed to map colors along the Display P3 gamut.

и предлагает пример использования в `@media` как в прошлой статье

- [три](https://chriscoyier.net/2023/10/20/more-oklch-musings/)
>P3 — This is totally a reason to use OKLCH, it’s not unique to it. You get P3 in LCH, OKLCH, LAB, OKLAB, color(display-p3 …), and maybe some more you probably access also via color() but I don’t know the whole list.

**Вывод**
Я не шарю в теме, но кажется, мы всё-таки можем задавать P3-цвета с помощью `oklch()` (и, судя по всему, с помощью других функций). Как я понял, DCI-P3 - это просто пространство цветов, шире, чем sRGB, и мы можем задавать цвета из этого пространства с помощью `oklch()`, подобно тому, как задаём цвета из пространства sRGB с помощью `rgb()`.

В первой статье говорится, как это сделать с помощью цветового миксера OKLCH. (лучше в русскоязычной статье читать этот [фрагмент](https://web-standards.ru/articles/oklch-in-css-why-quit-rgb-hsl/#:~:text=%D0%92%D0%BE%D1%82%2C%20%D0%BA%D0%B0%D0%BA%20%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE,gamut%3A%20p3.), а то я вижу какие-то проблемы с разметкой в оригинальной статье)

**Comment by TatianaFokina** [comment]
Привет! Спасибо за расследование 🕵️‍♂️ Кажется, проще всего было бы подправить формулировку, что, да, есть другие способы, но `color()` удобнее всего для записи P3. И нагляднее.

Можешь занести правку?
