### ISSUE TITLE
Актуализировать поддержку Safari в статье про `outline`

### ISSUE THREAD

**Issue by Denis-GH** [doka-guide/content#5407]
[Статья](https://doka.guide/css/outline/#podskazki) - в разделе "Подсказки" говорится, что Safari не адаптирует outline под форму элемента.

Кажется, в прошлом году завезли обнову - [ссылка](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes).

Предлагаю либо убрать этот абзац, либо написать как-то так:
```
В актуальных версиях браузеров обводка подстраивается под форму обводимого элемента, так же как и [`border`](/css/border/).
```
или:
```
Обводка подстраивается под форму обводимого элемента, так же как и [`border`](/css/border/).
```

**Comment by solarrust** [comment]
Как же прекрасно, что и Сафари подтянулся!
Принесёшь правочку? Мне нравятся все предложенные тобою варианты. Выбери тот, что тебе по душе =)
