### ISSUE TITLE
Неточности в статье про `perspective`

### ISSUE THREAD

**Issue by Denis-GH** [doka-guide/content#5432]
Статья - https://doka.guide/css/perspective/
В самом начале статьи:
>Свойство `perspective` определяет расстояние от пользователя до задней стенки экрана по оси z.

Не совсем понятно, что такое "задняя стенка". Официальная информация гласит, что это свойство определяет расстояние от пользователя до плоскости экрана/рисунка ("drawing plane") — https://www.w3.org/TR/css-transforms-2/#perspective (§ 4.1.1. Perspective). Считаю, что разница в формулировках всё-таки есть.

Второй вопросик у меня к интерактивной демке, она выглядит и работает как-то странно. Например, почему при увеличении значения `perspective` расстояние от пользователя до "задней стенки экрана" уменьшается...
Предлагаю свою демку: https://codepen.io/De-_-nis/pen/abgbKOR?editors=0010 — она явно показывает, как работает это свойство: при уменьшении значения свойства `perspective` часть элемента, расположенная выше плоскости экрана по оси Z увеличивается, а часть элемента, расположенная ниже плоскости экрана по оси Z уменьшается.

Третий вопрос/предложение. Стоит ли нам рассказать, как рассчитываются масштабы в перспективе? Я бы описал это так:

Для точного масштабирования в перспективе мы можем определить, во сколько раз увеличится элемент, по формуле d/(d-z), где d — значение свойства `perspective`, z — смещение элемента относительно плоскости экрана по оси z. Смещение по оси Z определяем следующим образом: если задали элементу `transform: translateZ(100px)`, то параметр z равен 100px, а если задали элементу `transform: rotateY(20deg)`, то для крайней левой точки элемента смещение по оси z определяется как sin(20), умноженный на половину изначальной ширины элемента.
Пример на основе демки выше:
изначальная ширина элемента — 500px, высота — 150px, элемент повёрнут на 45 градусов, родителю зададим `repspective: 700px`. Применяем формулу: 700/(700-sin(45)*250) = 1,3379 — во столько раз увеличится высота элемента в крайней левой точке. Подставляя разные значения в формулу можем "на бумаге" рассчитать эффект перспективы.

**Comment by solarrust** [comment]
Привет!

Очень дельные замечания, спасибо.

1. Да, стоит подобрать более корректную формулировку исходя из фразы в спецификации.
2. Соглашусь, что текущая демка может быть не до конца понятной. Твой вариант мне нравится. Он более наглядный.
3. Кажется, что это напрямую не относится к описанию свойства. Но будет отлично смотреться в блоке «На практике». Своего рода дополнительное знание =)

Принесёшь пиар с этими правками?

**Comment by Denis-GH** [comment]
>Принесёшь пиар с этими правками?

ок
