### ISSUE TITLE
Не хватает Рецепта о том как можно для любого выбранного Дива настраивать свойства каждой области

### ISSUE THREAD

**Issue by Vzprogr** [doka-guide/content#5451]
### Тема

Т.е. о том, как можно для любого выбранного Дива 
указать не только размеры всех четырех областей content/padding/border/margin,
но и для каждой задать свой определенный фоновый цвет!
Что бы не делать пачку вложенных Дивов, а иметь в разметке всего один Див-контейнер и для каждой области выставить свои цвета!
![Margin__1_ 1](https://github.com/user-attachments/assets/34619e2f-7a08-49a6-b9e2-d55f7f7b5238)

### Зачем

Важна, потому что считаю правильным не раздувать кол-во дивов больше минимально возможного.
И не видел готовых решений в других местах интернета.

Прошу знатоков, показать как правильно решать эту задачу, создавая код минимальной сложности!

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by alexeyten** [comment]
Цвет у margin? :thinking:

**Comment by solarrust** [comment]
@Vzprogr я бы с радостью увидела такой рецепт в Доке, особенно если там действительно будет найден способ красить `margin` =) Я не знаю нативного способа это сделать.

**Comment by alexeyten** [comment]
@solarrust, Ну можно сделать «красивую» двойную границу :sweat_smile: 

https://codepen.io/alexeyten/pen/poXyEZG

**Comment by Vzprogr** [comment]
> @Vzprogr я бы с радостью увидела такой рецепт в Доке, особенно если там действительно будет найден способ красить `margin` =) Я не знаю нативного способа это сделать.
> 
> А если говорить о теме рецепта, то расскажи, пожалуйста, какую-то реальную рабочую задачу, которую можно было бы решить таким способом. Пока что я вижу применение только для вот таких вот схем блочной модели.

Я раньше создавал интерфейсы в редакторе форм FoxPro 3-5, Dephi 7, Access 2003.
Мое мышление привыкло к естественной модели - вообразить раскладку на странице в терминах прямоугольников (тут эту будут в основном дивы и другие блочные элементы).
И дальше мыслить о настройке свойств этих объектов, так если есть область - то можно управлять как ее размером, так и всеми аспектами цвета.
Теперь я с сожалением понимаю, по вашей реакции - что область margin - не полноценна в своей настройке, и при таком желании прийдется делать уже пару вложенных дивов вместо одного.

Я собирался усвоить как менять все параметры имея всего один Див - и начать относиться к нему как у универсальному кирпичику. Теперь понимаю что полностью универсальным - может стать только пара дивов!

Может такой теоретический вывод -надо было бы поместить в какую нибудь статью по созданию блочной раскладки на наш справочный сайт.
Подумайте пожалуйста над этим.

**Comment by solarrust** [comment]
«Можно раскрасить почти весь мир, имея всего один фломастер. А чтобы раскрасить вообще весь мир понадобятся два фломастера» (Бородатая шутка)

Спасибо тебе и удачи в освоении веба!
