### ISSUE TITLE
Тег `<noscript>`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#546]
Рассказать что делает этот тег, зачем его использовать и какие проблемы он решает.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

**Comment by DariaKamenskaya** [comment]
Хочу взять эту задачу

**Comment by TatianaFokina** [comment]
> Хочу взять эту задачу

Круто! Закрепила за тобой.

**Comment by Ashkaari** [comment]
Готова взять

**Comment by solarrust** [comment]
@Ashkaari привет! Как дела? Есть ли какие-то вопросы?

**Comment by Ashkaari** [comment]
> @Ashkaari привет! Как дела? Есть ли какие-то вопросы?

Привет! Я на этих выходных возьмусь за дело 🥰

**Comment by Ashkaari** [comment]
@solarrust, у меня только выходные наступили 🤣 
Я посмотрела - статья-то уже есть и она в полной мере описывает этот тег (на мой взгляд), почему задача помечена как открытая?

**Comment by solarrust** [comment]
Привет! И правда, упустила момент появления этой статьи. Прости, пожалуйста. Может быть захочешь взять в работу какую-то другую доку?
