### ISSUE TITLE
Не хватает информации о фазе погружения у событий

### ISSUE THREAD

**Issue by mpstv** [doka-guide/content#5479]
### Тема

В статье [Событийная модель](https://doka.guide/js/events/) нет инфомации про фазу прогружения событий.

Насколько я понимаю, у событий - есть фаза погружения и получается, что их можно поймать еще до фазы всплытия, если передать [третий агрумент функции](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#usecapture) `addEventListener`

Если добавить такой обработчик в [примере со всплытием](https://doka.guide/js/events/demos/bubbling-chain/), тогда блоки загорятся сначала от внешнего к внутреннему (погружение), а потом от наоборот (всплытие).

### Зачем

Мне кажется, что это стоит добавить для полноты статьи, но придумать кейс, где это может понадобится, я, если честно, не могу.

Может быть, стоит добавить это как сноску со ссылкой mdn, например.

### Кто напишет материал

- [ ] Я сам напишу этот материал

**Comment by vitya-ne** [comment]
привет,
я уже работаю над этой частью. Надеюсь в ближайшее время добавить PR
