### ISSUE TITLE
Тег `<time>`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#548]

**Comment by pepelsbey** [comment]
@slavarazum готовы взяться? :)

**Comment by slavarazum** [comment]
@pepelsbey Если возражений нет, как тут не поучавствовать 🙂

**Comment by solarrust** [comment]
@slavarazum закрепила задачку за тобой =)
Готова прийти на помощь в любой момент! 
Буду очень ждать от тебя пул-реквест 🖤

**Comment by slavarazum** [comment]
Супер, спасибо 💛
Дока уже развернута, процесс запущен 💪

**Comment by slavarazum** [comment]
Готово – [Дока для `<time>`](https://github.com/doka-guide/content/pull/2371).
