### ISSUE TITLE
Ошибка в ссылке на статью (статья более недоступна) 

### ISSUE THREAD

**Issue by Eduard-Bosak** [doka-guide/content#5531]
### Ссылка на статью

https://doka.guide/tools/technical-debt/

### Описание

При нажатии на гиперссылку по тексту на фрагменте  "Есть мнение"  ссылка ведет на не существующую страницу
![image](https://github.com/user-attachments/assets/91072335-0374-4b3e-ac9e-2304c2edd40c)

![image](https://github.com/user-attachments/assets/a4991552-2259-414d-a74f-50836cb987e9)

**Comment by vitya-ne** [comment]
@skorobaeus, в статье про технический долг иллюстрация с графиком практически не видна в тёмной теме. Я созал [issue](https://github.com/doka-guide/content/issues/5532) что бы пофиксить это отдельно

**Comment by skorobaeus** [comment]
> @skorobaeus, в статье про технический долг иллюстрация с графиком практически не видна в тёмной теме. Я создал [issue](https://github.com/doka-guide/content/issues/5532) что бы пофиксить это отдельно

Спасибо большое! <3 Я всё пофиксила :)

**Comment by vitya-ne** [comment]
@skorobaeus, можно закрывать )
