### ISSUE TITLE
Что такое "разрежённый массив" и какая у него будет длина?

### ISSUE THREAD

**Issue by nasty23-star** [doka-guide/content#5558]
Как интересный факт добавить в статью "Массивы" про разрежённые массивы и про то, что дыры в массиве тоже считаются при подсчёте длины массива.

**Comment by alexeyten** [comment]
Ещё бы добавить что методы массивов типа `map`/`filter` и т.д. не обрабатывают пропущенные элементы. И что пропущенные элементы это не то же самое что значение `undefined`.

```js
> a = [undefined,,0]
[ undefined, <1 empty item>, 0 ]
> Object.keys(a)
[ '0', '2' ]
> a[0]
undefined
> a[1]
undefined
> 0 in a
true
> 1 in a
false
> a.map(() => true)
[ true, <1 empty item>, true ]
> a.filter(x => !x)
[ undefined, 0 ]
```

И что лучше таких массивов избегать, особенно если они используются часто.

**Comment by vitya-ne** [comment]
> Ещё бы добавить что методы массивов типа `map`/`filter` и т.д. не обрабатывают пропущенные элементы. И что пропущенные элементы это не то же самое что значение `undefined`.

Привет, спасибо за замечание.
Частично, эта тема раскрыта в конкрентых статьях, например: [.map()](https://doka.guide/js/array-map/).
Но в некоторых метадах, упоминание о <empty slots> действительно упущено.
Возможно стоит добавить информацию именно в конкретные статьи ? Если же есть идеи как это сформулировать в общей статье - тоже ок.
Будем рады пулл-реквесту )
