### ISSUE TITLE
Ошибка в демке статьи Number.isNaN

### ISSUE THREAD

**Issue by nasty23-star** [doka-guide/content#5570]
### Ссылка на статью

https://doka.guide/js/number-is-nan/

### Описание

На телефоне демка ниже билета неадаптивна

### Пруфы

нужен адаптив

**Comment by baileys-li** [comment]
Это же просто картинка, а не демка
![image](https://github.com/user-attachments/assets/ade3f433-0e87-4692-be3a-36a69313d22d)

**Comment by nasty23-star** [comment]
Ниже неё демка
![неадаптивна](https://github.com/user-attachments/assets/a631cef1-2abb-475d-8ed4-6934a1c4b0b1)

**Comment by baileys-li** [comment]
Понял. Невнимательно читал. Тогда возьму
