### ISSUE TITLE
Опечатки в статье Rotate

### ISSUE THREAD

**Issue by Aleg3000** [doka-guide/content#5578]
### Ссылка на статью

https://doka.guide/css/rotate/

### Описание

<img width="977" alt="Снимок экрана 2024-12-07 в 14 02 13" src="https://github.com/user-attachments/assets/27bde120-f4d5-4e84-a716-1db5231f1c2e">

соответсвующую -> соответствующую
повярнут -> повернут

просто опечатки
<img width="948" alt="Снимок экрана 2024-12-07 в 14 04 40" src="https://github.com/user-attachments/assets/78dc34fa-65fe-48c0-bc36-dc4d77a3aab7">

Не смотря на то, что -> Несмотря на то, что

### Пруфы

Если «несмотря на» — предлог, который значит, что что-то сделано вопреки обстоятельствам, то он пишется слитно.

**Comment by nasty23-star** [comment]
беру. спасибо, что прислал ошибку!
