### ISSUE TITLE
Вопрос для собеседования для статьи `Массив`

### ISSUE THREAD

**Issue by vitya-ne** [doka-guide/content#5589]
### Вопрос

Дан одномерный массив.
Его элементами могут быть значения разных типов, включая: `undefined`, `null`, `boolean`, `string`, `number`. 
Например: 
```js
const array = [5, undefined, 0, false, '', null, true, 1]
```
Массив может быть разрежённый (sparse array), то есть включать незаполненные элементы (empty slots).
Например, добавим к массиву `array` элемент с индексом `15`:
```js
array[15] = 'новый элемент'
console.log(array)
// [ 5, undefined, 0, false, '', null, true, 1, <7 empty items>, 'новый элемент']
```
Напишите функцию подсчёта незаполненных элементов массива.

### Кто ответит на вопрос

- [ ] Я знаю ответ!

**Comment by nasty23-star** [comment]
Привет! Всё хорошо, только "то есть" пишется раздельно. И я так понимаю sparse array пишется как разрежённый массив. Посмотри пожалуйста.

**Comment by vitya-ne** [comment]
поправил, спасибо

**Comment by alexeyten** [comment]
СЯУ что там оказывается буква «ё» в слове «разрежённый» 😅
