### ISSUE TITLE
Тег `<progress>`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#578]

**Comment by pepelsbey** [comment]
Fixed #1288

**Comment by pepelsbey** [comment]
Fixed #1288

**Comment by webdb81** [comment]
Добрый день.
Берусь дополнить доку.

**Comment by solarrust** [comment]
Спасибо большое за твою активность. Ты вносишь огромный вклад в Доку ♥️
Закрепила задачку за тобой!
