### ISSUE TITLE
Тег `<dialog>`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#581]

**Comment by baileys-li** [comment]
Хочу взять

**Comment by solarrust** [comment]
Привет! Супер, закрепила задачку за тобой.
Пожалуйста, пиши, если потребуется любая помощь =)

**Comment by baileys-li** [comment]
Редактура бы пригодилась, я к сожалению весьма косноязычен. 😔

Ну и если кто-то придумает интересные идеи для демок будет круто 😶‍🌫️
