### ISSUE TITLE
Атрибут `accept`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#584]
Рассказать к каким элементам можно применять, какие значения может, а какие не может принимать, как меняется поведение элемента с этим атрибутом. Какие есть ограничения и особенности.
Перелинковать с материалами про другие атрибуты, которые можно использовать вместе с этим.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept

**Comment by TanuGlagkih** [comment]
Хочу взять задачу:)

**Comment by TatianaFokina** [comment]
> Хочу взять задачу:)

Отлично, закрепила за тобой.

**Comment by teplostanski** [comment]
Готов взять!

**Comment by solarrust** [comment]
@teplostanski Супер! Закрепила за тобой =)
