### ISSUE TITLE
Атрибуты `maxlength` и `minlength`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#585]
Рассказать к каким элементам можно применять, какие значения может, а какие не может принимать, как меняется поведение элемента с этим атрибутом. Какие есть ограничения и особенности.
Перелинковать с материалами про другие атрибуты, которые можно использовать вместе с этим.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/minlength

**Comment by ZeddyBig** [comment]
Привет. Хочу написать эту тему

**Comment by TatianaFokina** [comment]
Привет, бери! Удачи в хакатоне.

**Comment by Edymov** [comment]
Привет. Я возьму
