### ISSUE TITLE
Атрибут `capture`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#589]
Рассказать к каким элементам можно применять, какие значения может, а какие не может принимать, как меняется поведение элемента с этим атрибутом. Какие есть ограничения и особенности.
Перелинковать с материалами про другие атрибуты, которые можно использовать вместе с этим.
Обязательно сказать про поддержку в браузерах.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture

**Comment by Inventoris** [comment]
Беру!

**Comment by eshevlyakova** [comment]
Беру
