### ISSUE TITLE
Функция clamp() 

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#601]
Рассказать про потрясную эту функцию. Какие значения может принимать, какие проблемы решает, как с её помощью сокращается код, как работает вычисление значения. Обязательно сказать про поддержку в браузерах.

Референс:
- https://developer.mozilla.org/en-US/docs/Web/CSS/clamp
- https://css-tricks.com/min-max-and-clamp-are-css-magic/

**Comment by TatianaFokina** [comment]
@denisputnov хочет написать эту доку.

**Comment by gartonot** [comment]
Здравствуйте. Если сейчас над статьёй никто не работает, хотелось бы взяться её написать

**Comment by TatianaFokina** [comment]
> Здравствуйте. Если сейчас над статьёй никто не работает, хотелось бы взяться её написать

Закрепила задачку.
