### ISSUE TITLE
Свойство `clip-path`

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#602]

**Comment by Spheno** [comment]
👋  Хотела бы взять

**Comment by furtivite** [comment]
@solarrust закроем в связке с #4062 ? Или ждём роста статьи из плейсхолдера во что-то большее?

**Comment by StarHamster** [comment]
Хочу взять, заасайните? 👀

**Comment by TatianaFokina** [comment]
> Хочу взять, заасайните? 👀

Без проблем!
