### ISSUE TITLE
Свойство touch-action

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#605]
Подробнее рассказать об этом свойстве. Какие проблемы решает, какие значения принимает, когда следует использовать. 

Референсы:
- https://css-tricks.com/almanac/properties/t/touch-action/
- https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by ErmachenkoBoris** [comment]
Хочу забрать эту статью

**Comment by solarrust** [comment]
@ErmachenkoBoris привет! Как дела? Нужна ли какая-то помощь?

**Comment by ErmachenkoBoris** [comment]
Привет, я помню про задание и все еще хочу сделать) Я в отпуске, через 14 дней вернусь, и через 3 недели смогу подготовить статью. Если нужно раньше - тогда мне нужно ее передать

**Comment by solarrust** [comment]
О, отпуск это прекрасно! Хорошего тебе отдыха 🌴

Сроки не горят, просто хотела убедиться, что у тебя нет никаких трудностей на пути 🙌
