### ISSUE TITLE
Свойство word-break

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#608]
Расширить статью из плейсхолдера. Рассказать, какие проблемы решает, когда следует использовать, можно ли задать глобально для всей страницы, какие значения принимает.

Референсы:
- https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
- https://css-tricks.com/almanac/properties/w/word-break/

**Comment by goingtogogo** [comment]
Привет! Хочу попробовать взять на себя)

**Comment by goingtogogo** [comment]
Сори, не дождалась назначения( очень хотелось попробовать!)

**Comment by solarrust** [comment]
@goingtogogo круто, что не стал дожидаться меня в этом ишью 👍
