### ISSUE TITLE
Свойство aspect-ratio

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#621]

**Comment by TatianaFokina** [comment]
Привет, отлично! Пиши, если нужна будет помощь.

Пара полезных ссылок:

- [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).
- [Демки](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).
- [Про стиль демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md).
