### ISSUE TITLE
Свойство clip

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#648]

**Comment by bellabzhu** [comment]
Хочу взять эту задачу :)

**Comment by TatianaFokina** [comment]
> Хочу взять эту задачу :)

Забирай, закрепила.

**Comment by bellabzhu** [comment]
> Забирай, закрепила.
Похоже статья уже написана?
https://doka.guide/css/clip/

**Comment by TatianaFokina** [comment]
> Похоже статья уже написана? https://doka.guide/css/clip/

И правда, задублировано было ишью :( Спасибо, что обратила внимание.

**Comment by TatianaFokina** [comment]
Закрываю задачку, это дубль #473.
