### ISSUE TITLE
Свойство font-stretch

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#650]

**Comment by kalpovskii** [comment]
Взято (TAKEN ⚠)

**Comment by solarrust** [comment]
Круто! Спасибо ♥️

**Comment by kalpovskii** [comment]
Хотел сделать демку, но стили не применялись, попробовал в разных браузерах, посмотрел на caniuse, все должно работать. Написал:

![image](https://user-images.githubusercontent.com/64479736/192547714-47458f5c-919e-42ca-914b-fba2852c4e3e.png)

и получил:
![image](https://user-images.githubusercontent.com/64479736/192548420-a26ba874-45f5-4d84-b1fe-ee6be706d54b.png)
в chrome и firefox

Я что-то не то делаю? Не понимаю :(
