### ISSUE TITLE
Свойство text-indent 

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#660]

**Comment by ra1nbow1** [comment]
Привет. С удовольствием займусь!

**Comment by solarrust** [comment]
@ra1nbow1 привет! 
Буду очень ждать доки твоего авторства 🔥
Пожалуйста, пиши, если потребуется любая помощь!
Тебе может пригодится [Руководство по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)

**Comment by ra1nbow1** [comment]
@solarrust есть - #2667
