### ISSUE TITLE
Функция conic-gradient()

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#675]

**Comment by Mitorun** [comment]
Нужен конический градиент! https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient()

**Comment by solarrust** [comment]
Согласна полностью, нужен очень.
Возьмёшься?

**Comment by Mitorun** [comment]
> Согласна полностью, нужен очень. Возьмёшься?

Попробую попробовать, но без обещания что получится закончить)

**Comment by solarrust** [comment]
@Mitorun мы обязательно поможем довести статью до идеала и опубликовать её! 🙌
Главное начать =)

**Comment by Mitorun** [comment]
> @Mitorun мы обязательно поможем довести статью до идеала и опубликовать её! 🙌 Главное начать =)

В общем написал статью в виде текста. Завтра со свежей головой причешу текст и примеры, можно нарисовать иллюстрации. Если скину "дальше на конвейер" контент статьи и мне не придется изучать как самому статью запушить - это будет норм?

**Comment by solarrust** [comment]
Запушить статью очень просто. @pepelsbey записал об этом [короткое видео](https://www.youtube.com/watch?v=y-_nXfKkI3w&t=1s). Уверена, что после его просмотра у тебя не возникнет сложностей =)

**Comment by Mitorun** [comment]
> Запушить статью очень просто. @pepelsbey записал об этом [короткое видео](https://www.youtube.com/watch?v=y-_nXfKkI3w&t=1s). Уверена, что после его просмотра у тебя не возникнет сложностей =)

У меня нет опыта работы с git, а видео не отвечает на вопрос как же склонировать себе локально content.git
Еще есть непонятки с оформлением раздела "На практике" - нигде в документации не указано в каком файле заполнять этот раздел, в основном файле статьи или во вложенном "conic-gradient/practice/Mitorun.md"?

В остальном статья готова, маркдаун и демки хоть и делал "вслепую", но они с большой вероятностью или без ошибок или потребуют лишь незначительных правок. Мне нужна помощь в клонировании репозитория (также будет хорошо и в документации более подробно описать эти шаги) или я могу скинуть архивчик со всеми файлами статьи.

**Comment by furtivite** [comment]
Привет, 

1. Клонируешь контентный репозиторий: `git clone https://github.com/doka-guide/content.git`
1. Клонируешь репозиторий платформы (в ту же папку): `git clone https://github.com/doka-guide/platform.git`
1. В папке платформы устанавливаешь зависимости командой `npm i`
1. Если у тебя windows под админскими правами в терминале: `node make-links.js`, если не windows, то без админских прав
1. Запускаешь сервер `npm start`
1. Переключаешься на новую ветку в папке контента, пишешь статью, она будет видна на локалхосте.
1. Блок «на пратике» действительно находится в папке практик с твоим ником в названии (с маленькой буквы, чтобы имя могло подтянуться из папки people): conic-gradient/practice/mitorun.md - спасибо, что подсказал, заведём issue, что про это не написано
1. Создаёшь свою папку в people
1. Коммитишь пушишь

**Comment by Mitorun** [comment]
> Привет, @Mitorun
> 
> 1. Клонируешь контентный репозиторий: `git clone https://github.com/doka-guide/content.git`
> 2. Клонируешь репозиторий платформы (в ту же папку): `git clone https://github.com/doka-guide/platform.git`
> 3. В папке платформы устанавливаешь зависимости командой `npm i`
> 4. Если у тебя windows под админскими правами в терминале: `node make-links.js`, если не windows, то без админских прав
> 5. Запускаешь сервер `npm start`
> 6. Переключаешься на новую ветку в папке контента, пишешь статью, она будет видна на локалхосте.
> 7. Блок «на пратике» действительно находится в папке практик с твоим ником в названии (с маленькой буквы, чтобы имя могло подтянуться из папки people): conic-gradient/practice/mitorun.md - спасибо, что подсказал, заведём issue, что про это не написано
> 8. Создаёшь свою папку в people
> 9. Коммитишь пушишь

Более подробное про раздел "На практике":
https://github.com/doka-guide/content/blob/main/docs/contributing.md
https://github.com/doka-guide/content/blob/main/docs/examples/doka.md
В этих руководствах не хватает подробного описания как заполнять раздел "На практике". Только указание создать подпапку practice и файл со своим ником. Не описано в каком файле нужно размещать текст для раздела и фреймы с демками, а также в какой папке создавать сами демки.

У меня проблема с первым пунктом:
"1. Клонируешь контентный репозиторий: git clone https://github.com/doka-guide/content.git"
Клонировать с терминала Windows или встроенного терминала? Для клонирования что-то должно быть установлено кроме VS Code?

**Comment by furtivite** [comment]
> Клонировать с терминала Windows или встроенного терминала VSCode? Для клонирования что-то должно быть установлено кроме VS Code?

Чтобы клонировать репозитории с гитхаба при помощи терминала VSCode или встроенного (разницы нет), нужно установить гит на свой компьютер. [Вот ссылка](https://git-scm.com/download/win). Можно поставить [Github Desktop](https://desktop.github.com) (Windows, mac).

Рекомендую [статью про гит](https://doka.guide/tools/git-cli/). Она будет полезна в работе в дальнейшем.

> На этих страницах не хватает подробного описания как заполнять раздел "На практике". Только указание создать подпапку practice и файл со своим ником. Не описано в каком файле нужно размещать текст для раздела и фреймы с демками, а также в какой папке создавать сами демки.

Тут я тоже посмотрю и мы приведём документацию в более прозрачный вид.

Как создать демку [описано вот тут](https://github.com/doka-guide/content/blob/main/docs/demos.md).

**Comment by Mitorun** [comment]
Отправил пулл реквест, статью и файл в папку people. Вместе с ним еще один пулл реквест прицепился, надеюсь в общем получилось правильно отправить.
