### ISSUE TITLE
Свойство word-spacing

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#684]

**Comment by ra1nbow1** [comment]
Привет! Могу заняться этой докой

**Comment by ra1nbow1** [comment]
@solarrust :)

**Comment by solarrust** [comment]
@ra1nbow1 привет! Прости за задержку с ответом — в отпуске 🙂
Конечно забирай себе эту задачку! Я буду с нетерпением ждать доки твоего авторства 🫶

**Comment by ra1nbow1** [comment]
#3274

**Comment by ra1nbow1** [comment]
@solarrust а почему дата редактирования не изменилась?

**Comment by solarrust** [comment]
Хороший вопрос! @igsekor можешь посмотреть?
