### ISSUE TITLE
Поправить прокрутку в статьу `wheel`

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#718]
В новой демке в статье о событиях прокрутки есть проблема — айфрейм перестает прокручиваться и начинает прокручиваться родительская страница.

Обсуждали варианты решения в пул реквесте #537 и решили пофиксить позже. Нужно найти решение и запилить его

**Comment by kalininmax** [comment]
@nlopin Вот такой скрипт, кажется, должен помочь:
```
const iframes = document.querySelectorAll('iframe')

iframes.forEach(iframe => {
  iframe.addEventListener('mouseenter', document.body.style.overflowY = 'hidden')
  iframe.addEventListener('mouseleave', document.body.style.overflowY = 'auto')
})
```

**Comment by nlopin** [comment]
Если нужно добавлять скрипт, то эти изменения нужно вносить в репозиторий платформы в шаблон материала. В этом случае этот код будет добавляться на каждую страницу доки и не должен ломать их.

**Comment by pepelsbey** [comment]
Думаю, можно переехать в #1956
