### ISSUE TITLE
Перенести типы статей в теги

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#737]
- [x] Перенести HTML, поправить ссылки @solarrust
- [x] Перенести CSS, поправить ссылки @solarrust
- [x] Перенести JS, поправить ссылки @nlopin
- [x] Перенести инструменты @nlopin
- [x] Проверить сборку на платформе @furtivite 
- [x] Описать в документации @tachisis

# Как сейчас

Файлы

```
tech/
  articles/
    title-1/
  doka/
    title-2/
```

Ссылки

- [tech/articles/title-1]()
- [tech/doka/title-2]()

# В чём проблема

- Знание о том, что это статья или дока не даёт ценности читателю
- Ссылка удлинняется лишней информацией, уже сходу не набрать её в строке
- Разница между статьями и доками уже размыта

# Приняли решение

Оля, Алёна, Коля и Вадим договорились вынести тип статьи в теги и выводить это на самой странице.

```
tech/
  title-1/
  title-2/
```

Ссылки

- [tech/title-1]()
- [tech/title-2]()

То есть все статьи у нас будут иметь предсказуемый адрес `tech/title`.

# Как делать

Примерный сценарий:

1. Каждый лид берёт один свой раздел и собирает ПР с переездом
2. Внутри папок `article` и `doka` эти типы расставляются тегами в ключ `tags`
3. Папки с проставленными тегами выносятся из папки-типа наверх в папку-технологию
4. Создаётся ПР

# Например

В файле `css/articles/animation/index.md` добавляется тип в теги:

```yml
---
title: ":active"
authors:
  - solarrust
tags:
  - article
---
```

Потом убирается папка-тип `css/animation/index.md`.

**Comment by pepelsbey** [comment]
@furtivite твой ход, проверить как новая структура контента живёт с платформой :)

**Comment by pepelsbey** [comment]
@tachisis надо пройтись по документации и найти, что там нигде больше нет папок `doka` и `articles` в примерах, а также описать идею с тегами `article` и `doka` в руководствах и шаблонах.

**Comment by nlopin** [comment]
Я для поиска использовал такую регулярку `\/(articles|doka|long)\/`если будет полезно

**Comment by tachisis** [comment]
@pepelsbey ПР: https://github.com/doka-guide/content/pull/1045
