### ISSUE TITLE
Описать структуру материалов в разделах

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#738]
Сначала лучше доделать #737 (Перенести типы статей в теги).

- [x] Описать HTML @solarrust
- [x] Описать CSS @solarrust
- [x] Описать JS @nlopin
- [x] Описать инструменты @nlopin
- [x] Продумать, как обозначить связи @nlopin @pepelsbey

# Как сейчас

У нас есть четыре категории:

1. HTML
2. CSS
3. JS
4. Инструменты

Внутри каждой категории у статей нет никакой структуры, кроме алфавитной.

# В чём проблема

- Материалы уже имеют неявную структуру: корневые и отходящие, вводные и углублённые
- Перечисление материалов просто по алфавиту не отвечает всем задачам читателей
- Некоторые материалы не имеют вводных, объединяющих точек

# Приняли решение

Оля, Алёна, Коля и Вадим договорились собрать внутри каждого раздела структуру связей. Например:

- HTML
  - Теги
    - a
    - address
    - article
  - Устаревшие теги
- CSS
  - Гайд по flexbox
    - flex
    - flex-basis
    - flex-direction
  - Гайд по grid
    - grid
    - grid-area
    - grid-auto-columns-rows

# Важно

- Связи обозначаются в отдельном файле или на уровне меты (нужно решить как)
- Связи не отражаются на файловой системе или в адресах статей
- Связи выводятся в индексе и в самом материале: родительские (хлебные крошки) или дочерние (читать дальше)

# Как делать

Параллельно нужно решить две задачи:

1. Продумать структуру связей и понять, каких корневых точек не хватает
2. Обсудить и найти решение, как эти связи организовать, [ссылка на дискуссию](https://github.com/Y-Doka/content/discussions/753)

**Comment by solarrust** [comment]
Я 100% что-то забыли, но с этого можно начинать. И да, я ненавижу CSS 😅 Там столько всего! 

https://disk.yandex.ru/i/rS4m821qRWzIDQ

**Comment by nlopin** [comment]
@pepelsbey мы кажется эту задачу сделали, надо реализовать новую структуру

**Comment by pepelsbey** [comment]
@nlopin согласен, задачу закрываю. Теперь нужно уже сам контент разметить.
