### ISSUE TITLE
window.location

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#745]
Рассказать, что такое и дать совет как редиректить пользователя с ее помощью

**Comment by akellbl4** [comment]
тут прям много всего интересного можно целую статью написать

**Comment by nlopin** [comment]
У нас есть краткое описание в статье [bom](https://y-doka.site/js/long/bom/#location)

Но хочется подробненько

**Comment by akellbl4** [comment]
Нужно описать прям все возможности? Просто я оказывается даже не знаю что за `ancestorOrigins` и `fragmentDirective` (кстати сейчас попробовал вызвать в браузере и не вижу `fragmentDirective`)

Еще заметил что есть функция `assign()` которая работает как сеттер доля поля `href`. А ребята на SO говорят все фигня `href`, [то что нужно](https://stackoverflow.com/questions/10302905/location-href-property-vs-location-assign-method).
