### ISSUE TITLE
Оформить демки в статье про CSS-анимации

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#756]

**Comment by skorobaeus** [comment]
@solarrust @ValyaBro [Первое демо](https://codepen.io/solarrust/pen/GRrYodX) это чужая анимация. Своё я такое за адекватное время не нарисую. Что делать? Пока вставлять, что есть, и заводить задачу на создание своей анимации когда-нибудь в будущем?

**Comment by ValyaBro** [comment]
сейчас точно перерисовывать не надо. да, будет здорово, завести тикет в ношене на анимацию и я сделаю. критически ли важно для смысла статьи публиковать эту анимацию? И помогите, пожалуйста, где и как можно почитать текст статьи, чтобы понять контекст, скорее всего можно решить более простыми графическими приёмами

**Comment by solarrust** [comment]
@skorobaeus я бы не стала перерисовывать. Столько времени можно потратить =) Лучше обратиться за опытом лучших. Буду рада, если ты предложишь какую-то другую, ещё более прикольную. Разве что я бы добавила копирайт (откуда взято), а то што-то упустила.

@ValyaBro если статья слита, то она есть на сайте. Вот ссылочка на эту https://new.y-doka.site/css/animation/

**Comment by ValyaBro** [comment]
@skorobaeus первая анимация в-целом не смыслообразующая и её можно опустить. Я бы даже сказала, что такие задачи не первостепенные для тебя, тегай на них меня, пожалуйста. 
@solarrust а последняя демка твоя, правильно? Что думаешь, если мы её чуть задизайним?

**Comment by solarrust** [comment]
1. Первая демка — чисто иллюстративная, показывает, что можно сделать на CSS. Её трогать по желанию, но совсем не обязательно. Она и так ок =)
2. Мои демки в этой задаче только с квадратом и кружочком. Остальные взяты из интернетов. 
3. Те демки, что иллюстрируют работу разных значений свойства можно перекрашивать как угодно, а суть, точнее код самого механизма демки можно не трогать.

**Comment by ValyaBro** [comment]
Ага, первую демку хочется переделать, она не совсем в нашем стиле. подумаем тогда со @skorobaeus.
Демку со светофорами хочется переделать больше в нашем стиле, тогда @skorobaeus кажется тут интересная задача для тебя <3

**Comment by solarrust** [comment]
@skorobaeus ты могла бы, пожалуйста, взять эту задачку в работу?
