### ISSUE TITLE
Примеры для статьи про Таблицы

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#769]

**Comment by skorobaeus** [comment]
@solarrust Сейчас в статье только одно демо. Напиши, пожалуйста, сколько ещё нужно. По одному в подраздел — норм?

**Comment by solarrust** [comment]
А смотри, там в начале стоит итоговая таблица, которую мы создаём по ходу. Получается, нужно сделать одну классную стильную табличку и постепенно её создать по ходу статьи. Надеюсь, понятно объяснила 😅

**Comment by skorobaeus** [comment]
@solarrust Пока не совсем :D Смотри, сейчас кусочки HTML-кода идут чуть ли не через абзац и в них эта таблица и создаётся по ходу статьи. Ты имеешь в виду каждый этот кусочек кода и проиллюстрировать демкой? Просто боюсь, не превратится ли статья в простыню)

**Comment by solarrust** [comment]
Давай вставлять демки только там, где что-то реально МЕНЯЕТСЯ визуально =) Типа пустые таблички или добавленный `<tbody>`, наверное, можно не иллюстрировать
