### ISSUE TITLE
Не описана модель ветвления

### ISSUE THREAD

**Issue by igsekor** [doka-guide/content#789]
В документации проекта не описана модель ветвления. Вывод сделал по прочтении трех файлов:

- [README.md](https://github.com/Y-Doka/y-doka.site/blob/master/README.md)
- [CONTRIBUTING.md](https://github.com/Y-Doka/y-doka.site/blob/master/CONTRIBUTING.md)
- [WRITING.md](https://github.com/Y-Doka/y-doka.site/blob/master/WRITING.md)

**Comment by nlopin** [comment]
Я добавил [описание процесса в contributing.md](https://github.com/Y-Doka/content/blob/main/docs/contributing.md#%D1%84%D0%BB%D0%BE%D1%83), но случайно сделал это в мейне.
