### ISSUE TITLE
GitHub Actions: автоматизировать заведение задач на редактора и дизайнера

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#793]

**Comment by tachisis** [comment]
@solarrust @nlopin Игорь на созвоне сказал, что эта задача неактуальна, если это так, закройте, пожалуйста.

**Comment by solarrust** [comment]
Котики, мы ходим по кругу. Я ровно так сейчас и делаю — создаю ишью для Светы **руками**. Задача про автоматическое создание.

**Comment by igsekor** [comment]
> Вот тут вопрос вопросов, на самом деле. У них отдельная доска, но есть импорт из гитхабовских ишьюсов. 

Надо посмотреть, как сделана эта интеграция.

> Может быть перед закрытием ставить лейбу какую-то и по ней заводить задачку? Чтобы контролировать процесс, не везде помощь дизайнеров нужна. Плюс есть два вида задач для них: иллюстрации и инфографика.

Ну иллюстрации вряд ли автоматизировать получится. Только ишью. К тому же таких статей мало, это может стать поводом не переживать об этом.

Инфографика — наверное, с помощью ревью от Вали. Если апрув есть, то всё ок, если апрува нет, то либо запрос изменений со стороны Вали, либо автоишью в случае, когда сливается без её апрува. Может такая логика?

**Comment by igsekor** [comment]
Порешали в этих PR:

1. [Обновление списков материалов-кандидатов на редактирование](https://github.com/doka-guide/content/pull/1827)
2. [Добавляет автоштучки для дизайнеров](https://github.com/doka-guide/content/pull/1945)

**Comment by solarrust** [comment]
В итоге задачку можно закрывать?

**Comment by igsekor** [comment]
Да!
