### ISSUE TITLE
Лонгрид Errors

### ISSUE THREAD

**Issue by nlopin** [doka-guide/content#798]
Взять старую статью из ноушена и переделать.

Что нужно рассказать:
* типы ошибок, которые выплевывает JS
* как создавать свои ошибки

**Comment by alexbaumgertner** [comment]
Скиньте пожалуйста старую статью из ноушена — я попробую написать.

**Comment by nlopin** [comment]
Привет! Спасибо, что откликнулся!

Я приложил старую статью as-is. Думаю, что нужны два материала: первый чисто справочная статья по классу `Error`, а вторая уже в целом про обработку ошибок (у меня тоже есть черновик).

Давай начнем со справочной по Error? 

[Errors.pdf](https://github.com/doka-guide/content/files/7038660/Errors.pdf)

**Comment by Dissarion** [comment]
@nlopin @bespoyasov Кажется этот ишшью можно закрыть, так как статья появилась.
