### ISSUE TITLE
Поправить мета-информацию для блока «В работе»

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#831]
Файлы авторов блока «В работе» начинаются с обязательной мета-информации

```njk
---
tags:
  - practice
permalink: false
—-
```

Оказалось, что блок регистрозависимый, а в WebStorm эта мета-информация автоматически редактируется в 

```njk
---
 tags:
 - practice
   permalink: false
 ---
```

и сборка ломается. Надо внести правку в документацию для решения проблемы и автоматом подменить все вхождения для единообразности.

**Comment by furtivite** [comment]
Если написать так:

```njk
---
permalink: false
tags:
  - practice
---
```

всё работает и всем просто.

**Comment by pepelsbey** [comment]
Мне кажется, что завтра Вебшторм захочет ещё что-нибудь в мете отформатировать. Это будет погоня за тенью.

Может лучше разобраться, дефолтное ли это поведение или плагин-настройка чудят?

**Comment by furtivite** [comment]
Это может повторяться и в других IDE, потому что там явный список, а после него следующая строка, а в решении строка вроде как заканчивается, и начинается список, проблема решается.

**Comment by furtivite** [comment]
То что сборка не собирается с таким отступом — это дефолтное поведение 11ty

**Comment by pepelsbey** [comment]
> Это может повторяться и в других IDE, потому что там явный список

Это синтаксис YAML, а не Маркдаун. То есть там всё корректно и у нас есть много других мест, где список заканчивается каким-то ключом. Если редактор начинает это форматировать — это беда редактора. То, что Eleventy это не собирает — вполне справедливо.

**Comment by furtivite** [comment]
> Если редактор начинает это форматировать — это беда редактора.

Я понимаю, что это беда редактора и что он не должен это трогать, но он это трогает. И обычный `CMD` + `V` из документации или из другого файла автоматически ломает сборку. Можно было бы этого избежать. Давайте подумаем и решим.

**Comment by nlopin** [comment]
У меня так же вебшторм форматирует как бог на душу положит, но это проблема конкретного редактора. Нужно либо как-то автоматически проверять мету в файлах, либо проверять руками в пул реквестах.

Думаю, что уже сломанное нужно исправить.

Помнится мы говорили, что такая разметка нам не нужна и мы можем в коллекцию `practice` добавлять файлы по маске

**Comment by pepelsbey** [comment]
В принципе, есть какое-то количество [валидаторов YAML](https://www.npmjs.com/search?q=yaml%20validator) в npm.

**Comment by pepelsbey** [comment]
[Закинул твит](https://twitter.com/pepelsbey/status/1402392066206965766) с просьбой проверить, как ведёт себя WebStorm с [тестовым файлом](https://gist.githubusercontent.com/pepelsbey/24c46c2692702704342116b9a246867d/raw/4fd5f5e3bacb912a122c3833231de679b3a5f83a/why.md).

**Comment by nlopin** [comment]
> [Закинул твит](https://twitter.com/pepelsbey/status/1402392066206965766) с просьбой проверить, как ведёт себя WebStorm с [тестовым файлом](https://gist.githubusercontent.com/pepelsbey/24c46c2692702704342116b9a246867d/raw/4fd5f5e3bacb912a122c3833231de679b3a5f83a/why.md).

Я записал [демо проблемы](https://www.loom.com/share/168c848aea6745acbe8922bce657865a), чтобы мы все говорили об одном.

**Comment by nlopin** [comment]
Давайте поймем, что мы хотим решить. Егор этим тикетом предлагает поправить существующие ошибки. Мне кажется это и нужно сделать, а через месяц посмотреть, появились ли они снова. Возможно, это артефакты переноса статей и дальше всё будет нормально.

**Comment by pepelsbey** [comment]
Пулреквест Егора предлагает взять отдельный тип YAML-шапки и поменять местами ключи, чтобы при копировании внутри WebStorm не слетало форматирование. Мы не знаем, что происходит с форматированием типичной шапки статьи при такой вставке — может там тоже ломается. Или начнёт ломаться в каком-то другом сочетании ключей.

Я бы не хотел заводить прецедент, когда мы для ошибки одного редактора меняем структуру полей. Я бы лучше принял решение а) следить за метой при пулреквестах (мы увидим ошибки при тестовой сборке) и б) подумать над валидатором YAML-шапок, чтобы там были только нужные нам ключи в нужном порядке.

**Comment by furtivite** [comment]
> Мы не знаем, что происходит с форматированием типичной шапки статьи при такой вставке — может там тоже ломается. Или начнёт ломаться в каком-то другом сочетании ключей.

Веское замечание — там тоже всё ломается (был уверен, что вебшторм после списка может нормально работать с новым списком), если взять дефолтный вариант из примеров, и вставить в новый файл

<img width="926" alt="Снимок экрана 2021-06-09 в 12 46 44" src="https://user-images.githubusercontent.com/50330458/121332776-dc793700-c920-11eb-83c0-ab4b4a682d59.png">

Кажется, нам скорее нужен валидатор YAML-шапок. С этим согласен. 

Может как-то сделать интерфейс в прекоммите, например, который бы проверил наличие шапки, в принципе и предлагал дописать туда нужные поля, если они отсутствуют (или смотреть в файле-примере, если это нужно). А в остальных случаях вообще статьи можно было бы писать без меты.

**Comment by pepelsbey** [comment]
> Может как-то сделать интерфейс в прекоммите

Прекоммит выбивает тебя из понятного процесса, когда всё просто и привычно. Плюс он требует инструментов, а у нас контент принципиально голый. Не надо так. У нас есть шаблоны статей, у нас есть тесты в пулреквестах — вот так стоит следить за качеством кода.

**Comment by pepelsbey** [comment]
В общем, WebStorm не знает, что такое YAML-шапка в маркдауне и мы ничего не с этим не можем сделать в самой структуре шапки — он будет её ломать при вставке.

1. Давайте следить внимательнее
2. Обсудим написание валидатора
3. Кто-нибудь, заведите ишью в трекере JetBrains

**Comment by furtivite** [comment]
> Давайте следить внимательнее

Стоит ли об этом написать: авторам, в документации?

**Comment by pepelsbey** [comment]
> Стоит ли об этом написать: авторам, в документации?

Можно добавить пометку, мол, следите за форматированием YAML, особенно в WebStorm :D
